// GENERATED by cargo-arael (vendored javascript support). Do not edit.
// The 2D pose-graph reader of the g2o text format, for a browser page
// composing a generated model: VERTEX_SE2 and EDGE_SE2 records, with the
// information matrix's exact whitening. Values are plain objects,
// {x, y} for a 2D vector, {x, y, z} for a 3D one, and an array of row
// arrays for a matrix, the shapes the generated interface takes.

/** One 2D pose from a VERTEX_SE2 record. */
export class Pose2 {
  constructor(t, th) {
    this.t = { x: t.x, y: t.y };
    this.th = th;
  }
}

/**
 * One relative SE2 measurement from an EDGE_SE2 record: pose `b` seen
 * from pose `a`'s body frame. `info` is the information-matrix upper
 * triangle in file order (I11 I12 I13 I22 I23 I33).
 */
export class DeltaPose2 {
  constructor(a, b, dt, dth, info) {
    this.a = a;
    this.b = b;
    this.dt = { x: dt.x, y: dt.y };
    this.dth = dth;
    if (info.length !== 6) throw new Error("EDGE_SE2 needs 6 information entries");
    this.info = info.slice();
  }

  /**
   * [wt, wr] when the information matrix is diagonal with equal
   * translation entries; null when it is anything else.
   */
  isoSqrtInfo() {
    const [i11, i12, i13, i22, i23, i33] = this.info;
    if (Math.abs(i12) < 1e-9 && Math.abs(i13) < 1e-9 && Math.abs(i23) < 1e-9
        && Math.abs(i11 - i22) < 1e-9) {
      return [Math.sqrt(i11), Math.sqrt(i33)];
    }
    return null;
  }

  /**
   * Eigen factors {r, w} of the information matrix for exact whitening
   * of any symmetric information matrix: info = r * diag(w)^2 * r^T, so
   * the weighted residual is diag(w) * r^T * res. `r` is an array of
   * row arrays with the eigenvectors as columns, `w` is {x, y, z}.
   * Eigenvalues below zero clamp to zero weight.
   */
  eigenSqrtInfo() {
    const [i11, i12, i13, i22, i23, i33] = this.info;
    const { vectors, values } = symmetricEigen3([[i11, i12, i13], [i12, i22, i23], [i13, i23, i33]]);
    const w = values.map((v) => (v > 0.0 ? Math.sqrt(v) : 0.0));
    return { r: vectors, w: { x: w[0], y: w[1], z: w[2] } };
  }
}

/**
 * Eigenvectors (as the columns of an array of row arrays) and
 * eigenvalues (ascending) of a symmetric 3x3 matrix, by cyclic Jacobi
 * rotations.
 */
export function symmetricEigen3(m) {
  const a = m.map((row) => row.slice());
  const v = [[1, 0, 0], [0, 1, 0], [0, 0, 1]];
  for (let sweep = 0; sweep < 64; sweep++) {
    const off = Math.abs(a[0][1]) + Math.abs(a[0][2]) + Math.abs(a[1][2]);
    if (!(off > 1e-300)) break;
    for (let p = 0; p < 2; p++) {
      for (let q = p + 1; q < 3; q++) {
        if (a[p][q] === 0.0) continue;
        const theta = (a[q][q] - a[p][p]) / (2.0 * a[p][q]);
        const t = (theta >= 0.0 ? 1.0 : -1.0) / (Math.abs(theta) + Math.sqrt(theta * theta + 1.0));
        const c = 1.0 / Math.sqrt(t * t + 1.0);
        const s = t * c;
        for (let k = 0; k < 3; k++) {
          const akp = a[k][p], akq = a[k][q];
          a[k][p] = c * akp - s * akq;
          a[k][q] = s * akp + c * akq;
        }
        for (let k = 0; k < 3; k++) {
          const apk = a[p][k], aqk = a[q][k];
          a[p][k] = c * apk - s * aqk;
          a[q][k] = s * apk + c * aqk;
        }
        for (let k = 0; k < 3; k++) {
          const vkp = v[k][p], vkq = v[k][q];
          v[k][p] = c * vkp - s * vkq;
          v[k][q] = s * vkp + c * vkq;
        }
      }
    }
  }
  const idx = [0, 1, 2].sort((i, j) => a[i][i] - a[j][j]);
  const values = idx.map((i) => a[i][i]);
  const vectors = [0, 1, 2].map((r) => idx.map((j) => v[r][j]));
  return { vectors, values };
}

/** A 2D pose graph: poses and the relative measurements between them. */
export class Dataset2 {
  constructor() {
    this.poses = [];
    this.deltas = [];
  }

  /** Parse a 2D pose graph from g2o text. */
  static parse(text) {
    const ds = new Dataset2();
    const lines = text.split(/\r?\n/);
    for (let n = 0; n < lines.length; n++) {
      const f = lines[n].trim().split(/\s+/);
      if (f.length === 0 || f[0] === "") continue;
      const num = (s) => {
        const x = Number(s);
        if (s === undefined || Number.isNaN(x)) throw new Error(`g2o line ${n + 1}: bad number`);
        return x;
      };
      if (f[0] === "VERTEX_SE2") {
        if (num(f[1]) !== ds.poses.length) throw new Error(`g2o line ${n + 1}: vertex ids must be dense and ordered`);
        ds.poses.push(new Pose2({ x: num(f[2]), y: num(f[3]) }, num(f[4])));
      } else if (f[0] === "EDGE_SE2") {
        ds.deltas.push(new DeltaPose2(
          num(f[1]), num(f[2]), { x: num(f[3]), y: num(f[4]) }, num(f[5]),
          f.slice(6, 12).map(num)));
      }
    }
    for (const d of ds.deltas) {
      if (d.a >= ds.poses.length || d.b >= ds.poses.length) {
        throw new Error(`measurement references pose ${d.a} / ${d.b} of ${ds.poses.length}`);
      }
    }
    return ds;
  }

  /** Fetch and parse a 2D pose graph from a URL. */
  static async load(url) {
    const r = await fetch(url);
    if (!r.ok) throw new Error(`fetch ${url}: ${r.status}`);
    return Dataset2.parse(await r.text());
  }

  /** The graph back as g2o text. */
  toG2o() {
    const out = [];
    this.poses.forEach((p, i) => out.push(`VERTEX_SE2 ${i} ${p.t.x} ${p.t.y} ${p.th}`));
    for (const d of this.deltas) {
      out.push(`EDGE_SE2 ${d.a} ${d.b} ${d.dt.x} ${d.dt.y} ${d.dth} ${d.info.join(" ")}`);
    }
    return out.join("\n") + "\n";
  }
}
