// GENERATED by cargo-arael from the `Decay` model sidecar. Do not
// edit; regenerate with `cargo arael export`.
#pragma once

#include <cstdint>
#include <cstddef>
#include <cmath>
#include <iterator>
#include <memory>
#include "arael/math.hpp"
#include "arael/result.hpp"
#include "arael/solver.hpp"

namespace cxx_mr::decay {

/// The arael value vocabulary this interface uses, re-exported so a
/// single `using namespace cxx_mr::decay;` brings the model AND the math.
using arael::vect2;
using arael::vect3;
using arael::matrix2;
using arael::matrix3;
using arael::quatern;
using arael::vect2f;
using arael::vect2d;
using arael::vect3f;
using arael::vect3d;
using arael::matrix2f;
using arael::matrix2d;
using arael::matrix3f;
using arael::matrix3d;
using arael::quaternf;
using arael::quaternd;
using arael::option;
using arael::result;
using arael::LmStatus;
using arael::LmPreset;
using arael::LmConfigT;
using arael::LmResultT;
using arael::LmIterT;
using arael::LmTiming;
using arael::SchurPlan;
using arael::ReducedOrdering;
using arael::RouteFlops;
using arael::CovMode;
using arael::CovError;

/// Instantiations of the shared solver surface (arael/solver.hpp) at
/// this model's precision, plus the config constructor that fetches
/// the preset's actual Rust values through this root's FFI.
using LmIter = LmIterT<float>;

struct LmConfig : LmConfigT<float> {
    LmConfig(LmPreset p = LmPreset::Defaults);
    static LmConfig defaults() { return LmConfig(LmPreset::Defaults); }
    static LmConfig conservative() { return LmConfig(LmPreset::Conservative); }
    static LmConfig well_conditioned() { return LmConfig(LmPreset::WellConditioned); }
    static LmConfig ill_conditioned() { return LmConfig(LmPreset::IllConditioned); }
};

/// Typed handle into the collection that issued it -- the C++
/// spelling of Rust's `Ref<Cell>`. Default-constructed it is the
/// null sentinel (same as Rust `Ref::default()`).
struct CellRef {
    uint32_t raw = UINT32_MAX;
    bool valid() const { return raw != UINT32_MAX; }
};

namespace ffi {
struct Decay;
struct Cell;

extern "C" {
float decay_cell_v(const Cell*);
void decay_cell_set_v(Cell*, float);
bool decay_cell_v_optimize(const Cell*);
void decay_cell_v_set_optimize(Cell*, bool);
float decay_cell_t(const Cell*);
void decay_cell_set_t(Cell*, float);
float decay_cell_w(const Cell*);
void decay_cell_set_w(Cell*, float);
int32_t decay_assemble_covariance(Decay*, uint32_t);
int32_t decay_cell_marginal_cov(Decay*, const Cell*, double*, uint32_t);
int32_t decay_cell_conditional_cov(Decay*, const Cell*, double*, uint32_t);
int32_t decay_cell_std_dev(Decay*, const Cell*, double*, uint32_t);
int32_t decay_cell_cell_cross_cov(Decay*, const Cell*, const Cell*, double*, uint32_t);
uint32_t decay_cells_len(const Decay*);
void decay_cells_reserve(Decay*, uint32_t);
Cell* decay_cells_push(Decay*);
Cell* decay_cells_at(Decay*, uint32_t);
bool decay_cells_pop(Decay*);
void decay_cells_clear(Decay*);
void decay_cells_truncate(Decay*, uint32_t);
uint32_t decay_cells_ref_at(const Decay*, uint32_t);
uint32_t decay_cells_first_ref(const Decay*);
uint32_t decay_cells_last_ref(const Decay*);
Cell* decay_cells_get(Decay*, uint32_t);
bool decay_cells_contains(const Decay*, uint32_t);
Cell* decay_cells_try_get(Decay*, uint32_t);
double decay_cost(Decay*);
int32_t decay_solve_band(Decay*, uint32_t, const LmConfig*, LmResultT<float>*);
void decay_lm_config(uint32_t, LmConfig*);
Decay* decay_new(void);
void decay_free(Decay*);
const char* decay_last_error(const Decay*);
const char* decay_validate(Decay*);
int32_t decay_solve_dense(Decay*, const LmConfig*, LmResultT<float>*);
int32_t decay_solve_sparse(Decay*, const LmConfig*, LmResultT<float>*);
const char* decay_result_report(void*, bool);
bool decay_result_plan(const void*, SchurPlan*);
void decay_result_free(void*);
}
} // namespace ffi

inline LmConfig::LmConfig(LmPreset p) {
    ffi::decay_lm_config(uint32_t(p), this);
}

/// A completed solve: the plain result fields plus ownership of the
/// full Rust result behind them. report()/pretty_report() render the
/// Rust-side text (status, cost, the timing breakdown and the
/// backend's plan when gathered); plan() returns the sparse backend's
/// SchurPlan as data. Copies share ownership of the Rust result.
class LmResult : public LmResultT<float> {
public:
    LmResult() : LmResultT<float>() {}
    explicit LmResult(const LmResultT<float>& raw) : LmResultT<float>(raw) {
        if (detail)
            guard_ = std::shared_ptr<void>(detail, ffi::decay_result_free);
    }
    /// Text report; the pointer is valid until the next report call
    /// on this result or the destruction of its last copy.
    const char* report() const {
        return detail ? ffi::decay_result_report(detail, false) : "";
    }
    /// report() with colour and box-drawing glyphs.
    const char* pretty_report() const {
        return detail ? ffi::decay_result_report(detail, true) : "";
    }
    /// The sparse backend's plan; empty for dense and band solves.
    option<SchurPlan> plan() const {
        SchurPlan p;
        if (detail && ffi::decay_result_plan(detail, &p))
            return p;
        return {};
    }

private:
    std::shared_ptr<void> guard_;
};

/// The Err side of a solve: SolverFailed or Panicked, the text from
/// last_error() (valid until the next call on the model), and the
/// best accepted state before the break when the solve got that far.
struct SolveError {
    LmStatus status;
    const char* message;
    option<LmResult> partial;
};

using SolveResult = result<LmResult, SolveError>;

/// A `Cell` in its owner's storage; a thin pointer wrapper (validity
/// follows the storage -- see the owning container).
class Cell {
public:
    /// Optimized parameters this entity contributes to the solve.
    static constexpr uint32_t param_count = 1;
    Cell() : h_(nullptr) {}
    explicit Cell(ffi::Cell* p) : h_(p) {}
    /// False when default-constructed (e.g. inside an empty option).
    bool valid() const { return h_ != nullptr; }
    /// The underlying C pointer -- the relaxed escape hatch.
    ffi::Cell* raw() const { return h_; }
    float v() const { return ffi::decay_cell_v(h_); }
    void set_v(float v) { ffi::decay_cell_set_v(h_, v); }
    bool v_optimize() const { return ffi::decay_cell_v_optimize(h_); }
    void set_v_optimize(bool v) { ffi::decay_cell_v_set_optimize(h_, v); }
    float t() const { return ffi::decay_cell_t(h_); }
    void set_t(float v) { ffi::decay_cell_set_t(h_, v); }
    float w() const { return ffi::decay_cell_w(h_); }
    void set_w(float v) { ffi::decay_cell_set_w(h_, v); }
private:
    ffi::Cell* h_;
};

/// Covariance prepared at the solution (root.assemble_covariance);
/// queries answer per-entity marginal blocks. Valid until the model
/// is dropped or reassembled.
class Covariance {
public:
    Covariance() : h_(nullptr) {}
    explicit Covariance(ffi::Decay* h) : h_(h) {}
    /// Per-parameter standard deviations into out; returns the count
    /// or a negative code. Works on every CovMode incl. TriDiagonal.
    int32_t std_dev(const Cell& e, double* out, uint32_t cap) {
        return ffi::decay_cell_std_dev(h_, e.raw(), out, cap);
    }
    /// Row-major dim x dim conditional covariance (all other
    /// parameters held fixed) into out; returns dim or a negative code.
    int32_t conditional(const Cell& e, double* out, uint32_t cap) {
        return ffi::decay_cell_conditional_cov(h_, e.raw(), out, cap);
    }
    result<double, CovError> marginal(const Cell& e) {
        double b[1];
        if (ffi::decay_cell_marginal_cov(h_, e.raw(), b, 1) < 0) return fail<double>();
        return result<double, CovError>::ok(b[0]);
    }
    /// Row-major Cell::param_count x Cell::param_count cross-covariance
    /// into out; returns the row count or a negative code.
    int32_t cross(const Cell& a, const Cell& b, double* out, uint32_t cap) {
        return ffi::decay_cell_cell_cross_cov(h_, a.raw(), b.raw(), out, cap);
    }
private:
    template<class T> result<T, CovError> fail() {
        return result<T, CovError>::err({ffi::decay_last_error(h_)});
    }
    ffi::Decay* h_;
};

/// `Decay.cells`. Element pointers are STABLE across pushes (chunked storage).
class DecayCellsVec {
public:
    explicit DecayCellsVec(ffi::Decay* h) : h_(h) {}
    uint32_t size() const { return ffi::decay_cells_len(h_); }
    bool empty() const { return size() == 0; }
    void reserve(uint32_t additional) { ffi::decay_cells_reserve(h_, additional); }
    /// Appends a default element and returns a wrapper for it.
    ///
    /// The wrapper holds a pointer INTO the collection, so it follows the
    /// std::vector rule: any later push may reallocate, and every wrapper
    /// taken before it -- including wrappers into collections nested inside
    /// these elements -- is then dangling. Either reserve() the count up
    /// front, or re-take the wrapper with operator[] after the growth.
    /// To hold on to an element across pushes, keep its Ref, not a wrapper.
    Cell push() { return Cell(ffi::decay_cells_push(h_)); }
    /// Wrapper for element `i`; see push() on how long it stays valid.
    Cell operator[](uint32_t i) { return Cell(ffi::decay_cells_at(h_, i)); }
    /// Front/back of a non-empty vec (empty = UB, like STL).
    Cell front() { return (*this)[0]; }
    Cell back() { return (*this)[size() - 1]; }
    /// Drops the last element; false when already empty.
    bool pop() { return ffi::decay_cells_pop(h_); }
    void clear() { ffi::decay_cells_clear(h_); }
    void truncate(uint32_t n) { ffi::decay_cells_truncate(h_, n); }
    CellRef ref_at(uint32_t i) const { return CellRef{ffi::decay_cells_ref_at(h_, i)}; }
    /// Ref of the first/last element; null when empty.
    CellRef first_ref() const { return CellRef{ffi::decay_cells_first_ref(h_)}; }
    CellRef last_ref() const { return CellRef{ffi::decay_cells_last_ref(h_)}; }
    Cell get(CellRef r) { return Cell(ffi::decay_cells_get(h_, r.raw)); }
    /// True while r addresses a live element here.
    bool contains(CellRef r) const { return ffi::decay_cells_contains(h_, r.raw); }
    /// Like get, but empty for a stale or foreign ref.
    option<Cell> try_get(CellRef r) {
        ffi::Cell* p = ffi::decay_cells_try_get(h_, r.raw);
        return p ? option<Cell>(Cell(p)) : option<Cell>();
    }
    /// Bidirectional iterator. Standard C++ contract: modifying the
    /// container while iterating is undefined behavior. Dereference
    /// yields a value wrapper (Cell), like vector<bool> --
    /// reference is a value type.
    class iterator {
    public:
        using iterator_category = std::bidirectional_iterator_tag;
        using value_type = Cell;
        using difference_type = std::ptrdiff_t;
        using reference = Cell;
        struct arrow { Cell v; Cell* operator->() { return &v; } };
        using pointer = arrow;

        iterator() : h_(nullptr), i_(0) {}
        iterator(ffi::Decay* h, uint32_t i) : h_(h), i_(i) {}
        Cell operator*() const { return Cell(ffi::decay_cells_at(h_, i_)); }
        arrow operator->() const { return arrow{**this}; }
        iterator& operator++() { ++i_; return *this; }
        iterator& operator--() { --i_; return *this; }
        iterator operator++(int) { iterator t = *this; ++*this; return t; }
        iterator operator--(int) { iterator t = *this; --*this; return t; }
        bool operator==(const iterator& o) const { return i_ == o.i_; }
        bool operator!=(const iterator& o) const { return i_ != o.i_; }
    private:
        ffi::Decay* h_;
        uint32_t i_;
    };
    iterator begin() { return iterator(h_, 0); }
    iterator end() { return iterator(h_, size()); }
    class reverse_iterator {
    public:
        using iterator_category = std::bidirectional_iterator_tag;
        using value_type = Cell;
        using difference_type = std::ptrdiff_t;
        using reference = Cell;
        using pointer = iterator::arrow;

        reverse_iterator() {}
        explicit reverse_iterator(iterator base) : base_(base) {}
        iterator base() const { return base_; }
        Cell operator*() const { iterator t = base_; --t; return *t; }
        pointer operator->() const { return pointer{**this}; }
        reverse_iterator& operator++() { --base_; return *this; }
        reverse_iterator& operator--() { ++base_; return *this; }
        reverse_iterator operator++(int) { reverse_iterator t = *this; ++*this; return t; }
        reverse_iterator operator--(int) { reverse_iterator t = *this; --*this; return t; }
        bool operator==(const reverse_iterator& o) const { return base_ == o.base_; }
        bool operator!=(const reverse_iterator& o) const { return base_ != o.base_; }
    private:
        iterator base_;
    };
    reverse_iterator rbegin() { return reverse_iterator(end()); }
    reverse_iterator rend() { return reverse_iterator(begin()); }
private:
    ffi::Decay* h_;
};

/// The `Decay` model. Owns the Rust-side object; move-only.
class Decay {
public:
    Decay() : h_(ffi::decay_new()) {}
    ~Decay() { if (h_) ffi::decay_free(h_); }
    Decay(const Decay&) = delete;
    Decay& operator=(const Decay&) = delete;
    Decay(Decay&& o) noexcept : h_(o.h_) { o.h_ = nullptr; }
    Decay& operator=(Decay&& o) noexcept {
        if (this != &o) {
            if (h_) ffi::decay_free(h_);
            h_ = o.h_;
            o.h_ = nullptr;
        }
        return *this;
    }

    DecayCellsVec cells() { return DecayCellsVec(h_); }

    /// Ok(LmResult) for every healthy termination, Err(SolveError) for
    /// a solve failure (-1) or a caught panic (-2) -- the same split
    /// Rust's SolveResult makes. The error carries the partial result
    /// when the solver got past its first assembly.
    SolveResult solve_dense(const LmConfig& cfg = LmConfig{}) {
        LmResultT<float> raw;
        return finish_(ffi::decay_solve_dense(h_, &cfg, &raw), raw);
    }
    SolveResult solve_sparse(const LmConfig& cfg = LmConfig{}) {
        LmResultT<float> raw;
        return finish_(ffi::decay_solve_sparse(h_, &cfg, &raw), raw);
    }
    /// Band Cholesky solve for banded Hessians; kd is the half-bandwidth
    /// in scalar parameters.
    SolveResult solve_band(uint32_t kd, const LmConfig& cfg = LmConfig{}) {
        LmResultT<float> raw;
        return finish_(ffi::decay_solve_band(h_, kd, &cfg, &raw), raw);
    }
    /// Total cost at the current parameter values (f64 evaluation).
    double cost() { return ffi::decay_cost(h_); }
    /// Prepare the covariance at the current (solved) parameters; query
    /// per-entity marginals on the returned view.
    result<Covariance, CovError> assemble_covariance(CovMode mode = CovMode::AllMarginals) {
        if (ffi::decay_assemble_covariance(h_, uint32_t(mode)) != 0)
            return result<Covariance, CovError>::err({last_error()});
        return result<Covariance, CovError>::ok(Covariance(h_));
    }
    /// Empty string when the model is clean, the Diagnostic text
    /// otherwise. The returned pointer is valid until the next call on
    /// this model.
    const char* validate() { return ffi::decay_validate(h_); }
    const char* last_error() const { return ffi::decay_last_error(h_); }

private:
    SolveResult finish_(int32_t code, const LmResultT<float>& raw) {
        if (code >= 0) return SolveResult::ok(LmResult(raw));
        SolveError e{static_cast<LmStatus>(code), last_error(), {}};
        if (raw.detail) e.partial = LmResult(raw);
        return SolveResult::err(e);
    }

    ffi::Decay* h_;
};

} // namespace cxx_mr::decay
