// GENERATED by cargo-arael from the `Line` model sidecar. Do not
// edit; regenerate with `cargo arael export`.
#pragma once

#include <cstdint>
#include <cstddef>
#include <cmath>
#include <iterator>
#include <memory>
#include <vector>
#include "arael/math.hpp"
#include "arael/result.hpp"
#include "arael/solver.hpp"

namespace cxx_mr::line {

/// The arael value vocabulary this interface uses, re-exported so a
/// single `using namespace cxx_mr::line;` brings the model AND the math.
using arael::vect2;
using arael::vect3;
using arael::matrix2;
using arael::matrix3;
using arael::quatern;
using arael::vect2f;
using arael::vect2d;
using arael::vect3f;
using arael::vect3d;
using arael::matrix2f;
using arael::matrix2d;
using arael::matrix3f;
using arael::matrix3d;
using arael::quaternf;
using arael::quaternd;
using arael::option;
using arael::result;
using arael::LmStatus;
using arael::LmPreset;
using arael::LmConfigT;
using arael::LmResultT;
using arael::LmIterT;
using arael::LmStep;
using arael::LmTiming;
using arael::SolveFailureKind;
using arael::DiagonalFault;
using arael::SolveFailure;
using arael::SchurPlan;
using arael::ReducedOrdering;
using arael::RouteFlops;
using arael::SchurPolicy;
using arael::FaerOrdering;
using arael::EnvelopeMode;
using arael::BlockSupernodalMode;
using arael::SchurSolve;
using arael::SparseOptionsT;
using arael::LogLevel;
using arael::PanicError;
using arael::CovMode;
using arael::CovOrdering;
using arael::CovOptions;
using arael::CovPlan;
using arael::CovCandidateFlops;
using arael::CovError;

/// Instantiations of the shared solver surface (arael/solver.hpp) at
/// this model's precision, plus the config constructor that fetches
/// the preset's actual Rust values through this root's FFI.
using LmIter = LmIterT<double>;

struct LmConfig : LmConfigT<double> {
    LmConfig(LmPreset p = LmPreset::Defaults);
    static LmConfig defaults() { return LmConfig(LmPreset::Defaults); }
    static LmConfig conservative() { return LmConfig(LmPreset::Conservative); }
    static LmConfig well_conditioned() { return LmConfig(LmPreset::WellConditioned); }
    static LmConfig ill_conditioned() { return LmConfig(LmPreset::IllConditioned); }
};

/// The sparse backend's options, holding the actual Rust defaults
/// (fetched through the FFI at construction). Edit fields, pass to
/// solve_sparse.
struct SparseOptions : SparseOptionsT {
    SparseOptions();
};

/// Typed handle into the collection that issued it -- the C++
/// spelling of Rust's `Ref<Ob>`. Default-constructed it is the
/// null sentinel (same as Rust `Ref::default()`).
struct ObRef {
    uint32_t raw = UINT32_MAX;
    bool valid() const { return raw != UINT32_MAX; }
};

namespace ffi {
struct Line;
struct Ob;

extern "C" {
double line_ob_x(const Ob*);
void line_ob_set_x(Ob*, double);
double line_ob_y(const Ob*);
void line_ob_set_y(Ob*, double);
struct LineCov;
int32_t line_assemble_covariance(Line*, uint32_t, LineCov**);
int32_t line_assemble_covariance_with(Line*, uint32_t, uint32_t, uint32_t, LineCov**);
const char* line_cov_error(const LineCov*);
void line_cov_plan(const LineCov*, CovPlan*);
void line_cov_free(LineCov*);
double line_k(const Line*);
void line_set_k(Line*, double);
bool line_k_optimize(const Line*);
void line_k_set_optimize(Line*, bool);
uint32_t line_obs_len(const Line*);
void line_obs_reserve(Line*, uint32_t);
Ob* line_obs_push(Line*);
Ob* line_obs_at(Line*, uint32_t);
bool line_obs_pop(Line*);
void line_obs_clear(Line*);
void line_obs_truncate(Line*, uint32_t);
double line_cost(Line*);
int32_t line_solve_band(Line*, uint32_t, const LmConfig*, LmResultT<double>*);
void line_lm_config(uint32_t, LmConfig*);
Line* line_new(void);
void line_free(Line*);
const char* line_last_error(const Line*);
bool line_last_failure(const Line*, SolveFailure*);
const char* line_validate(Line*);
void line_set_log_level(uint32_t);
void line_sparse_options(SparseOptions*);
int32_t line_solve_dense(Line*, const LmConfig*, LmResultT<double>*);
int32_t line_solve_sparse(Line*, const LmConfig*, const SparseOptions*, LmResultT<double>*);
const char* line_result_report(void*, bool);
bool line_result_plan(const void*, SchurPlan*);
uint64_t line_result_steps(const void*, LmStep*, uint64_t);
void line_result_free(void*);
struct LineSession;
LineSession* line_session_new(const SparseOptions*);
void line_session_free(LineSession*);
void line_session_invalidate(LineSession*);
int32_t line_session_solve(LineSession*, Line*, const LmConfig*, LmResultT<double>*);
}
} // namespace ffi

inline LmConfig::LmConfig(LmPreset p) {
    ffi::line_lm_config(uint32_t(p), this);
}

inline SparseOptions::SparseOptions() {
    ffi::line_sparse_options(this);
}

/// Drop arael log messages above `level` (Info -- everything -- is
/// the default). Process-wide: all models and roots share it.
inline void set_log_level(LogLevel level) {
    ffi::line_set_log_level(uint32_t(level));
}

/// A completed solve: the plain result fields plus ownership of the
/// full Rust result behind them. report()/pretty_report() render the
/// Rust-side text (status, cost, the timing breakdown and the
/// backend's plan when gathered); plan() returns the sparse backend's
/// SchurPlan as data, steps() the per-attempt timeline. Copies share
/// ownership of the Rust result.
class LmResult : public LmResultT<double> {
public:
    LmResult() : LmResultT<double>() {}
    explicit LmResult(const LmResultT<double>& raw) : LmResultT<double>(raw) {
        if (detail)
            guard_ = std::shared_ptr<void>(detail, ffi::line_result_free);
    }
    /// Text report; the pointer is valid until the next report call
    /// on this result or the destruction of its last copy.
    const char* report() const {
        return detail ? ffi::line_result_report(detail, false) : "";
    }
    /// report() with colour and box-drawing glyphs.
    const char* pretty_report() const {
        return detail ? ffi::line_result_report(detail, true) : "";
    }
    /// The sparse backend's plan; empty for dense and band solves.
    option<SchurPlan> plan() const {
        SchurPlan p;
        if (detail && ffi::line_result_plan(detail, &p))
            return p;
        return {};
    }
    /// The per-attempt timeline (Rust's LmTiming::steps); empty
    /// unless the solve ran with gather_timing.
    std::vector<LmStep> steps() const {
        std::vector<LmStep> out;
        if (!detail)
            return out;
        out.resize(ffi::line_result_steps(detail, nullptr, 0));
        if (!out.empty())
            ffi::line_result_steps(detail, out.data(), out.size());
        return out;
    }

private:
    std::shared_ptr<void> guard_;
};

/// The Err side of a solve: SolverFailed, the text from
/// last_error() (valid until the next call on the model), the
/// best accepted state before the break when the solve got that
/// far, and the structured failure (which kind, which parameter /
/// row / block index) in `failure`.
struct SolveError {
    LmStatus status;
    const char* message;
    option<LmResult> partial;
    SolveFailure failure;
};

using SolveResult = result<LmResult, SolveError>;

/// A `Ob` in its owner's storage; a thin pointer wrapper (validity
/// follows the storage -- see the owning container).
class Ob {
public:
    /// Optimized parameters this entity contributes to the solve.
    static constexpr uint32_t param_count = 0;
    Ob() : h_(nullptr) {}
    explicit Ob(ffi::Ob* p) : h_(p) {}
    /// False when default-constructed (e.g. inside an empty option).
    bool valid() const { return h_ != nullptr; }
    /// The underlying C pointer -- the relaxed escape hatch.
    ffi::Ob* raw() const { return h_; }
    double x() const { return ffi::line_ob_x(h_); }
    void set_x(double v) { ffi::line_ob_set_x(h_, v); }
    double y() const { return ffi::line_ob_y(h_); }
    void set_y(double v) { ffi::line_ob_set_y(h_, v); }
private:
    ffi::Ob* h_;
};

/// An assembled covariance (root.assemble_covariance), OWNED: copies
/// share it, the last copy releases it, and later assemblies are
/// independent. Entity arguments must come from the live model.
class Covariance {
public:
    Covariance() : c_(nullptr) {}
    explicit Covariance(ffi::LineCov* c)
        : c_(c), guard_(c, ffi::line_cov_free) {}
    /// Error text of the last failed query on this assembly.
    const char* last_error() const { return ffi::line_cov_error(c_); }
    /// What the assembly decided -- the ordering it kept, what the
    /// candidates priced at, and how many symbolics it built.
    CovPlan plan() const {
        CovPlan p;
        ffi::line_cov_plan(c_, &p);
        return p;
    }
private:
    /// A caught Rust panic (-2) throws; other codes pass through.
    int32_t ck_(int32_t n) const {
        if (n == -2) throw PanicError(ffi::line_cov_error(c_));
        return n;
    }
    template<class T> result<T, CovError> fail() {
        return result<T, CovError>::err({ffi::line_cov_error(c_)});
    }
    ffi::LineCov* c_;
    std::shared_ptr<void> guard_;
};

/// `Line.obs`. std::vec::Vec storage: pushes may MOVE elements -- re-fetch element refs after a push.
class LineObsVec {
public:
    explicit LineObsVec(ffi::Line* h) : h_(h) {}
    uint32_t size() const { return ffi::line_obs_len(h_); }
    bool empty() const { return size() == 0; }
    void reserve(uint32_t additional) { ffi::line_obs_reserve(h_, additional); }
    /// Appends a default element and returns a wrapper for it.
    ///
    /// The wrapper holds a pointer INTO the collection, so it follows the
    /// std::vector rule: any later push may reallocate, and every wrapper
    /// taken before it -- including wrappers into collections nested inside
    /// these elements -- is then dangling. Either reserve() the count up
    /// front, or re-take the wrapper with operator[] after the growth.
    /// To hold on to an element across pushes, keep its Ref, not a wrapper.
    Ob push() { return Ob(ffi::line_obs_push(h_)); }
    /// Wrapper for element `i`; see push() on how long it stays valid.
    Ob operator[](uint32_t i) { return Ob(ffi::line_obs_at(h_, i)); }
    /// Front/back of a non-empty vec (empty = UB, like STL).
    Ob front() { return (*this)[0]; }
    Ob back() { return (*this)[size() - 1]; }
    /// Drops the last element; false when already empty.
    bool pop() { return ffi::line_obs_pop(h_); }
    void clear() { ffi::line_obs_clear(h_); }
    void truncate(uint32_t n) { ffi::line_obs_truncate(h_, n); }
    /// Bidirectional iterator. Standard C++ contract: modifying the
    /// container while iterating is undefined behavior. Dereference
    /// yields a value wrapper (Ob), like vector<bool> --
    /// reference is a value type.
    class iterator {
    public:
        using iterator_category = std::bidirectional_iterator_tag;
        using value_type = Ob;
        using difference_type = std::ptrdiff_t;
        using reference = Ob;
        struct arrow { Ob v; Ob* operator->() { return &v; } };
        using pointer = arrow;

        iterator() : h_(nullptr), i_(0) {}
        iterator(ffi::Line* h, uint32_t i) : h_(h), i_(i) {}
        Ob operator*() const { return Ob(ffi::line_obs_at(h_, i_)); }
        arrow operator->() const { return arrow{**this}; }
        iterator& operator++() { ++i_; return *this; }
        iterator& operator--() { --i_; return *this; }
        iterator operator++(int) { iterator t = *this; ++*this; return t; }
        iterator operator--(int) { iterator t = *this; --*this; return t; }
        bool operator==(const iterator& o) const { return i_ == o.i_; }
        bool operator!=(const iterator& o) const { return i_ != o.i_; }
    private:
        ffi::Line* h_;
        uint32_t i_;
    };
    iterator begin() { return iterator(h_, 0); }
    iterator end() { return iterator(h_, size()); }
    class reverse_iterator {
    public:
        using iterator_category = std::bidirectional_iterator_tag;
        using value_type = Ob;
        using difference_type = std::ptrdiff_t;
        using reference = Ob;
        using pointer = iterator::arrow;

        reverse_iterator() {}
        explicit reverse_iterator(iterator base) : base_(base) {}
        iterator base() const { return base_; }
        Ob operator*() const { iterator t = base_; --t; return *t; }
        pointer operator->() const { return pointer{**this}; }
        reverse_iterator& operator++() { --base_; return *this; }
        reverse_iterator& operator--() { ++base_; return *this; }
        reverse_iterator operator++(int) { reverse_iterator t = *this; ++*this; return t; }
        reverse_iterator operator--(int) { reverse_iterator t = *this; --*this; return t; }
        bool operator==(const reverse_iterator& o) const { return base_ == o.base_; }
        bool operator!=(const reverse_iterator& o) const { return base_ != o.base_; }
    private:
        iterator base_;
    };
    reverse_iterator rbegin() { return reverse_iterator(end()); }
    reverse_iterator rend() { return reverse_iterator(begin()); }
private:
    ffi::Line* h_;
};

/// The `Line` model. Owns the Rust-side object; move-only.
class Line {
public:
    Line() : h_(ffi::line_new()) {}
    ~Line() { if (h_) ffi::line_free(h_); }
    Line(const Line&) = delete;
    Line& operator=(const Line&) = delete;
    Line(Line&& o) noexcept : h_(o.h_) { o.h_ = nullptr; }
    Line& operator=(Line&& o) noexcept {
        if (this != &o) {
            if (h_) ffi::line_free(h_);
            h_ = o.h_;
            o.h_ = nullptr;
        }
        return *this;
    }

    double k() const { return ffi::line_k(h_); }
    void set_k(double v) { ffi::line_set_k(h_, v); }
    bool k_optimize() const { return ffi::line_k_optimize(h_); }
    void set_k_optimize(bool v) { ffi::line_k_set_optimize(h_, v); }
    LineObsVec obs() { return LineObsVec(h_); }

    /// Ok(LmResult) for every healthy termination, Err(SolveError) for
    /// a solve failure (-1); a caught Rust panic throws PanicError.
    /// The Ok/Err division is the same split
    /// Rust's SolveResult makes. The error carries the partial result
    /// when the solver got past its first assembly.
    SolveResult solve_dense(const LmConfig& cfg = LmConfig{}) {
        LmResultT<double> raw;
        return finish_(ffi::line_solve_dense(h_, &cfg, &raw), raw);
    }
    SolveResult solve_sparse(const LmConfig& cfg = LmConfig{}) {
        LmResultT<double> raw;
        return finish_(ffi::line_solve_sparse(h_, &cfg, nullptr, &raw), raw);
    }
    /// solve_sparse with explicit backend options: ordering, Schur
    /// policy, the envelope route.
    SolveResult solve_sparse(const LmConfig& cfg, const SparseOptions& opts) {
        LmResultT<double> raw;
        return finish_(ffi::line_solve_sparse(h_, &cfg, &opts, &raw), raw);
    }
    /// Band Cholesky solve for banded Hessians; kd is the half-bandwidth
    /// in scalar parameters.
    SolveResult solve_band(uint32_t kd, const LmConfig& cfg = LmConfig{}) {
        LmResultT<double> raw;
        return finish_(ffi::line_solve_band(h_, kd, &cfg, &raw), raw);
    }
    /// Total cost at the current parameter values (f64 evaluation).
    double cost() { return ffi::line_cost(h_); }

    /// Prepare the covariance at the current (solved) parameters; query
    /// per-entity marginals on the returned view.
    result<Covariance, CovError> assemble_covariance(CovMode mode = CovMode::AllMarginals) {
        return assemble_covariance(mode, CovOptions{});
    }
    /// The same, with the assembly spelled out instead of left to the
    /// defaults. The covariance is the same either way; the options decide
    /// what producing it costs.
    result<Covariance, CovError> assemble_covariance(CovMode mode, const CovOptions& opts) {
        ffi::LineCov* c = nullptr;
        int32_t code = ffi::line_assemble_covariance_with(
            h_, uint32_t(mode), uint32_t(opts.ordering),
            uint32_t(opts.block_supernodal), &c);
        if (code == -2) throw PanicError(last_error());
        if (code != 0)
            return result<Covariance, CovError>::err({last_error()});
        return result<Covariance, CovError>::ok(Covariance(c));
    }
    /// Empty string when the model is clean, the Diagnostic text
    /// otherwise. The returned pointer is valid until the next call on
    /// this model.
    const char* validate() { return ffi::line_validate(h_); }
    const char* last_error() const { return ffi::line_last_error(h_); }

private:
    friend class LmSession;

    SolveResult finish_(int32_t code, const LmResultT<double>& raw) {
        if (code == -2) throw PanicError(last_error());
        if (code >= 0) return SolveResult::ok(LmResult(raw));
        SolveError e{static_cast<LmStatus>(code), last_error(), {}, {}};
        ffi::line_last_failure(h_, &e.failure);
        if (raw.detail) e.partial = LmResult(raw);
        return SolveResult::err(e);
    }

    ffi::Line* h_;
};

/// Warm reuse over repeated sparse solves (Rust's LmSession): keeps
/// the analysis -- pattern, ordering, symbolic factorization, Schur
/// plan -- across solves, so only the first pays for it. Warm solves
/// are bit-identical to cold ones. A parameter-count change
/// re-analyzes by itself; call invalidate() after a structural change
/// at the same count (solving warm through one is undefined).
/// Move-only.
class LmSession {
public:
    LmSession() : s_(ffi::line_session_new(nullptr)) {}
    /// Session over explicit backend options (see SparseOptions).
    explicit LmSession(const SparseOptions& opts)
        : s_(ffi::line_session_new(&opts)) {}
    ~LmSession() { if (s_) ffi::line_session_free(s_); }
    LmSession(const LmSession&) = delete;
    LmSession& operator=(const LmSession&) = delete;
    LmSession(LmSession&& o) noexcept : s_(o.s_) { o.s_ = nullptr; }
    LmSession& operator=(LmSession&& o) noexcept {
        if (this != &o) {
            if (s_) ffi::line_session_free(s_);
            s_ = o.s_;
            o.s_ = nullptr;
        }
        return *this;
    }
    /// Solve through the session; contract as Line::solve_sparse.
    SolveResult solve(Line& m, const LmConfig& cfg = LmConfig{}) {
        LmResultT<double> raw;
        return m.finish_(ffi::line_session_solve(s_, m.h_, &cfg, &raw), raw);
    }
    /// Drop the learned structure; the next solve runs cold.
    void invalidate() { ffi::line_session_invalidate(s_); }

private:
    ffi::LineSession* s_;
};

} // namespace cxx_mr::line
