// GENERATED by cargo-arael from the `Line` model sidecar. Do not
// edit; regenerate with `cargo arael export`.
#pragma once

#include <cstdint>
#include <cstddef>
#include <cmath>
#include <iterator>
#include "arael/math.hpp"
#include "arael/result.hpp"
#include "arael/solver.hpp"

namespace cxx_mr::line {

/// The arael value vocabulary this interface uses, re-exported so a
/// single `using namespace cxx_mr::line;` brings the model AND the math.
using arael::vect2;
using arael::vect3;
using arael::matrix2;
using arael::matrix3;
using arael::quatern;
using arael::vect2f;
using arael::vect2d;
using arael::vect3f;
using arael::vect3d;
using arael::matrix2f;
using arael::matrix2d;
using arael::matrix3f;
using arael::matrix3d;
using arael::quaternf;
using arael::quaternd;
using arael::option;
using arael::result;
using arael::LmStatus;
using arael::LmPreset;
using arael::LmConfigT;
using arael::LmResultT;
using arael::LmIterT;
using arael::LmTiming;
using arael::SolveResultT;
using arael::SolveError;
using arael::CovMode;
using arael::CovError;

/// Instantiations of the shared solver surface (arael/solver.hpp) at
/// this model's precision, plus the config constructor that fetches
/// the preset's actual Rust values through this root's FFI.
using LmResult = LmResultT<double>;
using LmIter = LmIterT<double>;
using SolveResult = SolveResultT<double>;

struct LmConfig : LmConfigT<double> {
    LmConfig(LmPreset p = LmPreset::Defaults);
    static LmConfig defaults() { return LmConfig(LmPreset::Defaults); }
    static LmConfig conservative() { return LmConfig(LmPreset::Conservative); }
    static LmConfig well_conditioned() { return LmConfig(LmPreset::WellConditioned); }
};

/// Typed handle into the collection that issued it -- the C++
/// spelling of Rust's `Ref<Ob>`. Default-constructed it is the
/// null sentinel (same as Rust `Ref::default()`).
struct ObRef {
    uint32_t raw = UINT32_MAX;
    bool valid() const { return raw != UINT32_MAX; }
};

namespace ffi {
struct Line;
struct Ob;

extern "C" {
double line_ob_x(const Ob*);
void line_ob_set_x(Ob*, double);
double line_ob_y(const Ob*);
void line_ob_set_y(Ob*, double);
int32_t line_assemble_covariance(Line*, uint32_t);
double line_k(const Line*);
void line_set_k(Line*, double);
bool line_k_optimize(const Line*);
void line_k_set_optimize(Line*, bool);
uint32_t line_obs_len(const Line*);
void line_obs_reserve(Line*, uint32_t);
Ob* line_obs_push(Line*);
Ob* line_obs_at(Line*, uint32_t);
bool line_obs_pop(Line*);
void line_obs_clear(Line*);
void line_obs_truncate(Line*, uint32_t);
double line_cost(Line*);
int32_t line_solve_band(Line*, uint32_t, const LmConfig*, LmResult*);
void line_lm_config(uint32_t, LmConfig*);
Line* line_new(void);
void line_free(Line*);
const char* line_last_error(const Line*);
const char* line_last_report(Line*, bool);
const char* line_validate(Line*);
int32_t line_solve_dense(Line*, const LmConfig*, LmResult*);
int32_t line_solve_sparse(Line*, const LmConfig*, LmResult*);
}
} // namespace ffi

inline LmConfig::LmConfig(LmPreset p) {
    ffi::line_lm_config(uint32_t(p), this);
}

/// A `Ob` in its owner's storage; a thin pointer wrapper (validity
/// follows the storage -- see the owning container).
class Ob {
public:
    /// Optimized parameters this entity contributes to the solve.
    static constexpr uint32_t param_count = 0;
    Ob() : h_(nullptr) {}
    explicit Ob(ffi::Ob* p) : h_(p) {}
    /// False when default-constructed (e.g. inside an empty option).
    bool valid() const { return h_ != nullptr; }
    /// The underlying C pointer -- the relaxed escape hatch.
    ffi::Ob* raw() const { return h_; }
    double x() const { return ffi::line_ob_x(h_); }
    void set_x(double v) { ffi::line_ob_set_x(h_, v); }
    double y() const { return ffi::line_ob_y(h_); }
    void set_y(double v) { ffi::line_ob_set_y(h_, v); }
private:
    ffi::Ob* h_;
};

/// Covariance prepared at the solution (root.assemble_covariance);
/// queries answer per-entity marginal blocks. Valid until the model
/// is dropped or reassembled.
class Covariance {
public:
    Covariance() : h_(nullptr) {}
    explicit Covariance(ffi::Line* h) : h_(h) {}
private:
    template<class T> result<T, CovError> fail() {
        return result<T, CovError>::err({ffi::line_last_error(h_)});
    }
    ffi::Line* h_;
};

/// `Line.obs`. std::vec::Vec storage: pushes may MOVE elements -- re-fetch element refs after a push.
class LineObsVec {
public:
    explicit LineObsVec(ffi::Line* h) : h_(h) {}
    uint32_t size() const { return ffi::line_obs_len(h_); }
    bool empty() const { return size() == 0; }
    void reserve(uint32_t additional) { ffi::line_obs_reserve(h_, additional); }
    /// Appends a default element and returns a wrapper for it.
    ///
    /// The wrapper holds a pointer INTO the collection, so it follows the
    /// std::vector rule: any later push may reallocate, and every wrapper
    /// taken before it -- including wrappers into collections nested inside
    /// these elements -- is then dangling. Either reserve() the count up
    /// front, or re-take the wrapper with operator[] after the growth.
    /// To hold on to an element across pushes, keep its Ref, not a wrapper.
    Ob push() { return Ob(ffi::line_obs_push(h_)); }
    /// Wrapper for element `i`; see push() on how long it stays valid.
    Ob operator[](uint32_t i) { return Ob(ffi::line_obs_at(h_, i)); }
    /// Front/back of a non-empty vec (empty = UB, like STL).
    Ob front() { return (*this)[0]; }
    Ob back() { return (*this)[size() - 1]; }
    /// Drops the last element; false when already empty.
    bool pop() { return ffi::line_obs_pop(h_); }
    void clear() { ffi::line_obs_clear(h_); }
    void truncate(uint32_t n) { ffi::line_obs_truncate(h_, n); }
    /// Bidirectional iterator. Standard C++ contract: modifying the
    /// container while iterating is undefined behavior. Dereference
    /// yields a value wrapper (Ob), like vector<bool> --
    /// reference is a value type.
    class iterator {
    public:
        using iterator_category = std::bidirectional_iterator_tag;
        using value_type = Ob;
        using difference_type = std::ptrdiff_t;
        using reference = Ob;
        struct arrow { Ob v; Ob* operator->() { return &v; } };
        using pointer = arrow;

        iterator() : h_(nullptr), i_(0) {}
        iterator(ffi::Line* h, uint32_t i) : h_(h), i_(i) {}
        Ob operator*() const { return Ob(ffi::line_obs_at(h_, i_)); }
        arrow operator->() const { return arrow{**this}; }
        iterator& operator++() { ++i_; return *this; }
        iterator& operator--() { --i_; return *this; }
        iterator operator++(int) { iterator t = *this; ++*this; return t; }
        iterator operator--(int) { iterator t = *this; --*this; return t; }
        bool operator==(const iterator& o) const { return i_ == o.i_; }
        bool operator!=(const iterator& o) const { return i_ != o.i_; }
    private:
        ffi::Line* h_;
        uint32_t i_;
    };
    iterator begin() { return iterator(h_, 0); }
    iterator end() { return iterator(h_, size()); }
    class reverse_iterator {
    public:
        using iterator_category = std::bidirectional_iterator_tag;
        using value_type = Ob;
        using difference_type = std::ptrdiff_t;
        using reference = Ob;
        using pointer = iterator::arrow;

        reverse_iterator() {}
        explicit reverse_iterator(iterator base) : base_(base) {}
        iterator base() const { return base_; }
        Ob operator*() const { iterator t = base_; --t; return *t; }
        pointer operator->() const { return pointer{**this}; }
        reverse_iterator& operator++() { --base_; return *this; }
        reverse_iterator& operator--() { ++base_; return *this; }
        reverse_iterator operator++(int) { reverse_iterator t = *this; ++*this; return t; }
        reverse_iterator operator--(int) { reverse_iterator t = *this; --*this; return t; }
        bool operator==(const reverse_iterator& o) const { return base_ == o.base_; }
        bool operator!=(const reverse_iterator& o) const { return base_ != o.base_; }
    private:
        iterator base_;
    };
    reverse_iterator rbegin() { return reverse_iterator(end()); }
    reverse_iterator rend() { return reverse_iterator(begin()); }
private:
    ffi::Line* h_;
};

/// The `Line` model. Owns the Rust-side object; move-only.
class Line {
public:
    Line() : h_(ffi::line_new()) {}
    ~Line() { if (h_) ffi::line_free(h_); }
    Line(const Line&) = delete;
    Line& operator=(const Line&) = delete;
    Line(Line&& o) noexcept : h_(o.h_) { o.h_ = nullptr; }
    Line& operator=(Line&& o) noexcept {
        if (this != &o) {
            if (h_) ffi::line_free(h_);
            h_ = o.h_;
            o.h_ = nullptr;
        }
        return *this;
    }

    double k() const { return ffi::line_k(h_); }
    void set_k(double v) { ffi::line_set_k(h_, v); }
    bool k_optimize() const { return ffi::line_k_optimize(h_); }
    void set_k_optimize(bool v) { ffi::line_k_set_optimize(h_, v); }
    LineObsVec obs() { return LineObsVec(h_); }

    /// Ok(LmResult) for every healthy termination, Err(SolveError) for
    /// a solve failure (-1) or a caught panic (-2) -- the same split
    /// Rust's SolveResult makes.
    SolveResult solve_dense(const LmConfig& cfg = LmConfig{}) {
        LmResult r;
        int32_t code = ffi::line_solve_dense(h_, &cfg, &r);
        if (code >= 0) return SolveResult::ok(r);
        return SolveResult::err({static_cast<LmStatus>(code), last_error()});
    }
    SolveResult solve_sparse(const LmConfig& cfg = LmConfig{}) {
        LmResult r;
        int32_t code = ffi::line_solve_sparse(h_, &cfg, &r);
        if (code >= 0) return SolveResult::ok(r);
        return SolveResult::err({static_cast<LmStatus>(code), last_error()});
    }
    /// Band Cholesky solve for banded Hessians; kd is the half-bandwidth
    /// in scalar parameters.
    SolveResult solve_band(uint32_t kd, const LmConfig& cfg = LmConfig{}) {
        LmResult r;
        int32_t code = ffi::line_solve_band(h_, kd, &cfg, &r);
        if (code >= 0) return SolveResult::ok(r);
        return SolveResult::err({static_cast<LmStatus>(code), last_error()});
    }
    /// Total cost at the current parameter values (f64 evaluation).
    double cost() { return ffi::line_cost(h_); }
    /// Prepare the covariance at the current (solved) parameters; query
    /// per-entity marginals on the returned view.
    result<Covariance, CovError> assemble_covariance(CovMode mode = CovMode::AllMarginals) {
        if (ffi::line_assemble_covariance(h_, uint32_t(mode)) != 0)
            return result<Covariance, CovError>::err({last_error()});
        return result<Covariance, CovError>::ok(Covariance(h_));
    }
    /// Empty string when the model is clean, the Diagnostic text
    /// otherwise. The returned pointer is valid until the next call on
    /// this model.
    const char* validate() { return ffi::line_validate(h_); }
    const char* last_error() const { return ffi::line_last_error(h_); }
    /// Text report of the last completed solve (status, cost,
    /// iterations, timing and the backend's plan when gathered); ""
    /// before the first solve. Valid until the next report call.
    const char* last_report() { return ffi::line_last_report(h_, false); }
    /// last_report() with colour and box-drawing glyphs.
    const char* last_pretty_report() { return ffi::line_last_report(h_, true); }

private:
    ffi::Line* h_;
};

} // namespace cxx_mr::line
