# GENERATED by cargo-arael (vendored python support). Do not edit.
# arael Python solver surface, shared by every generated module:
# status/preset/covariance enums, the per-precision config, result and
# iteration layouts (ctypes mirrors of the C ABI -- field order
# matters), and AraelError. A generated module instantiates the
# layouts at its root's precision via lm_types() and wires the config
# constructor to its root's FFI.

import ctypes
import enum


class AraelError(Exception):
    """A failed solve (status < 0), a caught Rust panic (status -2),
    or a failed covariance query; carries the status code, the
    last_error text, and -- for a solve that got past its first
    assembly -- the partial LmResult. After a caught panic the
    model's parameters are unchanged and a session in use was
    invalidated; validate() reports the underlying mistake as
    text."""

    def __init__(self, status, message, partial=None):
        super().__init__("%s (status %d)" % (message, status))
        self.status = int(status)
        self.message = message
        self.partial = partial


class LmStatus(enum.IntEnum):
    """Why a solve stopped (matches the Rust LmStatus mapping)."""
    CONVERGED = 0
    COST_THRESHOLD = 1
    MAX_ITERATIONS = 2
    GRADIENT_TOLERANCE = 3
    PARAMETER_TOLERANCE = 4
    PREDICTED_REDUCTION = 5
    LAMBDA_CEILING = 6
    DRIVER_TERMINATED = 7
    OBSERVER_TERMINATED = 8
    TIME_LIMIT = 9
    RETRY_BUDGET_EXHAUSTED = 10
    ABORTED = 11
    SOLVER_FAILED = -1
    PANICKED = -2

    def is_success(self):
        """Did the solve reach a minimum, as opposed to running out
        of something? (Rust's LmStatus::is_success.)"""
        return self in (LmStatus.CONVERGED, LmStatus.COST_THRESHOLD,
                        LmStatus.GRADIENT_TOLERANCE,
                        LmStatus.PARAMETER_TOLERANCE,
                        LmStatus.PREDICTED_REDUCTION,
                        LmStatus.DRIVER_TERMINATED,
                        LmStatus.OBSERVER_TERMINATED)

    def as_str(self):
        """Rust's LmStatus::as_str (plus the two skin-only codes)."""
        return _STATUS_STR[self]


_STATUS_STR = {
    LmStatus.CONVERGED: "converged",
    LmStatus.COST_THRESHOLD: "cost threshold reached",
    LmStatus.MAX_ITERATIONS: "hit max_iters",
    LmStatus.GRADIENT_TOLERANCE: "gradient flat",
    LmStatus.PARAMETER_TOLERANCE: "step negligible",
    LmStatus.PREDICTED_REDUCTION: "predicted gain negligible",
    LmStatus.LAMBDA_CEILING: "damping exhausted",
    LmStatus.DRIVER_TERMINATED: "driver stopped it",
    LmStatus.OBSERVER_TERMINATED: "observer stopped it",
    LmStatus.TIME_LIMIT: "out of time",
    LmStatus.RETRY_BUDGET_EXHAUSTED: "retry budget exhausted",
    LmStatus.ABORTED: "aborted",
    LmStatus.SOLVER_FAILED: "solver failed",
    LmStatus.PANICKED: "panicked",
}


class LmPreset(enum.IntEnum):
    """The base preset a config starts from; it also supplies the one
    Rust field the struct does not expose, the lambda driver.
    ILL_CONDITIONED selects the Nielsen driver (its other fields match
    CONSERVATIVE); DEFAULTS and CONSERVATIVE are the same config."""
    DEFAULTS = 0
    CONSERVATIVE = 1
    WELL_CONDITIONED = 2
    ILL_CONDITIONED = 3


class CovMode(enum.IntEnum):
    PER_QUERY = 0
    ALL_MARGINALS = 1
    TRI_DIAGONAL = 2


class LogLevel(enum.IntEnum):
    """Severity threshold for arael's diagnostics (matches the Rust
    log::Level): a level admits everything at or below itself."""
    OFF = 0
    ERROR = 1
    WARN = 2
    INFO = 3


class ReducedOrdering(enum.IntEnum):
    """How the reduced system was ordered (matches the Rust enum)."""
    NATURAL_BANDED = 0
    NATURAL_DENSE = 1
    AMD = 2
    ND = 3


class SchurPolicy(enum.IntEnum):
    """Whether and when the sparse backend marginalizes (matches the
    Rust enum). AUTO prices the reduction; its tuning lives on
    SparseOptions."""
    AUTO = 0
    FORCE = 1
    NEVER = 2


class FaerOrdering(enum.IntEnum):
    """Elimination ordering of the factorized system (matches the
    Rust enum)."""
    AUTO = 0
    AMD = 1
    MARGINALIZE_FIRST = 2
    NATURAL = 3
    NESTED_DISSECTION = 4


class SchurSolve(enum.IntEnum):
    """How the reduced Schur system is solved (matches the Rust
    enum): factorized, or by preconditioned conjugate gradients
    (ITERATIVE forms the reduced matrix, ITERATIVE_IMPLICIT never
    does). Pair the iterative routes with SchurPolicy.FORCE --
    without a reduction the solve fails rather than taking another
    route."""
    FACTORIZE = 0
    ITERATIVE = 1
    ITERATIVE_IMPLICIT = 2


class EnvelopeMode(enum.IntEnum):
    """How the reduced Schur system is factored (matches the Rust
    enum): in block form under its envelope, or by the general sparse
    Cholesky. The envelope route uses less memory on suitable systems;
    AUTO prices it per problem."""
    AUTO = 0
    ALWAYS = 1
    NEVER = 2


def _enum_property(field, enum_cls):
    """Property mapping a raw u32 field to an enum. The setter
    validates: a value outside the enum raises ValueError."""

    def get(self):
        return enum_cls(getattr(self, field))

    def set(self, value):
        setattr(self, field, int(enum_cls(value)))

    return property(get, set)


class SparseOptions(ctypes.Structure):
    """The sparse backend's options (mirror of arael's
    SparseFaerOptions): whether and when to marginalize, the
    elimination ordering, and the envelope route for the reduced
    system. The generated module's subclass fills the actual Rust
    defaults at construction; edit fields and pass to solve_sparse.
    Not exposed: the marginalize range list (the model's own hint
    covers it) and the iterative Schur routes."""
    _fields_ = [
        ("_schur", ctypes.c_uint32),
        ("_ordering", ctypes.c_uint32),
        ("_envelope", ctypes.c_uint32),
        # 0 picks the envelope panel width automatically.
        ("envelope_panel_width", ctypes.c_uint32),
        ("supernodal", ctypes.c_bool),
        ("narrow_band", ctypes.c_bool),
        # SchurPolicy.AUTO tuning: the reduction must beat the whole
        # system by flop_margin to be taken, and below
        # obvious_flop_ratio it is taken without the exact pricing.
        ("flop_margin", ctypes.c_double),
        ("obvious_flop_ratio", ctypes.c_double),
        # Conjugate-gradient settings for the iterative routes:
        # tolerance, iteration cap (0 = unlimited), restart interval
        # (0 = never).
        ("cg_tol", ctypes.c_double),
        ("_schur_solve", ctypes.c_uint32),
        ("cg_max_iters", ctypes.c_uint32),
        ("cg_restart_every", ctypes.c_uint32),
    ]

    schur = _enum_property("_schur", SchurPolicy)
    ordering = _enum_property("_ordering", FaerOrdering)
    envelope = _enum_property("_envelope", EnvelopeMode)
    schur_solve = _enum_property("_schur_solve", SchurSolve)


class _OptDouble(ctypes.Structure):
    _fields_ = [("has", ctypes.c_bool), ("v", ctypes.c_double)]


class _OptU32(ctypes.Structure):
    _fields_ = [("has", ctypes.c_bool), ("v", ctypes.c_uint32)]


class _OptI32(ctypes.Structure):
    _fields_ = [("has", ctypes.c_bool), ("v", ctypes.c_int32)]


class _RouteFlops(ctypes.Structure):
    _fields_ = [("reduced", ctypes.c_double), ("full", ctypes.c_double)]


class _OptRouteFlops(ctypes.Structure):
    _fields_ = [("has", ctypes.c_bool), ("v", _RouteFlops)]


def _plan_opt(field, shape):
    """Read-only property mapping an {has, v} field to a value or None."""

    def get(self):
        c = getattr(self, field)
        return shape(c.v) if c.has else None

    return property(get)


class SchurPlan(ctypes.Structure):
    """What the sparse backend decided (mirror of the Rust SchurPlan):
    whether the Schur reduction ran, what it eliminated, how the
    factored system was ordered, and the evidence behind the Auto
    decisions. `envelope` says the system was factored in block form
    under its envelope; optional statistics read as None when absent."""
    _fields_ = [
        ("reduced", ctypes.c_bool),
        ("eliminated_blocks", ctypes.c_uint32),
        ("eliminated_params", ctypes.c_uint32),
        ("kept_params", ctypes.c_uint32),
        ("_fill_ratio", _OptDouble),
        ("_route_flops", _OptRouteFlops),
        ("_cg_iterations", _OptU32),
        ("_flop_ratio", _OptDouble),
        ("_ordering", _OptI32),
        ("kept_bandwidth", ctypes.c_uint32),
        ("envelope", ctypes.c_bool),
    ]

    fill_ratio = _plan_opt("_fill_ratio", float)
    route_flops = _plan_opt("_route_flops", lambda v: (v.reduced, v.full))
    cg_iterations = _plan_opt("_cg_iterations", int)
    flop_ratio = _plan_opt("_flop_ratio", float)
    ordering = _plan_opt("_ordering", ReducedOrdering)


class LmTiming(ctypes.Structure):
    """Per-phase wall-clock seconds plus call counts, gathered when
    config.gather_timing is set."""
    _fields_ = [
        ("total", ctypes.c_double),
        ("assembly", ctypes.c_double),
        ("first_assembly", ctypes.c_double),
        ("analysis", ctypes.c_double),
        ("linear_solve", ctypes.c_double),
        ("first_linear_solve", ctypes.c_double),
        ("cost_eval", ctypes.c_double),
        ("first_cost_eval", ctypes.c_double),
        ("advance", ctypes.c_double),
        ("first_advance", ctypes.c_double),
        ("assembly_count", ctypes.c_uint32),
        ("analysis_count", ctypes.c_uint32),
        ("linear_solve_count", ctypes.c_uint32),
        ("cost_eval_count", ctypes.c_uint32),
        ("advance_count", ctypes.c_uint32),
    ]


class LmStep(ctypes.Structure):
    """One attempted LM step: the per-attempt timeline behind
    LmResult.steps. A damping retry is its own record, so rejected
    steps and failed factorizations appear too. Durations are
    wall-clock seconds; assembly is charged to the first attempt at
    each linearization (inner == 0), zero on a retry."""
    _fields_ = [
        ("iter", ctypes.c_uint32),
        ("inner", ctypes.c_uint32),
        ("accepted", ctypes.c_bool),
        ("factorization_failed", ctypes.c_bool),
        ("lambda_", ctypes.c_double),
        ("cost", ctypes.c_double),
        ("new_cost", ctypes.c_double),
        ("step_norm", ctypes.c_double),
        ("grad_max", ctypes.c_double),
        ("time", ctypes.c_double),
        ("assembly", ctypes.c_double),
        ("analysis", ctypes.c_double),
        ("linear_solve", ctypes.c_double),
        ("cost_eval", ctypes.c_double),
        ("advance", ctypes.c_double),
    ]


def _opt_property(field):
    """Property mapping a COpt struct field to a float-or-None."""

    def get(self):
        c = getattr(self, field)
        return float(c.v) if c.has else None

    def set(self, value):
        c = getattr(self, field)
        if value is None:
            c.has = False
            c.v = 0.0
        else:
            c.has = True
            c.v = float(value)

    return property(get, set)


def lm_types(fp):
    """The per-precision solver layouts as a dict: fp is
    ctypes.c_float or ctypes.c_double. Field order is the C ABI."""

    class COptF(ctypes.Structure):
        _fields_ = [("has", ctypes.c_bool), ("v", fp)]

    class COptSeconds(ctypes.Structure):
        _fields_ = [("has", ctypes.c_bool), ("v", ctypes.c_double)]

    class LmIter(ctypes.Structure):
        """One damped attempt, as the observer callback sees it.
        `params`/`params_len` point at the CURRENT parameter vector;
        valid only during the callback."""
        _fields_ = [
            ("iter", ctypes.c_uint32),
            ("inner", ctypes.c_uint32),
            ("accepted", ctypes.c_bool),
            ("factorization_failed", ctypes.c_bool),
            ("cost", fp),
            ("new_cost", fp),
            ("lambda_", fp),
            ("accepted_total", ctypes.c_uint32),
            ("params", ctypes.POINTER(fp)),
            ("params_len", ctypes.c_uint32),
        ]

        def param(self, i):
            return float(self.params[i])

        def param_list(self):
            return [float(self.params[i]) for i in range(self.params_len)]

    observer_fn = ctypes.CFUNCTYPE(ctypes.c_bool, ctypes.c_void_p,
                                   ctypes.POINTER(LmIter))

    class LmConfig(ctypes.Structure):
        """The solver configuration, holding the preset's Rust values
        (the generated module's constructors fetch them through the
        FFI). Optional fields read/assign as float-or-None; assign a
        Python callable to `observer` (it receives an LmIter; return
        False to stop the solve)."""
        _fields_ = [
            ("preset", ctypes.c_uint32),
            ("max_iters", ctypes.c_uint32),
            ("min_iters", ctypes.c_uint32),
            ("patience", ctypes.c_uint32),
            ("num_threads", ctypes.c_uint32),
            ("verbose", ctypes.c_bool),
            ("gather_timing", ctypes.c_bool),
            ("abs_precision", fp),
            ("rel_precision", fp),
            ("initial_lambda", fp),
            ("cost_threshold", fp),
            ("lambda_floor", fp),
            ("_gradient_tolerance", COptF),
            ("_parameter_tolerance", COptF),
            ("_predicted_reduction_tolerance", COptF),
            ("_min_diagonal", COptF),
            ("_time_limit_seconds", COptSeconds),
            ("_observer", observer_fn),
            ("_observer_user", ctypes.c_void_p),
        ]

        gradient_tolerance = _opt_property("_gradient_tolerance")
        parameter_tolerance = _opt_property("_parameter_tolerance")
        predicted_reduction_tolerance = \
            _opt_property("_predicted_reduction_tolerance")
        min_diagonal = _opt_property("_min_diagonal")
        time_limit_seconds = _opt_property("_time_limit_seconds")

        @property
        def observer(self):
            return getattr(self, "_observer_py", None)

        @observer.setter
        def observer(self, fn):
            # The CFUNCTYPE object must outlive the config (the
            # classic ctypes GC trap) -- kept as an attribute.
            if fn is None:
                self._observer_py = None
                self._observer_keep = None
                self._observer = observer_fn()
                return

            def trampoline(_user, it):
                r = fn(it.contents)
                return r is None or bool(r)

            self._observer_py = fn
            self._observer_keep = observer_fn(trampoline)
            self._observer = self._observer_keep

    class LmResult(ctypes.Structure):
        """A completed solve: costs, iterations, status, damping, and
        (when gathered) the timing breakdown. `_detail` owns the full
        Rust-side result; the generated module's LmResult subclass
        renders reports and the backend plan from it and frees it on
        garbage collection."""
        _fields_ = [
            ("start_cost", fp),
            ("end_cost", fp),
            ("iterations", ctypes.c_uint32),
            ("accepted_iterations", ctypes.c_uint32),
            ("_status", ctypes.c_int32),
            ("final_lambda", fp),
            ("_timing", LmTiming),
            ("has_timing", ctypes.c_bool),
            ("_detail", ctypes.c_void_p),
        ]

        @property
        def status(self):
            return LmStatus(self._status)

        @property
        def timing(self):
            return self._timing if self.has_timing else None

    return {
        "COptF": COptF,
        "COptSeconds": COptSeconds,
        "LmIter": LmIter,
        "LmConfig": LmConfig,
        "LmResult": LmResult,
        "observer_fn": observer_fn,
    }
