// GENERATED by cargo-arael from the `Fit` model sidecar. Do not
// edit; regenerate with `cargo arael export`.
#pragma once

#include <cstdint>
#include <cmath>
#include "arael/math.hpp"
#include "arael/result.hpp"
#include "arael/solver.hpp"

namespace cxx_fit {

/// The arael value vocabulary this interface uses, re-exported so a
/// single `using namespace cxx_fit;` brings the model AND the math.
using arael::vect2;
using arael::vect3;
using arael::matrix2;
using arael::matrix3;
using arael::quatern;
using arael::vect2f;
using arael::vect2d;
using arael::vect3f;
using arael::vect3d;
using arael::matrix2f;
using arael::matrix2d;
using arael::matrix3f;
using arael::matrix3d;
using arael::quaternf;
using arael::quaternd;
using arael::option;
using arael::result;
using arael::LmStatus;
using arael::LmPreset;
using arael::LmConfigT;
using arael::LmResultT;
using arael::SolveResultT;
using arael::SolveError;
using arael::CovMode;
using arael::CovError;

/// Instantiations of the shared solver surface (arael/solver.hpp) at
/// this model's precision, plus the config constructor that fetches
/// the preset's actual Rust values through this root's FFI.
using LmResult = LmResultT<double>;
using SolveResult = SolveResultT<double>;

struct LmConfig : LmConfigT<double> {
    LmConfig(LmPreset p = LmPreset::Defaults);
    static LmConfig defaults() { return LmConfig(LmPreset::Defaults); }
    static LmConfig conservative() { return LmConfig(LmPreset::Conservative); }
    static LmConfig well_conditioned() { return LmConfig(LmPreset::WellConditioned); }
};

/// Typed handle into the collection that issued it -- the C++
/// spelling of Rust's `Ref<GpsObs>`.
struct GpsObsRef { uint32_t raw; };
/// Typed handle into the collection that issued it -- the C++
/// spelling of Rust's `Ref<Info>`.
struct InfoRef { uint32_t raw; };
/// Typed handle into the collection that issued it -- the C++
/// spelling of Rust's `Ref<N>`.
struct NRef { uint32_t raw; };
/// Typed handle into the collection that issued it -- the C++
/// spelling of Rust's `Ref<Obs>`.
struct ObsRef { uint32_t raw; };
/// Typed handle into the collection that issued it -- the C++
/// spelling of Rust's `Ref<Pose>`.
struct PoseRef { uint32_t raw; };
/// Typed handle into the collection that issued it -- the C++
/// spelling of Rust's `Ref<Tie>`.
struct TieRef { uint32_t raw; };

namespace ffi {
struct Fit;
struct GpsObs;
struct Info;
struct N;
struct Obs;
struct Pose;
struct Tie;

extern "C" {
vect3d fit_gps_obs_pos(const GpsObs*);
void fit_gps_obs_set_pos(GpsObs*, vect3d);
float fit_gps_obs_isigma(const GpsObs*);
void fit_gps_obs_set_isigma(GpsObs*, float);
bool fit_info_has_gps(const Info*);
GpsObs* fit_info_make_gps(Info*);
void fit_info_clear_gps(Info*);
GpsObs* fit_info_gps(Info*);
double fit_n_v(const N*);
void fit_n_set_v(N*, double);
bool fit_n_v_optimize(const N*);
void fit_n_v_set_optimize(N*, bool);
double fit_n_t(const N*);
void fit_n_set_t(N*, double);
double fit_n_w(const N*);
void fit_n_set_w(N*, double);
double fit_obs_x(const Obs*);
void fit_obs_set_x(Obs*, double);
double fit_obs_y(const Obs*);
void fit_obs_set_y(Obs*, double);
vect3d fit_pose_ea(const Pose*);
void fit_pose_set_ea(Pose*, vect3d);
bool fit_pose_ea_optimize(const Pose*);
void fit_pose_ea_set_optimize(Pose*, bool);
vect3d fit_pose_pos(const Pose*);
void fit_pose_set_pos(Pose*, vect3d);
bool fit_pose_pos_optimize(const Pose*);
void fit_pose_pos_set_optimize(Pose*, bool);
vect3d fit_pose_target(const Pose*);
void fit_pose_set_target(Pose*, vect3d);
Info* fit_pose_info_ptr(Pose*);
uint32_t fit_tie_a(const Tie*);
void fit_tie_set_a(Tie*, uint32_t);
uint32_t fit_tie_b(const Tie*);
void fit_tie_set_b(Tie*, uint32_t);
vect3d fit_tie_d(const Tie*);
void fit_tie_set_d(Tie*, vect3d);
double fit_tie_w(const Tie*);
void fit_tie_set_w(Tie*, double);
int32_t fit_assemble_covariance(Fit*, uint32_t);
int32_t fit_n_marginal_cov(Fit*, const N*, double*, uint32_t);
int32_t fit_pose_marginal_cov(Fit*, const Pose*, double*, uint32_t);
double fit_m(const Fit*);
void fit_set_m(Fit*, double);
bool fit_m_optimize(const Fit*);
void fit_m_set_optimize(Fit*, bool);
double fit_c(const Fit*);
void fit_set_c(Fit*, double);
bool fit_c_optimize(const Fit*);
void fit_c_set_optimize(Fit*, bool);
vect2d fit_cal(const Fit*);
void fit_set_cal(Fit*, vect2d);
uint32_t fit_obs_len(const Fit*);
Obs* fit_obs_push(Fit*);
Obs* fit_obs_at(Fit*, uint32_t);
uint32_t fit_items_len(const Fit*);
N* fit_items_push(Fit*);
N* fit_items_at(Fit*, uint32_t);
uint32_t fit_items_ref_at(const Fit*, uint32_t);
N* fit_items_get(Fit*, uint32_t);
uint32_t fit_poses_len(const Fit*);
Pose* fit_poses_push_back(Fit*);
Pose* fit_poses_push_front(Fit*);
Pose* fit_poses_at(Fit*, uint32_t);
uint32_t fit_poses_ref_at(const Fit*, uint32_t);
Pose* fit_poses_get(Fit*, uint32_t);
uint32_t fit_ties_len(const Fit*);
Tie* fit_ties_push(Fit*);
Tie* fit_ties_at(Fit*, uint32_t);
uint32_t fit_marks_len(const Fit*);
uint32_t fit_marks_push(Fit*);
bool fit_marks_remove(Fit*, uint32_t);
N* fit_marks_get(Fit*, uint32_t);
void fit_lm_config(uint32_t, LmConfig*);
Fit* fit_new(void);
void fit_free(Fit*);
const char* fit_last_error(const Fit*);
const char* fit_validate(Fit*);
int32_t fit_solve_dense(Fit*, const LmConfig*, LmResult*);
int32_t fit_solve_sparse(Fit*, const LmConfig*, LmResult*);
}
} // namespace ffi

inline LmConfig::LmConfig(LmPreset p) {
    ffi::fit_lm_config(uint32_t(p), this);
}

/// A `GpsObs` in its owner's storage; a thin pointer wrapper (validity
/// follows the storage -- see the owning container).
class GpsObs {
public:
    GpsObs() : h_(nullptr) {}
    explicit GpsObs(ffi::GpsObs* p) : h_(p) {}
    /// False when default-constructed (e.g. inside an empty option).
    bool valid() const { return h_ != nullptr; }
    /// The underlying C pointer -- the relaxed escape hatch.
    ffi::GpsObs* raw() const { return h_; }
    vect3d pos() const { return ffi::fit_gps_obs_pos(h_); }
    void set_pos(vect3d v) { ffi::fit_gps_obs_set_pos(h_, v); }
    float isigma() const { return ffi::fit_gps_obs_isigma(h_); }
    void set_isigma(float v) { ffi::fit_gps_obs_set_isigma(h_, v); }
private:
    ffi::GpsObs* h_;
};

/// A `Info` in its owner's storage; a thin pointer wrapper (validity
/// follows the storage -- see the owning container).
class Info {
public:
    Info() : h_(nullptr) {}
    explicit Info(ffi::Info* p) : h_(p) {}
    /// False when default-constructed (e.g. inside an empty option).
    bool valid() const { return h_ != nullptr; }
    /// The underlying C pointer -- the relaxed escape hatch.
    ffi::Info* raw() const { return h_; }
    bool has_gps() const { return ffi::fit_info_has_gps(h_); }
    GpsObs make_gps() { return GpsObs(ffi::fit_info_make_gps(h_)); }
    void clear_gps() { ffi::fit_info_clear_gps(h_); }
    option<GpsObs> gps() {
        ffi::GpsObs* p = ffi::fit_info_gps(h_);
        return p ? option<GpsObs>(GpsObs(p)) : option<GpsObs>();
    }
    // field `note`: String -- opaque, no accessor generated
private:
    ffi::Info* h_;
};

/// A `N` in its owner's storage; a thin pointer wrapper (validity
/// follows the storage -- see the owning container).
class N {
public:
    N() : h_(nullptr) {}
    explicit N(ffi::N* p) : h_(p) {}
    /// False when default-constructed (e.g. inside an empty option).
    bool valid() const { return h_ != nullptr; }
    /// The underlying C pointer -- the relaxed escape hatch.
    ffi::N* raw() const { return h_; }
    double v() const { return ffi::fit_n_v(h_); }
    void set_v(double v) { ffi::fit_n_set_v(h_, v); }
    bool v_optimize() const { return ffi::fit_n_v_optimize(h_); }
    void set_v_optimize(bool v) { ffi::fit_n_v_set_optimize(h_, v); }
    double t() const { return ffi::fit_n_t(h_); }
    void set_t(double v) { ffi::fit_n_set_t(h_, v); }
    double w() const { return ffi::fit_n_w(h_); }
    void set_w(double v) { ffi::fit_n_set_w(h_, v); }
private:
    ffi::N* h_;
};

/// A `Obs` in its owner's storage; a thin pointer wrapper (validity
/// follows the storage -- see the owning container).
class Obs {
public:
    Obs() : h_(nullptr) {}
    explicit Obs(ffi::Obs* p) : h_(p) {}
    /// False when default-constructed (e.g. inside an empty option).
    bool valid() const { return h_ != nullptr; }
    /// The underlying C pointer -- the relaxed escape hatch.
    ffi::Obs* raw() const { return h_; }
    double x() const { return ffi::fit_obs_x(h_); }
    void set_x(double v) { ffi::fit_obs_set_x(h_, v); }
    double y() const { return ffi::fit_obs_y(h_); }
    void set_y(double v) { ffi::fit_obs_set_y(h_, v); }
private:
    ffi::Obs* h_;
};

/// A `Pose` in its owner's storage; a thin pointer wrapper (validity
/// follows the storage -- see the owning container).
class Pose {
public:
    Pose() : h_(nullptr) {}
    explicit Pose(ffi::Pose* p) : h_(p) {}
    /// False when default-constructed (e.g. inside an empty option).
    bool valid() const { return h_ != nullptr; }
    /// The underlying C pointer -- the relaxed escape hatch.
    ffi::Pose* raw() const { return h_; }
    vect3d ea() const { return ffi::fit_pose_ea(h_); }
    void set_ea(vect3d v) { ffi::fit_pose_set_ea(h_, v); }
    bool ea_optimize() const { return ffi::fit_pose_ea_optimize(h_); }
    void set_ea_optimize(bool v) { ffi::fit_pose_ea_set_optimize(h_, v); }
    vect3d pos() const { return ffi::fit_pose_pos(h_); }
    void set_pos(vect3d v) { ffi::fit_pose_set_pos(h_, v); }
    bool pos_optimize() const { return ffi::fit_pose_pos_optimize(h_); }
    void set_pos_optimize(bool v) { ffi::fit_pose_pos_set_optimize(h_, v); }
    vect3d target() const { return ffi::fit_pose_target(h_); }
    void set_target(vect3d v) { ffi::fit_pose_set_target(h_, v); }
    Info info() { return Info(ffi::fit_pose_info_ptr(h_)); }
private:
    ffi::Pose* h_;
};

/// A `Tie` in its owner's storage; a thin pointer wrapper (validity
/// follows the storage -- see the owning container).
class Tie {
public:
    Tie() : h_(nullptr) {}
    explicit Tie(ffi::Tie* p) : h_(p) {}
    /// False when default-constructed (e.g. inside an empty option).
    bool valid() const { return h_ != nullptr; }
    /// The underlying C pointer -- the relaxed escape hatch.
    ffi::Tie* raw() const { return h_; }
    PoseRef a() const { return PoseRef{ffi::fit_tie_a(h_)}; }
    void set_a(PoseRef r) { ffi::fit_tie_set_a(h_, r.raw); }
    PoseRef b() const { return PoseRef{ffi::fit_tie_b(h_)}; }
    void set_b(PoseRef r) { ffi::fit_tie_set_b(h_, r.raw); }
    vect3d d() const { return ffi::fit_tie_d(h_); }
    void set_d(vect3d v) { ffi::fit_tie_set_d(h_, v); }
    double w() const { return ffi::fit_tie_w(h_); }
    void set_w(double v) { ffi::fit_tie_set_w(h_, v); }
private:
    ffi::Tie* h_;
};

/// Covariance prepared at the solution (root.assemble_covariance);
/// queries answer per-entity marginal blocks. Valid until the model
/// is dropped or reassembled.
class Covariance {
public:
    Covariance() : h_(nullptr) {}
    explicit Covariance(ffi::Fit* h) : h_(h) {}
    result<double, CovError> marginal(const N& e) {
        double b[1];
        if (ffi::fit_n_marginal_cov(h_, e.raw(), b, 1) < 0) return fail<double>();
        return result<double, CovError>::ok(b[0]);
    }
    /// Row-major dim x dim into out; returns dim or a negative code.
    int32_t marginal(const Pose& e, double* out, uint32_t cap) {
        return ffi::fit_pose_marginal_cov(h_, e.raw(), out, cap);
    }
private:
    template<class T> result<T, CovError> fail() {
        return result<T, CovError>::err({ffi::fit_last_error(h_)});
    }
    ffi::Fit* h_;
};

/// `Fit.obs`. std::vec::Vec storage: pushes may MOVE elements -- re-fetch element refs after a push.
class FitObsVec {
public:
    explicit FitObsVec(ffi::Fit* h) : h_(h) {}
    uint32_t size() const { return ffi::fit_obs_len(h_); }
    Obs push() { return Obs(ffi::fit_obs_push(h_)); }
    Obs operator[](uint32_t i) { return Obs(ffi::fit_obs_at(h_, i)); }
private:
    ffi::Fit* h_;
};

/// `Fit.items`. Element pointers are STABLE across pushes (chunked storage).
class FitItemsVec {
public:
    explicit FitItemsVec(ffi::Fit* h) : h_(h) {}
    uint32_t size() const { return ffi::fit_items_len(h_); }
    N push() { return N(ffi::fit_items_push(h_)); }
    N operator[](uint32_t i) { return N(ffi::fit_items_at(h_, i)); }
    NRef ref_at(uint32_t i) const { return NRef{ffi::fit_items_ref_at(h_, i)}; }
    N get(NRef r) { return N(ffi::fit_items_get(h_, r.raw)); }
private:
    ffi::Fit* h_;
};

/// `Fit.poses`. Element pointers are STABLE across pushes (chunked storage).
class FitPosesDeque {
public:
    explicit FitPosesDeque(ffi::Fit* h) : h_(h) {}
    uint32_t size() const { return ffi::fit_poses_len(h_); }
    Pose push_back() { return Pose(ffi::fit_poses_push_back(h_)); }
    Pose push_front() { return Pose(ffi::fit_poses_push_front(h_)); }
    Pose operator[](uint32_t i) { return Pose(ffi::fit_poses_at(h_, i)); }
    PoseRef ref_at(uint32_t i) const { return PoseRef{ffi::fit_poses_ref_at(h_, i)}; }
    Pose get(PoseRef r) { return Pose(ffi::fit_poses_get(h_, r.raw)); }
private:
    ffi::Fit* h_;
};

/// `Fit.ties`. std::vec::Vec storage: pushes may MOVE elements -- re-fetch element refs after a push.
class FitTiesVec {
public:
    explicit FitTiesVec(ffi::Fit* h) : h_(h) {}
    uint32_t size() const { return ffi::fit_ties_len(h_); }
    Tie push() { return Tie(ffi::fit_ties_push(h_)); }
    Tie operator[](uint32_t i) { return Tie(ffi::fit_ties_at(h_, i)); }
private:
    ffi::Fit* h_;
};

/// `Fit.marks`. Element pointers are STABLE across pushes (chunked storage).
class FitMarksArena {
public:
    explicit FitMarksArena(ffi::Fit* h) : h_(h) {}
    uint32_t size() const { return ffi::fit_marks_len(h_); }
    NRef push() { return NRef{ffi::fit_marks_push(h_)}; }
    bool remove(NRef r) { return ffi::fit_marks_remove(h_, r.raw); }
    N get(NRef r) { return N(ffi::fit_marks_get(h_, r.raw)); }
private:
    ffi::Fit* h_;
};

/// The `Fit` model. Owns the Rust-side object; move-only.
class Fit {
public:
    Fit() : h_(ffi::fit_new()) {}
    ~Fit() { if (h_) ffi::fit_free(h_); }
    Fit(const Fit&) = delete;
    Fit& operator=(const Fit&) = delete;
    Fit(Fit&& o) noexcept : h_(o.h_) { o.h_ = nullptr; }
    Fit& operator=(Fit&& o) noexcept {
        if (this != &o) {
            if (h_) ffi::fit_free(h_);
            h_ = o.h_;
            o.h_ = nullptr;
        }
        return *this;
    }

    double m() const { return ffi::fit_m(h_); }
    void set_m(double v) { ffi::fit_set_m(h_, v); }
    bool m_optimize() const { return ffi::fit_m_optimize(h_); }
    void set_m_optimize(bool v) { ffi::fit_m_set_optimize(h_, v); }
    double c() const { return ffi::fit_c(h_); }
    void set_c(double v) { ffi::fit_set_c(h_, v); }
    bool c_optimize() const { return ffi::fit_c_optimize(h_); }
    void set_c_optimize(bool v) { ffi::fit_c_set_optimize(h_, v); }
    vect2d cal() const { return ffi::fit_cal(h_); }
    void set_cal(vect2d v) { ffi::fit_set_cal(h_, v); }
    // field `tag`: String -- opaque, no accessor generated
    FitObsVec obs() { return FitObsVec(h_); }
    FitItemsVec items() { return FitItemsVec(h_); }
    FitPosesDeque poses() { return FitPosesDeque(h_); }
    FitTiesVec ties() { return FitTiesVec(h_); }
    FitMarksArena marks() { return FitMarksArena(h_); }

    /// Ok(LmResult) for every healthy termination, Err(SolveError) for
    /// a solve failure (-1) or a caught panic (-2) -- the same split
    /// Rust's SolveResult makes.
    SolveResult solve_dense(const LmConfig& cfg = LmConfig{}) {
        LmResult r;
        int32_t code = ffi::fit_solve_dense(h_, &cfg, &r);
        if (code >= 0) return SolveResult::ok(r);
        return SolveResult::err({static_cast<LmStatus>(code), last_error()});
    }
    SolveResult solve_sparse(const LmConfig& cfg = LmConfig{}) {
        LmResult r;
        int32_t code = ffi::fit_solve_sparse(h_, &cfg, &r);
        if (code >= 0) return SolveResult::ok(r);
        return SolveResult::err({static_cast<LmStatus>(code), last_error()});
    }
    /// Prepare the covariance at the current (solved) parameters; query
    /// per-entity marginals on the returned view.
    result<Covariance, CovError> assemble_covariance(CovMode mode = CovMode::AllMarginals) {
        if (ffi::fit_assemble_covariance(h_, uint32_t(mode)) != 0)
            return result<Covariance, CovError>::err({last_error()});
        return result<Covariance, CovError>::ok(Covariance(h_));
    }
    /// Empty string when the model is clean, the Diagnostic text
    /// otherwise. The returned pointer is valid until the next call on
    /// this model.
    const char* validate() { return ffi::fit_validate(h_); }
    const char* last_error() const { return ffi::fit_last_error(h_); }

private:
    ffi::Fit* h_;
};

} // namespace cxx_fit
