// GENERATED by cargo-arael from the `Fit` model sidecar. Do not
// edit; regenerate with `cargo arael export`.
#pragma once

#include <cstdint>
#include <cmath>

namespace arael {

/// Why a solve stopped. Non-negative codes come from the solver;
/// SolverFailed carries text via last_error(), Panicked likewise.
enum class LmStatus : int32_t {
    Converged = 0,
    CostThreshold = 1,
    MaxIterations = 2,
    GradientTolerance = 3,
    ParameterTolerance = 4,
    PredictedReduction = 5,
    LambdaCeiling = 6,
    DriverTerminated = 7,
    ObserverTerminated = 8,
    TimeLimit = 9,
    RetryBudgetExhausted = 10,
    Aborted = 11,
    SolverFailed = -1,
    Panicked = -2,
};

/// Sentinel-based: fields left at UINT32_MAX / NaN keep the preset's
/// value (preset 0 = solver defaults, 1 = conservative).
struct LmConfig {
    uint32_t preset = 0;
    uint32_t max_iters = UINT32_MAX;
    uint32_t min_iters = UINT32_MAX;
    uint32_t patience = UINT32_MAX;
    double abs_precision = NAN;
    double rel_precision = NAN;
    double initial_lambda = NAN;
    double cost_threshold = NAN;

    static LmConfig defaults() { return LmConfig{}; }
    static LmConfig conservative() { LmConfig c; c.preset = 1; return c; }
};

struct LmResult {
    double start_cost;
    double end_cost;
    uint32_t iterations;
    uint32_t accepted_iterations;
    LmStatus status;
    double lambda;

    /// True for the healthy terminations (the solver returned a state
    /// it stands behind).
    bool ok() const { return static_cast<int32_t>(status) >= 0
        && status != LmStatus::Aborted; }
};

namespace ffi {
struct Fit;
struct N;
struct Obs;

extern "C" {
double n_v(const N*);
void n_set_v(N*, double);
double n_t(const N*);
void n_set_t(N*, double);
double n_w(const N*);
void n_set_w(N*, double);
double obs_x(const Obs*);
void obs_set_x(Obs*, double);
double obs_y(const Obs*);
void obs_set_y(Obs*, double);
double fit_m(const Fit*);
void fit_set_m(Fit*, double);
double fit_c(const Fit*);
void fit_set_c(Fit*, double);
uint32_t fit_obs_len(const Fit*);
Obs* fit_obs_push(Fit*);
Obs* fit_obs_at(Fit*, uint32_t);
uint32_t fit_items_len(const Fit*);
N* fit_items_push(Fit*);
N* fit_items_at(Fit*, uint32_t);
Fit* fit_new(void);
void fit_free(Fit*);
const char* fit_last_error(const Fit*);
const char* fit_validate(Fit*);
int32_t fit_solve_dense(Fit*, const LmConfig*, LmResult*);
int32_t fit_solve_sparse(Fit*, const LmConfig*, LmResult*);
}
} // namespace ffi

/// A `N` in its collection. Thin pointer wrapper -- validity
/// follows the collection's storage (see the view).
class NRef {
public:
    explicit NRef(ffi::N* p) : p_(p) {}
    double v() const { return ffi::n_v(p_); }
    void set_v(double v) { ffi::n_set_v(p_, v); }
    double t() const { return ffi::n_t(p_); }
    void set_t(double v) { ffi::n_set_t(p_, v); }
    double w() const { return ffi::n_w(p_); }
    void set_w(double v) { ffi::n_set_w(p_, v); }
private:
    ffi::N* p_;
};

/// A `Obs` in its collection. Thin pointer wrapper -- validity
/// follows the collection's storage (see the view).
class ObsRef {
public:
    explicit ObsRef(ffi::Obs* p) : p_(p) {}
    double x() const { return ffi::obs_x(p_); }
    void set_x(double v) { ffi::obs_set_x(p_, v); }
    double y() const { return ffi::obs_y(p_); }
    void set_y(double v) { ffi::obs_set_y(p_, v); }
private:
    ffi::Obs* p_;
};

/// `Fit.obs`. std::vec::Vec storage: pushes may MOVE elements -- re-fetch
/// element refs after a push.
class ObsView {
public:
    explicit ObsView(ffi::Fit* h) : h_(h) {}
    uint32_t size() const { return ffi::fit_obs_len(h_); }
    ObsRef push() { return ObsRef(ffi::fit_obs_push(h_)); }
    ObsRef operator[](uint32_t i) { return ObsRef(ffi::fit_obs_at(h_, i)); }
private:
    ffi::Fit* h_;
};

/// `Fit.items`. Element pointers are STABLE across pushes (chunked storage).
class ItemsView {
public:
    explicit ItemsView(ffi::Fit* h) : h_(h) {}
    uint32_t size() const { return ffi::fit_items_len(h_); }
    NRef push() { return NRef(ffi::fit_items_push(h_)); }
    NRef operator[](uint32_t i) { return NRef(ffi::fit_items_at(h_, i)); }
private:
    ffi::Fit* h_;
};

/// The `Fit` model. Owns the Rust-side object; move-only.
class Fit {
public:
    Fit() : h_(ffi::fit_new()) {}
    ~Fit() { if (h_) ffi::fit_free(h_); }
    Fit(const Fit&) = delete;
    Fit& operator=(const Fit&) = delete;
    Fit(Fit&& o) noexcept : h_(o.h_) { o.h_ = nullptr; }
    Fit& operator=(Fit&& o) noexcept {
        if (this != &o) {
            if (h_) ffi::fit_free(h_);
            h_ = o.h_;
            o.h_ = nullptr;
        }
        return *this;
    }

    double m() const { return ffi::fit_m(h_); }
    void set_m(double v) { ffi::fit_set_m(h_, v); }
    double c() const { return ffi::fit_c(h_); }
    void set_c(double v) { ffi::fit_set_c(h_, v); }
    ObsView obs() { return ObsView(h_); }
    ItemsView items() { return ItemsView(h_); }
    // field `tag`: String -- opaque, no accessor generated

    LmResult solve_dense(const LmConfig& cfg = LmConfig{}) {
        LmResult r;
        ffi::fit_solve_dense(h_, &cfg, &r);
        return r;
    }
    LmResult solve_sparse(const LmConfig& cfg = LmConfig{}) {
        LmResult r;
        ffi::fit_solve_sparse(h_, &cfg, &r);
        return r;
    }
    /// Empty string when the model is clean, the Diagnostic text
    /// otherwise. The returned pointer is valid until the next call on
    /// this model.
    const char* validate() { return ffi::fit_validate(h_); }
    const char* last_error() const { return ffi::fit_last_error(h_); }

private:
    ffi::Fit* h_;
};

} // namespace arael
