# GENERATED by cargo-arael from the `Graph` model sidecar. Do not
# edit; regenerate with `cargo arael export`.
"""Python interface for the `Graph` model: build the problem, solve,
read the results back. Pure ctypes over the capi cdylib; see
docs/CXX.md for the shared surface semantics (this module mirrors the
C++ classes one-to-one)."""

import ctypes
import os

from . import _graph_ffi as _f
from .arael import math as _m
from .arael.solver import (AraelError, CovMode, EnvelopeMode, FaerOrdering,
                           LmPreset, LmStatus, LmTiming, LogLevel,
                           ReducedOrdering, SchurPlan, SchurPolicy,
                           SchurSolve)

LmIter = _f.LmIter

_lib = None


def load(path=None):
    """Load and bind the capi cdylib. Called implicitly on first
    model construction; call explicitly to pick a specific library.
    Resolution: explicit path, $ARAEL_CAPI, then the conventional
    cargo build locations next to the package."""
    global _lib
    if _lib is not None:
        return
    pkg = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    names = ["lib{}.so", "lib{}.dylib", "{}.dll"]
    tried = []
    candidates = [path, os.environ.get("ARAEL_CAPI")]
    for rel in ("../capi/target", "../target", "../../target"):
        for profile in ("release", "debug"):
            for n in names:
                candidates.append(os.path.join(
                    pkg, rel, profile, n.format("m3500_demo_capi")))
    for c in candidates:
        if not c:
            continue
        if not os.path.exists(c):
            tried.append(c)
            continue
        _lib = ctypes.CDLL(c)
        _f.bind(_lib)
        return
    raise AraelError(-1, "no capi cdylib found; build it with "
        "`cargo build --release -p <crate>-capi` or set ARAEL_CAPI. "
        "Tried: " + ", ".join(tried))


def set_log_level(level):
    """Drop arael log messages above `level` (a LogLevel; INFO --
    everything -- is the default). Process-wide: all models and roots
    share it."""
    load()
    _f.graph_set_log_level(int(level))


def _raw(r):
    return r.raw if hasattr(r, "raw") else int(r)


def _err(h):
    return (_f.graph_last_error(h) or b"").decode()


class LmConfig(_f.LmConfigRaw):
    """The solver configuration, holding the chosen preset's actual
    Rust values (fetched through the FFI at construction)."""

    def __init__(self, preset=LmPreset.DEFAULTS):
        load()
        _f.graph_lm_config(int(preset), ctypes.byref(self))

    @classmethod
    def defaults(cls):
        return cls(LmPreset.DEFAULTS)

    @classmethod
    def conservative(cls):
        return cls(LmPreset.CONSERVATIVE)

    @classmethod
    def well_conditioned(cls):
        return cls(LmPreset.WELL_CONDITIONED)

    @classmethod
    def ill_conditioned(cls):
        return cls(LmPreset.ILL_CONDITIONED)


class SparseOptions(_f.SparseOptionsRaw):
    """The sparse backend's options, holding the actual Rust
    defaults (fetched through the FFI at construction). Edit fields,
    pass to solve_sparse."""

    def __init__(self):
        load()
        _f.graph_sparse_options(ctypes.byref(self))


class LmSession:
    """Warm reuse over repeated sparse solves: keeps the analysis
    (pattern, ordering, symbolic factorization, Schur plan) across
    solves, so only the first pays for it. Warm solves are
    bit-identical to cold ones. A parameter-count change re-analyzes
    by itself; call invalidate() after a structural change at the
    same count (solving warm through one is undefined)."""

    def __init__(self, opts=None):
        load()
        self._s = _f.graph_session_new(
            ctypes.byref(opts) if opts is not None else None)

    def free(self):
        if self._s:
            _f.graph_session_free(self._s)
            self._s = None

    def __del__(self):
        try:
            self.free()
        except Exception:
            pass

    def solve(self, model, cfg=None):
        """Solve through the session; contract as solve_sparse."""
        cfg = cfg if cfg is not None else LmConfig()
        r = LmResult()
        return model._solved(
            _f.graph_session_solve(self._s, model._p, ctypes.byref(cfg),
                                       ctypes.byref(r)), r)

    def invalidate(self):
        """Drop the learned structure; the next solve runs cold."""
        _f.graph_session_invalidate(self._s)


class LmResult(_f.LmResultRaw):
    """A completed solve (see arael.solver for the fields); owns the
    full Rust-side result until garbage collected."""

    def report(self):
        """Text report: status, cost, iterations, damping, plus the
        timing breakdown and the backend's plan when gathered."""
        if not self._detail:
            return ""
        return _f.graph_result_report(self._detail, False).decode()

    def pretty_report(self):
        """report() with colour and box-drawing glyphs."""
        if not self._detail:
            return ""
        return _f.graph_result_report(self._detail, True).decode()

    @property
    def plan(self):
        """The sparse backend's SchurPlan, or None when the solve
        carried none (dense and band solves)."""
        p = SchurPlan()
        if self._detail and _f.graph_result_plan(self._detail,
                                                     ctypes.byref(p)):
            return p
        return None

    def __del__(self):
        d, self._detail = self._detail, None
        if d:
            try:
                _f.graph_result_free(d)
            except Exception:
                pass


class EdgeRef:
    """Typed handle into the collection that issued it -- the Python
    spelling of Rust's `Ref<Edge>`. Default-constructed it is the null
    sentinel."""

    __slots__ = ("raw",)

    def __init__(self, raw=0xFFFFFFFF):
        self.raw = raw

    @property
    def valid(self):
        return self.raw != 0xFFFFFFFF

    def __eq__(self, o):
        return isinstance(o, EdgeRef) and o.raw == self.raw

    def __hash__(self):
        return hash((EdgeRef, self.raw))

    def __repr__(self):
        return "EdgeRef(%s)" % (self.raw if self.valid else "null")


class Pose2Ref:
    """Typed handle into the collection that issued it -- the Python
    spelling of Rust's `Ref<Pose2>`. Default-constructed it is the null
    sentinel."""

    __slots__ = ("raw",)

    def __init__(self, raw=0xFFFFFFFF):
        self.raw = raw

    @property
    def valid(self):
        return self.raw != 0xFFFFFFFF

    def __eq__(self, o):
        return isinstance(o, Pose2Ref) and o.raw == self.raw

    def __hash__(self):
        return hash((Pose2Ref, self.raw))

    def __repr__(self):
        return "Pose2Ref(%s)" % (self.raw if self.valid else "null")


class PriorRef:
    """Typed handle into the collection that issued it -- the Python
    spelling of Rust's `Ref<Prior>`. Default-constructed it is the null
    sentinel."""

    __slots__ = ("raw",)

    def __init__(self, raw=0xFFFFFFFF):
        self.raw = raw

    @property
    def valid(self):
        return self.raw != 0xFFFFFFFF

    def __eq__(self, o):
        return isinstance(o, PriorRef) and o.raw == self.raw

    def __hash__(self):
        return hash((PriorRef, self.raw))

    def __repr__(self):
        return "PriorRef(%s)" % (self.raw if self.valid else "null")


class Edge:
    """A `Edge` in its owner's storage, addressed by key rather than by
    pointer: the pointer is re-resolved on every access, so growing the
    collection cannot leave this wrapper dangling."""

    __slots__ = ("_at",)
    param_count = 0

    def __init__(self, at):
        # Zero-argument callable returning a currently-valid pointer.
        self._at = at

    @property
    def _p(self):
        return self._at()

    @property
    def a(self):
        return Pose2Ref(_f.graph_edge_a(self._p))

    @a.setter
    def a(self, r):
        _f.graph_edge_set_a(self._p, _raw(r))

    @property
    def b(self):
        return Pose2Ref(_f.graph_edge_b(self._p))

    @b.setter
    def b(self, r):
        _f.graph_edge_set_b(self._p, _raw(r))

    @property
    def delta(self):
        return _f.graph_edge_delta(self._p)

    @delta.setter
    def delta(self, v):
        _f.graph_edge_set_delta(self._p, v if isinstance(v, _m.vect2d) else _m.vect2d(v))

    @property
    def dth(self):
        return _f.graph_edge_dth(self._p)

    @dth.setter
    def dth(self, v):
        _f.graph_edge_set_dth(self._p, v)

    @property
    def wt(self):
        return _f.graph_edge_wt(self._p)

    @wt.setter
    def wt(self, v):
        _f.graph_edge_set_wt(self._p, v)

    @property
    def wr(self):
        return _f.graph_edge_wr(self._p)

    @wr.setter
    def wr(self, v):
        _f.graph_edge_set_wr(self._p, v)


class Pose2:
    """A `Pose2` in its owner's storage, addressed by key rather than by
    pointer: the pointer is re-resolved on every access, so growing the
    collection cannot leave this wrapper dangling."""

    __slots__ = ("_at",)
    param_count = 3

    def __init__(self, at):
        # Zero-argument callable returning a currently-valid pointer.
        self._at = at

    @property
    def _p(self):
        return self._at()

    @property
    def pos(self):
        return _f.graph_pose2_pos(self._p)

    @pos.setter
    def pos(self, v):
        _f.graph_pose2_set_pos(self._p, v if isinstance(v, _m.vect2d) else _m.vect2d(v))

    @property
    def pos_optimize(self):
        return _f.graph_pose2_pos_optimize(self._p)

    @pos_optimize.setter
    def pos_optimize(self, v):
        _f.graph_pose2_pos_set_optimize(self._p, bool(v))

    @property
    def rot_angle(self):
        return _f.graph_pose2_rot_angle(self._p)

    @rot_angle.setter
    def rot_angle(self, v):
        _f.graph_pose2_rot_set_angle(self._p, v)

    @property
    def rot_angle_optimize(self):
        return _f.graph_pose2_rot_angle_optimize(self._p)

    @rot_angle_optimize.setter
    def rot_angle_optimize(self, v):
        _f.graph_pose2_rot_angle_set_optimize(self._p, bool(v))

    @property
    def rot_rotation_matrix(self):
        """Rotation matrix at the current angle (read-only)."""
        return _f.graph_pose2_rot_rotation_matrix(self._p)


class Prior:
    """A `Prior` in its owner's storage, addressed by key rather than by
    pointer: the pointer is re-resolved on every access, so growing the
    collection cannot leave this wrapper dangling."""

    __slots__ = ("_at",)
    param_count = 0

    def __init__(self, at):
        # Zero-argument callable returning a currently-valid pointer.
        self._at = at

    @property
    def _p(self):
        return self._at()

    @property
    def p(self):
        return Pose2Ref(_f.graph_prior_p(self._p))

    @p.setter
    def p(self, r):
        _f.graph_prior_set_p(self._p, _raw(r))

    @property
    def pos(self):
        return _f.graph_prior_pos(self._p)

    @pos.setter
    def pos(self, v):
        _f.graph_prior_set_pos(self._p, v if isinstance(v, _m.vect2d) else _m.vect2d(v))

    @property
    def th(self):
        return _f.graph_prior_th(self._p)

    @th.setter
    def th(self, v):
        _f.graph_prior_set_th(self._p, v)


def _cov_query(c, fn, p, cap):
    buf = (ctypes.c_double * cap)()
    n = fn(c, p, buf, cap)
    if n < 0:
        raise AraelError(
            n, (_f.graph_cov_error(c) or b"").decode())
    return buf


def _shape_1(buf):
    return float(buf[0])


def _shape_2(buf):
    return _m.matrix2d.from_elements(buf[0], buf[1], buf[2], buf[3])


def _shape_3(buf):
    return _m.matrix3d.from_elements(*[buf[i] for i in range(9)])


def _shape_n(buf, n):
    return tuple(tuple(buf[r * n + c] for c in range(n)) for r in range(n))


class Covariance:
    """An assembled covariance, OWNED: released on garbage
    collection (free() to force it), independent of later assemblies.
    Per-entity queries (marginal/conditional by param count: 1 ->
    float, 2/3 -> matrix2d/3d, larger -> row-major tuples). Entity
    arguments must come from the live model."""

    __slots__ = ("_h",)

    def __init__(self, h):
        self._h = h

    def free(self):
        if self._h:
            _f.graph_cov_free(self._h)
            self._h = None

    def __del__(self):
        try:
            self.free()
        except Exception:
            pass

    def marginal(self, e):
        """The entity's marginal covariance block."""
        if isinstance(e, Pose2):
            return (_shape_3)(_cov_query(self._h, _f.graph_pose2_marginal_cov, e._p, 9))
        raise TypeError("no marginal for %r" % (e,))

    def conditional(self, e):
        """Conditional covariance (all other parameters fixed)."""
        if isinstance(e, Pose2):
            return (_shape_3)(_cov_query(self._h, _f.graph_pose2_conditional_cov, e._p, 9))
        raise TypeError("no conditional for %r" % (e,))

    def std_dev(self, e):
        """Per-parameter standard deviations (every CovMode, incl.
        TriDiagonal)."""
        if isinstance(e, Pose2):
            return list(_cov_query(self._h, _f.graph_pose2_std_dev, e._p, 3))
        raise TypeError("no std_dev for %r" % (e,))
    def _cross_pose2_pose2(self, a, b):
        buf = (ctypes.c_double * 9)()
        rows = _f.graph_pose2_pose2_cross_cov(self._h, a._p, b._p, buf, 9)
        if rows < 0:
            raise AraelError(
                rows, (_f.graph_cov_error(self._h) or b"").decode())
        return tuple(tuple(buf[r * 3 + c] for c in range(3))
                     for r in range(rows))

    def cross(self, a, b):
        """Row-major cross-covariance block between two entities."""
        if isinstance(a, Pose2) and isinstance(b, Pose2):
            return self._cross_pose2_pose2(a, b)
        raise TypeError("no cross-covariance for %r x %r" % (a, b))


class GraphPosesVec:
    """View of `poses` (vec of Pose2); element wrappers re-resolve
    their pointer by key on every access, so growing the collection
    cannot leave them dangling. Mutating while iterating is undefined."""

    __slots__ = ("_p",)

    def __init__(self, p):
        self._p = p

    def __len__(self):
        return _f.graph_poses_len(self._p)

    def reserve(self, additional):
        _f.graph_poses_reserve(self._p, additional)

    def __getitem__(self, i):
        if isinstance(i, Pose2Ref):
            return Pose2(lambda r=i.raw: _f.graph_poses_get(self._p, r))
        n = len(self)
        if i < 0:
            i += n
        if not 0 <= i < n:
            raise IndexError(i)
        return Pose2(lambda i=i: _f.graph_poses_at(self._p, i))

    def __iter__(self):
        for i in range(len(self)):
            yield Pose2(lambda i=i: _f.graph_poses_at(self._p, i))

    def clear(self):
        _f.graph_poses_clear(self._p)

    def truncate(self, n):
        _f.graph_poses_truncate(self._p, n)

    def push(self):
        _f.graph_poses_push(self._p)
        return self[self.ref_at(len(self) - 1)]

    def pop(self):
        """Drops the last element; False when already empty."""
        return _f.graph_poses_pop(self._p)

    def get(self, r):
        return Pose2(lambda k=_raw(r): _f.graph_poses_get(self._p, k))

    def __contains__(self, r):
        return _f.graph_poses_contains(self._p, _raw(r))

    def try_get(self, r):
        """The element, or None for a stale or foreign ref."""
        p = _f.graph_poses_try_get(self._p, _raw(r))
        return Pose2(lambda k=_raw(r): _f.graph_poses_get(self._p, k)) if p else None

    def ref_at(self, i):
        return Pose2Ref(_f.graph_poses_ref_at(self._p, i))

    def first_ref(self):
        """Ref of the first element; null when empty."""
        return Pose2Ref(_f.graph_poses_first_ref(self._p))

    def last_ref(self):
        """Ref of the last element; null when empty."""
        return Pose2Ref(_f.graph_poses_last_ref(self._p))


class GraphEdgesVec:
    """View of `edges` (vec of Edge); element wrappers re-resolve
    their pointer by key on every access, so growing the collection
    cannot leave them dangling. Mutating while iterating is undefined."""

    __slots__ = ("_p",)

    def __init__(self, p):
        self._p = p

    def __len__(self):
        return _f.graph_edges_len(self._p)

    def reserve(self, additional):
        _f.graph_edges_reserve(self._p, additional)

    def __getitem__(self, i):
        n = len(self)
        if i < 0:
            i += n
        if not 0 <= i < n:
            raise IndexError(i)
        return Edge(lambda i=i: _f.graph_edges_at(self._p, i))

    def __iter__(self):
        for i in range(len(self)):
            yield Edge(lambda i=i: _f.graph_edges_at(self._p, i))

    def clear(self):
        _f.graph_edges_clear(self._p)

    def truncate(self, n):
        _f.graph_edges_truncate(self._p, n)

    def push(self):
        _f.graph_edges_push(self._p)
        return self[len(self) - 1]

    def pop(self):
        """Drops the last element; False when already empty."""
        return _f.graph_edges_pop(self._p)


class Graph:
    """The model. Owns the underlying Rust instance; free() (or GC)
    releases it. One model, one thread."""

    def __init__(self):
        load()
        self._p = _f.graph_new()

    def free(self):
        if self._p:
            _f.graph_free(self._p)
            self._p = None

    def __del__(self):
        try:
            self.free()
        except Exception:
            pass

    def _solved(self, code, res):
        if code < 0:
            raise AraelError(code, _err(self._p),
                             res if res._detail else None)
        return res

    def solve_dense(self, cfg=None):
        cfg = cfg if cfg is not None else LmConfig()
        r = LmResult()
        return self._solved(
            _f.graph_solve_dense(self._p, ctypes.byref(cfg),
                                     ctypes.byref(r)), r)

    def solve_sparse(self, cfg=None, opts=None):
        """Sparse solve; `opts` (a SparseOptions) selects the
        backend's route, None means the defaults."""
        cfg = cfg if cfg is not None else LmConfig()
        r = LmResult()
        return self._solved(
            _f.graph_solve_sparse(
                self._p, ctypes.byref(cfg),
                ctypes.byref(opts) if opts is not None else None,
                ctypes.byref(r)), r)

    def solve_band(self, kd, cfg=None):
        """Band Cholesky solve; kd is the half-bandwidth in scalar
        parameters."""
        cfg = cfg if cfg is not None else LmConfig()
        r = LmResult()
        return self._solved(
            _f.graph_solve_band(self._p, kd, ctypes.byref(cfg),
                                    ctypes.byref(r)), r)

    def assemble_covariance(self, mode=CovMode.ALL_MARGINALS):
        c = ctypes.c_void_p()
        code = _f.graph_assemble_covariance(self._p, int(mode),
                                                ctypes.byref(c))
        if code != 0:
            raise AraelError(code, _err(self._p))
        return Covariance(c)

    def cost(self):
        """Total cost at the current parameter values (no solve)."""
        return _f.graph_cost(self._p)

    def validate(self):
        """Empty string when the model is clean, the diagnostic text
        otherwise."""
        return _f.graph_validate(self._p).decode()

    def last_error(self):
        return _err(self._p)

    @property
    def poses(self):
        return GraphPosesVec(self._p)

    @property
    def edges(self):
        return GraphEdgesVec(self._p)

    @property
    def prior(self):
        """The `Prior`, or None while absent (make_prior() creates)."""
        if not _f.graph_prior(self._p):
            return None
        return Prior(lambda: _f.graph_prior(self._p))

    def make_prior(self):
        _f.graph_make_prior(self._p)
        return Prior(lambda: _f.graph_prior(self._p))

    def clear_prior(self):
        _f.graph_clear_prior(self._p)

