// GENERATED by cargo-arael from the `Graph` model sidecar. Do not edit;
// regenerate with `cargo arael export` (check drift with `cargo arael check`).
#![allow(clippy::missing_safety_doc)]

use std::ffi::CString;
use std::os::raw::c_char;
use std::panic::{AssertUnwindSafe, catch_unwind};
use arael::covariance::{CovAssembly, CovMode, Covariance};
use arael::simple_lm::{LmConfig, LmProblem, LmStatus};
use m3500_demo::{Edge, Graph, Pose2, Prior};

/// The opaque handle the C ABI hands out: the model, the error /
/// diagnostic text buffer `last_error` points into, and the covariance
/// assembly once requested.
pub struct GraphHandle {
    model: Graph,
    text: CString,
    cov: Option<CovAssembly>,
}

macro_rules! c_vec2 {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub x: $t, pub y: $t }
        impl From<arael::vect::vect2<$t>> for $name {
            fn from(v: arael::vect::vect2<$t>) -> Self { Self { x: v.x, y: v.y } }
        }
        impl From<$name> for arael::vect::vect2<$t> {
            fn from(v: $name) -> Self { arael::vect::vect2::new(v.x, v.y) }
        }
    };
}
macro_rules! c_vec3 {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub x: $t, pub y: $t, pub z: $t }
        impl From<arael::vect::vect3<$t>> for $name {
            fn from(v: arael::vect::vect3<$t>) -> Self { Self { x: v.x, y: v.y, z: v.z } }
        }
        impl From<$name> for arael::vect::vect3<$t> {
            fn from(v: $name) -> Self { arael::vect::vect3::new(v.x, v.y, v.z) }
        }
    };
}
macro_rules! c_mat2 {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub m: [[$t; 2]; 2] }
        impl From<arael::matrix::matrix2<$t>> for $name {
            fn from(v: arael::matrix::matrix2<$t>) -> Self {
                Self { m: [[v.rows[0].x, v.rows[0].y], [v.rows[1].x, v.rows[1].y]] }
            }
        }
        impl From<$name> for arael::matrix::matrix2<$t> {
            fn from(v: $name) -> Self {
                arael::matrix::matrix2::from_elements(v.m[0][0], v.m[0][1], v.m[1][0], v.m[1][1])
            }
        }
    };
}
macro_rules! c_mat3 {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub m: [[$t; 3]; 3] }
        impl From<arael::matrix::matrix3<$t>> for $name {
            fn from(v: arael::matrix::matrix3<$t>) -> Self {
                Self { m: [
                    [v.rows[0].x, v.rows[0].y, v.rows[0].z],
                    [v.rows[1].x, v.rows[1].y, v.rows[1].z],
                    [v.rows[2].x, v.rows[2].y, v.rows[2].z],
                ] }
            }
        }
        impl From<$name> for arael::matrix::matrix3<$t> {
            fn from(v: $name) -> Self { arael::matrix::matrix3::from_array(v.m) }
        }
    };
}
macro_rules! c_quat {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub t: $t, pub x: $t, pub y: $t, pub z: $t }
        impl From<arael::quatern::quatern<$t>> for $name {
            fn from(q: arael::quatern::quatern<$t>) -> Self {
                Self { t: q.t, x: q.v.x, y: q.v.y, z: q.v.z }
            }
        }
        impl From<$name> for arael::quatern::quatern<$t> {
            fn from(q: $name) -> Self {
                arael::quatern::quatern::new(q.t, arael::vect::vect3::new(q.x, q.y, q.z))
            }
        }
    };
}
c_vec2!(CVec2F32, f32);
c_vec2!(CVec2F64, f64);
c_vec3!(CVec3F32, f32);
c_vec3!(CVec3F64, f64);
c_mat2!(CMat2F32, f32);
c_mat2!(CMat2F64, f64);
c_mat3!(CMat3F32, f32);
c_mat3!(CMat3F64, f64);
c_quat!(CQuatF32, f32);
c_quat!(CQuatF64, f64);

fn status_code(s: &LmStatus) -> i32 {
    match s {
        LmStatus::Converged => 0,
        LmStatus::CostThreshold => 1,
        LmStatus::MaxIterations => 2,
        LmStatus::GradientTolerance => 3,
        LmStatus::ParameterTolerance => 4,
        LmStatus::PredictedReduction => 5,
        LmStatus::LambdaCeiling => 6,
        LmStatus::DriverTerminated => 7,
        LmStatus::ObserverTerminated => 8,
        LmStatus::TimeLimit => 9,
        LmStatus::RetryBudgetExhausted => 10,
        LmStatus::Aborted => 11,
    }
}

fn set_text(h: &mut GraphHandle, msg: &str) {
    h.text = CString::new(msg.replace('\0', " ")).unwrap();
}

fn panic_text(p: Box<dyn std::any::Any + Send>) -> String {
    if let Some(s) = p.downcast_ref::<&str>() {
        (*s).to_string()
    } else if let Some(s) = p.downcast_ref::<String>() {
        s.clone()
    } else {
        "panic".to_string()
    }
}

/// C mirror of `arael::option<T>` ({has, value}; layouts must match).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct COptF {
    pub has: bool,
    pub v: f64,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct COptSeconds {
    pub has: bool,
    pub v: f64,
}

fn copt(o: Option<f64>) -> COptF {
    match o {
        Some(v) => COptF { has: true, v },
        None => COptF { has: false, v: 0.0 },
    }
}

fn opt_of(c: COptF) -> Option<f64> {
    c.has.then_some(c.v)
}

/// The solver config as REAL values: constructed by
/// graph_lm_config (which copies them out of the actual Rust
/// LmConfig preset), edited freely, passed back whole. The preset tag
/// stays the base for the Rust fields this struct does not expose
/// (lambda driver, observer, gather_timing). Field order is C ABI.
#[repr(C)]
pub struct CLmConfig {
    pub preset: u32,
    pub max_iters: u32,
    pub min_iters: u32,
    pub patience: u32,
    pub num_threads: u32,
    pub verbose: bool,
    pub abs_precision: f64,
    pub rel_precision: f64,
    pub initial_lambda: f64,
    pub cost_threshold: f64,
    pub lambda_floor: f64,
    pub gradient_tolerance: COptF,
    pub parameter_tolerance: COptF,
    pub predicted_reduction_tolerance: COptF,
    pub min_diagonal: COptF,
    pub time_limit_seconds: COptSeconds,
}

fn preset_config(preset: u32) -> LmConfig<f64> {
    match preset {
        1 => LmConfig::conservative(),
        2 => LmConfig::well_conditioned(),
        _ => LmConfig::default(),
    }
}

/// Fill `out` with the preset's actual Rust values (0 = defaults,
/// 1 = conservative, 2 = well_conditioned).
#[no_mangle]
pub unsafe extern "C" fn graph_lm_config(preset: u32, out: *mut CLmConfig) {
    let c = preset_config(preset);
    *out = CLmConfig {
        preset,
        max_iters: c.max_iters as u32,
        min_iters: c.min_iters as u32,
        patience: c.patience as u32,
        num_threads: c.num_threads as u32,
        verbose: c.verbose,
        abs_precision: c.abs_precision,
        rel_precision: c.rel_precision,
        initial_lambda: c.initial_lambda,
        cost_threshold: c.cost_threshold,
        lambda_floor: c.lambda_floor,
        gradient_tolerance: copt(c.gradient_tolerance),
        parameter_tolerance: copt(c.parameter_tolerance),
        predicted_reduction_tolerance: copt(c.predicted_reduction_tolerance),
        min_diagonal: copt(c.min_diagonal),
        time_limit_seconds: match c.time_limit {
            Some(d) => COptSeconds { has: true, v: d.as_secs_f64() },
            None => COptSeconds { has: false, v: 0.0 },
        },
    };
}

impl CLmConfig {
    fn to_config(&self) -> LmConfig<f64> {
        let mut c = preset_config(self.preset);
        c.max_iters = self.max_iters as usize;
        c.min_iters = self.min_iters as usize;
        c.patience = self.patience as usize;
        c.num_threads = self.num_threads as usize;
        c.verbose = self.verbose;
        c.abs_precision = self.abs_precision;
        c.rel_precision = self.rel_precision;
        c.initial_lambda = self.initial_lambda;
        c.cost_threshold = self.cost_threshold;
        c.lambda_floor = self.lambda_floor;
        c.gradient_tolerance = opt_of(self.gradient_tolerance);
        c.parameter_tolerance = opt_of(self.parameter_tolerance);
        c.predicted_reduction_tolerance = opt_of(self.predicted_reduction_tolerance);
        c.min_diagonal = opt_of(self.min_diagonal);
        c.time_limit = self.time_limit_seconds.has.then(|| {
            std::time::Duration::from_secs_f64(self.time_limit_seconds.v)
        });
        c
    }
}

#[repr(C)]
pub struct CLmResult {
    pub start_cost: f64,
    pub end_cost: f64,
    pub iterations: u32,
    pub accepted_iterations: u32,
    pub status: i32,
    pub final_lambda: f64,
}

#[no_mangle]
pub extern "C" fn graph_new() -> *mut GraphHandle {
    Box::into_raw(Box::new(GraphHandle {
        model: Default::default(),
        text: CString::default(),
        cov: None,
    }))
}

#[no_mangle]
pub unsafe extern "C" fn graph_free(h: *mut GraphHandle) {
    if !h.is_null() {
        drop(Box::from_raw(h));
    }
}

#[no_mangle]
pub unsafe extern "C" fn graph_last_error(h: *const GraphHandle) -> *const c_char {
    (*h).text.as_ptr()
}

/// Empty string when the model is clean, the Diagnostic text otherwise.
#[no_mangle]
pub unsafe extern "C" fn graph_validate(h: *mut GraphHandle) -> *const c_char {
    let hh = &mut *h;
    let text = match catch_unwind(AssertUnwindSafe(|| {
        let d = hh.model.validate();
        if d.is_clean() { String::new() } else { d.to_string() }
    })) {
        Ok(t) => t,
        Err(p) => panic_text(p),
    };
    set_text(hh, &text);
    hh.text.as_ptr()
}

/// Returns the status code (>= 0: LmStatus; -1: solve failure; -2:
/// panic). Failure text via graph_last_error.
#[no_mangle]
pub unsafe extern "C" fn graph_solve_dense(
    h: *mut GraphHandle,
    cfg: *const CLmConfig,
    out: *mut CLmResult,
) -> i32 {
    let hh = &mut *h;
    let c = (*cfg).to_config();
    *out = CLmResult {
        start_cost: 0.0, end_cost: 0.0, iterations: 0,
        accepted_iterations: 0, status: -1, final_lambda: 0.0,
    };
    match catch_unwind(AssertUnwindSafe(|| hh.model.solve_dense(&c))) {
        Ok(Ok(r)) => {
            let code = status_code(&r.status);
            *out = CLmResult {
                start_cost: r.start_cost,
                end_cost: r.end_cost,
                iterations: r.iterations as u32,
                accepted_iterations: r.accepted_iterations as u32,
                status: code,
                final_lambda: r.final_lambda,
            };
            set_text(hh, "");
            code
        }
        Ok(Err(f)) => {
            set_text(hh, &format!("solve failure: {:?}", f.kind));
            (*out).status = -1;
            -1
        }
        Err(p) => {
            let msg = panic_text(p);
            set_text(hh, &msg);
            (*out).status = -2;
            -2
        }
    }
}

/// Returns the status code (>= 0: LmStatus; -1: solve failure; -2:
/// panic). Failure text via graph_last_error.
#[no_mangle]
pub unsafe extern "C" fn graph_solve_sparse(
    h: *mut GraphHandle,
    cfg: *const CLmConfig,
    out: *mut CLmResult,
) -> i32 {
    let hh = &mut *h;
    let c = (*cfg).to_config();
    *out = CLmResult {
        start_cost: 0.0, end_cost: 0.0, iterations: 0,
        accepted_iterations: 0, status: -1, final_lambda: 0.0,
    };
    match catch_unwind(AssertUnwindSafe(|| hh.model.solve_sparse(&c))) {
        Ok(Ok(r)) => {
            let code = status_code(&r.status);
            *out = CLmResult {
                start_cost: r.start_cost,
                end_cost: r.end_cost,
                iterations: r.iterations as u32,
                accepted_iterations: r.accepted_iterations as u32,
                status: code,
                final_lambda: r.final_lambda,
            };
            set_text(hh, "");
            code
        }
        Ok(Err(f)) => {
            set_text(hh, &format!("solve failure: {:?}", f.kind));
            (*out).status = -1;
            -1
        }
        Err(p) => {
            let msg = panic_text(p);
            set_text(hh, &msg);
            (*out).status = -2;
            -2
        }
    }
}

/// Band Cholesky solve; `kd` is the Hessian half-bandwidth in scalar
/// parameters. Returns the status code (>= 0: LmStatus; -1: solve
/// failure; -2: panic). Failure text via graph_last_error.
#[no_mangle]
pub unsafe extern "C" fn graph_solve_band(
    h: *mut GraphHandle,
    kd: u32,
    cfg: *const CLmConfig,
    out: *mut CLmResult,
) -> i32 {
    let hh = &mut *h;
    let c = (*cfg).to_config();
    *out = CLmResult {
        start_cost: 0.0, end_cost: 0.0, iterations: 0,
        accepted_iterations: 0, status: -1, final_lambda: 0.0,
    };
    match catch_unwind(AssertUnwindSafe(|| {
        let mut x0 = Vec::new();
        hh.model.serialize64(&mut x0);
        arael::simple_lm::solve_band(&x0, kd as usize, &mut hh.model, &c).map(|r| {
            hh.model.deserialize64(&r.x);
            r
        })
    })) {
        Ok(Ok(r)) => {
            let code = status_code(&r.status);
            *out = CLmResult {
                start_cost: r.start_cost,
                end_cost: r.end_cost,
                iterations: r.iterations as u32,
                accepted_iterations: r.accepted_iterations as u32,
                status: code,
                final_lambda: r.final_lambda,
            };
            set_text(hh, "");
            code
        }
        Ok(Err(f)) => {
            set_text(hh, &format!("solve failure: {:?}", f.kind));
            (*out).status = -1;
            -1
        }
        Err(p) => {
            let msg = panic_text(p);
            set_text(hh, &msg);
            (*out).status = -2;
            -2
        }
    }
}

/// Total cost at the current parameter values (evaluated at the
/// model's precision, returned as f64).
#[no_mangle]
pub unsafe extern "C" fn graph_cost(h: *mut GraphHandle) -> f64 {
    let m = &mut (*h).model;
    let mut params = Vec::new();
    m.serialize64(&mut params);
    m.calc_cost(&params)
}

/// mode: 0 = PerQuery, 1 = AllMarginals, 2 = TriDiagonal. Returns 0,
/// -1 (error, text via graph_last_error), -2 (panic).
#[no_mangle]
pub unsafe extern "C" fn graph_assemble_covariance(h: *mut GraphHandle, mode: u32) -> i32 {
    let hh = &mut *h;
    let m = match mode {
        0 => CovMode::PerQuery,
        2 => CovMode::TriDiagonal,
        _ => CovMode::AllMarginals,
    };
    hh.cov = None;
    match catch_unwind(AssertUnwindSafe(|| hh.model.assemble_covariance(m))) {
        Ok(Ok(c)) => {
            hh.cov = Some(c);
            set_text(hh, "");
            0
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p) => {
            let msg = panic_text(p);
            set_text(hh, &msg);
            -2
        }
    }
}

/// Row-major dim x dim marginal covariance (f64) of one `Pose2`; returns
/// dim, or -1 (error) / -2 (panic) / -3 (no assembly or buffer too
/// small), text via graph_last_error.
#[no_mangle]
pub unsafe extern "C" fn graph_pose2_marginal_cov(
    h: *mut GraphHandle,
    p: *const Pose2,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "marginal_cov: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.marginal_cov(&*p))) {
        Ok(Ok(m)) => {
            let dim = m.nrows();
            if (dim * dim) as u32 > cap {
                set_text(hh, "marginal_cov: buffer too small");
                return -3;
            }
            for r in 0..dim {
                for c in 0..dim {
                    *out.add(r * dim + c) = m[(r, c)];
                }
            }
            dim as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}
/// Per-parameter standard deviations (sqrt of the marginal diagonal)
/// of one `Pose2`; returns the count, or -1 (error) / -2 (panic) / -3
/// (no assembly or buffer too small), text via graph_last_error.
/// Works on every CovMode, including TriDiagonal.
#[no_mangle]
pub unsafe extern "C" fn graph_pose2_std_dev(
    h: *mut GraphHandle,
    p: *const Pose2,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "std_dev: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.std_dev(&*p))) {
        Ok(Ok(sd)) => {
            if sd.len() as u32 > cap {
                set_text(hh, "std_dev: buffer too small");
                return -3;
            }
            for (i, v) in sd.iter().enumerate() {
                *out.add(i) = *v;
            }
            sd.len() as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}

/// Row-major pa x pb cross-covariance (f64) between a `Pose2` and a
/// `Pose2`; returns the row count, or -1 (error) / -2 (panic) / -3 (no
/// assembly or buffer too small), text via graph_last_error.
#[no_mangle]
pub unsafe extern "C" fn graph_pose2_pose2_cross_cov(
    h: *mut GraphHandle,
    a: *const Pose2,
    b: *const Pose2,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "cross_cov: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.cross_cov(&*a, &*b))) {
        Ok(Ok(m)) => {
            let (rows, cols) = (m.nrows(), m.ncols());
            if (rows * cols) as u32 > cap {
                set_text(hh, "cross_cov: buffer too small");
                return -3;
            }
            for r in 0..rows {
                for c in 0..cols {
                    *out.add(r * cols + c) = m[(r, c)];
                }
            }
            rows as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}
#[no_mangle]
pub unsafe extern "C" fn graph_poses_len(p: *const GraphHandle) -> u32 {
    (*p).model.poses.len() as u32
}
#[no_mangle]
pub unsafe extern "C" fn graph_poses_reserve(p: *mut GraphHandle, additional: u32) {
    (*p).model.poses.reserve(additional as usize);
}
#[no_mangle]
pub unsafe extern "C" fn graph_poses_push(p: *mut GraphHandle) -> *mut Pose2 {
    let m = &mut (*p).model.poses;
    let r = m.push(Default::default());
    &mut m[r] as *mut Pose2
}
#[no_mangle]
pub unsafe extern "C" fn graph_poses_at(p: *mut GraphHandle, i: u32) -> *mut Pose2 {
    let m = &mut (*p).model.poses;
    &mut m[i as usize] as *mut Pose2
}
/// Drops the last element; false when already empty.
#[no_mangle]
pub unsafe extern "C" fn graph_poses_pop(p: *mut GraphHandle) -> bool {
    (*p).model.poses.pop().is_some()
}
#[no_mangle]
pub unsafe extern "C" fn graph_poses_clear(p: *mut GraphHandle) {
    (*p).model.poses.clear();
}
#[no_mangle]
pub unsafe extern "C" fn graph_poses_truncate(p: *mut GraphHandle, len: u32) {
    (*p).model.poses.truncate(len as usize);
}
#[no_mangle]
pub unsafe extern "C" fn graph_poses_ref_at(p: *const GraphHandle, i: u32) -> u32 {
    (*p).model.poses.ref_at(i as usize).to_raw()
}
/// Ref of the first/last element, or u32::MAX when empty.
#[no_mangle]
pub unsafe extern "C" fn graph_poses_first_ref(p: *const GraphHandle) -> u32 {
    match (*p).model.poses.first_ref() {
        Some(r) => r.to_raw(),
        None => u32::MAX,
    }
}
#[no_mangle]
pub unsafe extern "C" fn graph_poses_last_ref(p: *const GraphHandle) -> u32 {
    match (*p).model.poses.last_ref() {
        Some(r) => r.to_raw(),
        None => u32::MAX,
    }
}
#[no_mangle]
pub unsafe extern "C" fn graph_poses_get(p: *mut GraphHandle, r: u32) -> *mut Pose2 {
    let m = &mut (*p).model.poses;
    &mut m[arael::refs::Ref::from_raw(r)] as *mut Pose2
}
/// True while `r` addresses a live element of this collection.
#[no_mangle]
pub unsafe extern "C" fn graph_poses_contains(p: *const GraphHandle, r: u32) -> bool {
    (*p).model.poses.contains_ref(arael::refs::Ref::from_raw(r))
}
/// Like get, but null for a stale or foreign ref instead of a panic.
#[no_mangle]
pub unsafe extern "C" fn graph_poses_try_get(p: *mut GraphHandle, r: u32) -> *mut Pose2 {
    let m = &mut (*p).model.poses;
    match m.get_mut(arael::refs::Ref::from_raw(r)) {
        Some(e) => e as *mut Pose2,
        None => std::ptr::null_mut(),
    }
}
#[no_mangle]
pub unsafe extern "C" fn graph_edges_len(p: *const GraphHandle) -> u32 {
    (*p).model.edges.len() as u32
}
#[no_mangle]
pub unsafe extern "C" fn graph_edges_reserve(p: *mut GraphHandle, additional: u32) {
    (*p).model.edges.reserve(additional as usize);
}
#[no_mangle]
pub unsafe extern "C" fn graph_edges_push(p: *mut GraphHandle) -> *mut Edge {
    let m = &mut (*p).model.edges;
    m.push(Default::default());
    m.last_mut().unwrap() as *mut Edge
}
#[no_mangle]
pub unsafe extern "C" fn graph_edges_at(p: *mut GraphHandle, i: u32) -> *mut Edge {
    let m = &mut (*p).model.edges;
    &mut m[i as usize] as *mut Edge
}
/// Drops the last element; false when already empty.
#[no_mangle]
pub unsafe extern "C" fn graph_edges_pop(p: *mut GraphHandle) -> bool {
    (*p).model.edges.pop().is_some()
}
#[no_mangle]
pub unsafe extern "C" fn graph_edges_clear(p: *mut GraphHandle) {
    (*p).model.edges.clear();
}
#[no_mangle]
pub unsafe extern "C" fn graph_edges_truncate(p: *mut GraphHandle, len: u32) {
    (*p).model.edges.truncate(len as usize);
}
#[no_mangle]
pub unsafe extern "C" fn graph_has_prior(p: *const GraphHandle) -> bool {
    (*p).model.prior.is_some()
}
#[no_mangle]
pub unsafe extern "C" fn graph_make_prior(p: *mut GraphHandle) -> *mut Prior {
    let a = &mut (*p).model.prior;
    *a = Some(Default::default());
    a.as_mut().unwrap() as *mut Prior
}
#[no_mangle]
pub unsafe extern "C" fn graph_clear_prior(p: *mut GraphHandle) {
    (*p).model.prior = None;
}
#[no_mangle]
pub unsafe extern "C" fn graph_prior(p: *mut GraphHandle) -> *mut Prior {
    match &mut (*p).model.prior {
        Some(e) => e as *mut Prior,
        None => std::ptr::null_mut(),
    }
}
#[no_mangle]
pub unsafe extern "C" fn graph_edge_a(p: *const Edge) -> u32 {
    (*p).a.to_raw()
}
#[no_mangle]
pub unsafe extern "C" fn graph_edge_set_a(p: *mut Edge, v: u32) {
    (*p).a = arael::refs::Ref::from_raw(v);
}
#[no_mangle]
pub unsafe extern "C" fn graph_edge_b(p: *const Edge) -> u32 {
    (*p).b.to_raw()
}
#[no_mangle]
pub unsafe extern "C" fn graph_edge_set_b(p: *mut Edge, v: u32) {
    (*p).b = arael::refs::Ref::from_raw(v);
}
#[no_mangle]
pub unsafe extern "C" fn graph_edge_delta(p: *const Edge) -> CVec2F64 {
    (*p).delta.into()
}
#[no_mangle]
pub unsafe extern "C" fn graph_edge_set_delta(p: *mut Edge, v: CVec2F64) {
    (*p).delta = v.into();
}
#[no_mangle]
pub unsafe extern "C" fn graph_edge_dth(p: *const Edge) -> f64 {
    (*p).dth
}
#[no_mangle]
pub unsafe extern "C" fn graph_edge_set_dth(p: *mut Edge, v: f64) {
    (*p).dth = v;
}
#[no_mangle]
pub unsafe extern "C" fn graph_edge_wt(p: *const Edge) -> f64 {
    (*p).wt
}
#[no_mangle]
pub unsafe extern "C" fn graph_edge_set_wt(p: *mut Edge, v: f64) {
    (*p).wt = v;
}
#[no_mangle]
pub unsafe extern "C" fn graph_edge_wr(p: *const Edge) -> f64 {
    (*p).wr
}
#[no_mangle]
pub unsafe extern "C" fn graph_edge_set_wr(p: *mut Edge, v: f64) {
    (*p).wr = v;
}
#[no_mangle]
pub unsafe extern "C" fn graph_pose2_pos(p: *const Pose2) -> CVec2F64 {
    (*p).pos.value.into()
}
#[no_mangle]
pub unsafe extern "C" fn graph_pose2_set_pos(p: *mut Pose2, v: CVec2F64) {
    (*p).pos.value = v.into();
}
#[no_mangle]
pub unsafe extern "C" fn graph_pose2_pos_optimize(p: *const Pose2) -> bool {
    (*p).pos.optimize
}
#[no_mangle]
pub unsafe extern "C" fn graph_pose2_pos_set_optimize(p: *mut Pose2, v: bool) {
    (*p).pos.optimize = v;
}
#[no_mangle]
pub unsafe extern "C" fn graph_pose2_th(p: *const Pose2) -> f64 {
    (*p).th.value
}
#[no_mangle]
pub unsafe extern "C" fn graph_pose2_set_th(p: *mut Pose2, v: f64) {
    (*p).th.value = v;
}
#[no_mangle]
pub unsafe extern "C" fn graph_pose2_th_optimize(p: *const Pose2) -> bool {
    (*p).th.optimize
}
#[no_mangle]
pub unsafe extern "C" fn graph_pose2_th_set_optimize(p: *mut Pose2, v: bool) {
    (*p).th.optimize = v;
}
#[no_mangle]
pub unsafe extern "C" fn graph_prior_p(p: *const Prior) -> u32 {
    (*p).p.to_raw()
}
#[no_mangle]
pub unsafe extern "C" fn graph_prior_set_p(p: *mut Prior, v: u32) {
    (*p).p = arael::refs::Ref::from_raw(v);
}
#[no_mangle]
pub unsafe extern "C" fn graph_prior_pos(p: *const Prior) -> CVec2F64 {
    (*p).pos.into()
}
#[no_mangle]
pub unsafe extern "C" fn graph_prior_set_pos(p: *mut Prior, v: CVec2F64) {
    (*p).pos = v.into();
}
#[no_mangle]
pub unsafe extern "C" fn graph_prior_th(p: *const Prior) -> f64 {
    (*p).th
}
#[no_mangle]
pub unsafe extern "C" fn graph_prior_set_th(p: *mut Prior, v: f64) {
    (*p).th = v;
}
