# GENERATED by cargo-arael (vendored python support). Do not edit.
# arael Python g2o pose-graph file I/O, mirroring arael's src/g2o.rs:
# VERTEX_SE2 / EDGE_SE2 and VERTEX_SE3:QUAT / EDGE_SE3:QUAT. Unknown
# record types are skipped, vertex ids must be dense and ordered.
# Malformed records raise ValueError with the 1-based line number.

from decimal import Decimal

from .math import matrix3d, quaternd, vect2d, vect3d


def _fmt(v):
    """The shortest decimal that round-trips to v, positional
    notation (no exponent) -- byte-identical to the Rust writer."""
    r = repr(float(v))
    if "e" in r:
        return format(Decimal(r), "f")
    if r.endswith(".0"):
        return r[:-2]
    return r


class Pose2:
    """One 2D pose from a VERTEX_SE2 record."""

    def __init__(self, t, th):
        self.t = t if isinstance(t, vect2d) else vect2d(t)
        self.th = float(th)


class DeltaPose2:
    """One relative SE2 measurement from an EDGE_SE2 record: pose b
    seen from pose a's body frame. `info` is the information-matrix
    upper triangle in file order (I11 I12 I13 I22 I23 I33)."""

    def __init__(self, a, b, dt, dth, info):
        self.a = int(a)
        self.b = int(b)
        self.dt = dt if isinstance(dt, vect2d) else vect2d(dt)
        self.dth = float(dth)
        self.info = tuple(float(v) for v in info)
        if len(self.info) != 6:
            raise ValueError("EDGE_SE2 needs 6 information entries")

    def iso_sqrt_info(self):
        """(wt, wr) when the information matrix is diagonal with equal
        translation entries; None when it is anything else."""
        i11, i12, i13, i22, i23, i33 = self.info
        if (abs(i12) < 1e-9 and abs(i13) < 1e-9 and abs(i23) < 1e-9
                and abs(i11 - i22) < 1e-9):
            return i11 ** 0.5, i33 ** 0.5
        return None


class Dataset2:
    """A 2D pose graph: poses and the relative measurements between
    them."""

    def __init__(self):
        self.poses = []
        self.deltas = []

    @classmethod
    def parse(cls, text):
        """Parse a 2D pose graph from .g2o text."""
        ds = cls()
        for lineno, line in enumerate(text.splitlines(), 1):
            f = line.split()
            if not f:
                continue
            try:
                if f[0] == "VERTEX_SE2":
                    if int(f[1]) != len(ds.poses):
                        raise ValueError("vertex ids must be dense and ordered")
                    ds.poses.append(Pose2((float(f[2]), float(f[3])),
                                          float(f[4])))
                elif f[0] == "EDGE_SE2":
                    ds.deltas.append(DeltaPose2(
                        int(f[1]), int(f[2]), (float(f[3]), float(f[4])),
                        float(f[5]), [float(v) for v in f[6:12]]))
            except (IndexError, ValueError) as e:
                raise ValueError("g2o line %d: %s" % (lineno, e)) from None
        for d in ds.deltas:
            if d.a >= len(ds.poses) or d.b >= len(ds.poses):
                raise ValueError("measurement references pose %d / %d of %d"
                                 % (d.a, d.b, len(ds.poses)))
        return ds

    @classmethod
    def load(cls, path):
        """Read a 2D pose graph from a .g2o file."""
        with open(path, "r") as f:
            return cls.parse(f.read())

    def to_g2o(self):
        """Render the pose graph as .g2o text -- byte-identical to
        the Rust writer."""
        out = []
        for i, p in enumerate(self.poses):
            out.append("VERTEX_SE2 %d %s %s %s"
                       % (i, _fmt(p.t.x), _fmt(p.t.y), _fmt(p.th)))
        for d in self.deltas:
            row = ["EDGE_SE2 %d %d %s %s %s"
                   % (d.a, d.b, _fmt(d.dt.x), _fmt(d.dt.y), _fmt(d.dth))]
            row += [_fmt(v) for v in d.info]
            out.append(" ".join(row))
        return "".join(line + "\n" for line in out)

    def save(self, path):
        """Write the pose graph back out as .g2o."""
        with open(path, "w") as f:
            f.write(self.to_g2o())


def _unit_quat(qx, qy, qz, qw):
    """The file's qx qy qz qw, normalized (the same arithmetic as the
    Rust reader: scalar divided by n, vector scaled by 1/n)."""
    n = (qw * qw + (qx * qx + qy * qy + qz * qz)) ** 0.5
    if n < 1e-12:
        raise ValueError("zero-length quaternion")
    inv = 1.0 / n
    return quaternd(qw / n, (qx * inv, qy * inv, qz * inv))


class Pose3:
    """One 3D pose from a VERTEX_SE3:QUAT record; `q` is the
    orientation (unit quaternion, normalized on load)."""

    def __init__(self, t, q):
        self.t = t if isinstance(t, vect3d) else vect3d(t)
        self.q = q

    def rot(self):
        """The pose's rotation matrix."""
        return self.q.rotation_matrix()


class DeltaPose3:
    """One relative SE3 measurement from an EDGE_SE3:QUAT record: pose
    b seen from pose a's body frame. `info` is the full symmetric 6x6
    information matrix, rows ordered (x y z qx qy qz)."""

    def __init__(self, a, b, dt, dq, info):
        self.a = int(a)
        self.b = int(b)
        self.dt = dt if isinstance(dt, vect3d) else vect3d(dt)
        self.dq = dq
        self.info = tuple(tuple(float(v) for v in row) for row in info)

    def sqrt_info_upper(self):
        """Upper Cholesky factor u of the information matrix
        (info = u^T u), as a 6x6 tuple of tuples. Raises when the
        matrix is not positive definite -- that is a data error, not
        something to paper over."""
        a = self.info
        low = [[0.0] * 6 for _ in range(6)]
        for i in range(6):
            for j in range(i + 1):
                s = a[i][j] - sum(low[i][k] * low[j][k] for k in range(j))
                if i == j:
                    if s <= 0.0:
                        raise ValueError(
                            "information matrix not positive definite "
                            "(pivot %d = %g)" % (i, s))
                    low[i][j] = s ** 0.5
                else:
                    low[i][j] = s / low[j][j]
        return tuple(tuple(low[j][i] for j in range(6)) for i in range(6))

    def u_blocks(self):
        """The three 3x3 blocks of the upper-triangular sqrt-info
        factor [ u_tt u_tr ; 0 u_rr ]: (u_tt, u_tr, u_rr)."""
        u = self.sqrt_info_upper()

        def block(r0, c0):
            return matrix3d.from_elements(
                u[r0][c0], u[r0][c0 + 1], u[r0][c0 + 2],
                u[r0 + 1][c0], u[r0 + 1][c0 + 1], u[r0 + 1][c0 + 2],
                u[r0 + 2][c0], u[r0 + 2][c0 + 1], u[r0 + 2][c0 + 2])

        return block(0, 0), block(0, 3), block(3, 3)


class Dataset3:
    """A 3D pose graph: poses and the relative measurements between
    them."""

    def __init__(self):
        self.poses = []
        self.deltas = []

    @classmethod
    def parse(cls, text):
        """Parse a 3D pose graph from .g2o text."""
        ds = cls()
        for lineno, line in enumerate(text.splitlines(), 1):
            f = line.split()
            if not f:
                continue
            try:
                if f[0] == "VERTEX_SE3:QUAT":
                    # VERTEX_SE3:QUAT id x y z qx qy qz qw
                    if int(f[1]) != len(ds.poses):
                        raise ValueError("vertex ids must be dense and ordered")
                    ds.poses.append(Pose3(
                        (float(f[2]), float(f[3]), float(f[4])),
                        _unit_quat(float(f[5]), float(f[6]), float(f[7]),
                                   float(f[8]))))
                elif f[0] == "EDGE_SE3:QUAT":
                    # EDGE_SE3:QUAT a b dx dy dz qx qy qz qw then the
                    # 21 upper-triangular information entries,
                    # row-major, rows ordered (x y z qx qy qz).
                    vals = [float(v) for v in f[10:31]]
                    if len(vals) != 21:
                        raise ValueError(
                            "EDGE_SE3:QUAT needs 21 information entries")
                    info = [[0.0] * 6 for _ in range(6)]
                    k = 0
                    for i in range(6):
                        for j in range(i, 6):
                            info[i][j] = info[j][i] = vals[k]
                            k += 1
                    ds.deltas.append(DeltaPose3(
                        int(f[1]), int(f[2]),
                        (float(f[3]), float(f[4]), float(f[5])),
                        _unit_quat(float(f[6]), float(f[7]), float(f[8]),
                                   float(f[9])),
                        info))
            except (IndexError, ValueError) as e:
                raise ValueError("g2o line %d: %s" % (lineno, e)) from None
        for d in ds.deltas:
            if d.a >= len(ds.poses) or d.b >= len(ds.poses):
                raise ValueError("measurement references pose %d / %d of %d"
                                 % (d.a, d.b, len(ds.poses)))
        return ds

    @classmethod
    def load(cls, path):
        """Read a 3D pose graph from a .g2o file."""
        with open(path, "r") as f:
            return cls.parse(f.read())

    def to_g2o(self):
        """Render the pose graph as .g2o text -- byte-identical to
        the Rust writer."""
        out = []
        for i, p in enumerate(self.poses):
            out.append("VERTEX_SE3:QUAT %d %s %s %s %s %s %s %s"
                       % (i, _fmt(p.t.x), _fmt(p.t.y), _fmt(p.t.z),
                          _fmt(p.q.v.x), _fmt(p.q.v.y), _fmt(p.q.v.z),
                          _fmt(p.q.t)))
        for d in self.deltas:
            row = ["EDGE_SE3:QUAT %d %d %s %s %s %s %s %s %s"
                   % (d.a, d.b, _fmt(d.dt.x), _fmt(d.dt.y), _fmt(d.dt.z),
                      _fmt(d.dq.v.x), _fmt(d.dq.v.y), _fmt(d.dq.v.z),
                      _fmt(d.dq.t))]
            for i in range(6):
                for j in range(i, 6):
                    row.append(_fmt(d.info[i][j]))
            out.append(" ".join(row))
        return "".join(line + "\n" for line in out)

    def save(self, path):
        """Write the pose graph back out as .g2o."""
        with open(path, "w") as f:
            f.write(self.to_g2o())
