// GENERATED by cargo-arael from the `Path` model sidecar. Do not edit;
// regenerate with `cargo arael export` (check drift with `cargo arael check`).
#![allow(clippy::missing_safety_doc)]

use std::ffi::CString;
use std::os::raw::c_char;
use std::panic::{AssertUnwindSafe, catch_unwind};
use arael::covariance::{CovAssembly, CovMode, Covariance};
use arael::simple_lm::{
    LmConfig, LmProblem, LmSession, LmStatus, SparseFaer, SparseFaerOptions,
};
use slam2d_simple::{Frine, Landmark, Path, Pose, PosePair};

/// The opaque handle the C ABI hands out: the model, the error /
/// diagnostic text buffer `last_error` points into, and the
/// covariance assembly once requested.
pub struct PathHandle {
    model: Path,
    text: CString,
    cov: Option<CovAssembly>,
}

/// The Rust side of a solve result, boxed behind `CLmResult::detail`:
/// the full `LmResult` (report text, backend plan, per-step timing)
/// plus the buffer `path_result_report` renders into. Owned by
/// the caller; released with `path_result_free`.
pub struct ResultDetail {
    result: arael::simple_lm::LmResult<f32>,
    buf: CString,
}

macro_rules! c_vec2 {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub x: $t, pub y: $t }
        impl From<arael::vect::vect2<$t>> for $name {
            fn from(v: arael::vect::vect2<$t>) -> Self { Self { x: v.x, y: v.y } }
        }
        impl From<$name> for arael::vect::vect2<$t> {
            fn from(v: $name) -> Self { arael::vect::vect2::new(v.x, v.y) }
        }
    };
}
macro_rules! c_vec3 {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub x: $t, pub y: $t, pub z: $t }
        impl From<arael::vect::vect3<$t>> for $name {
            fn from(v: arael::vect::vect3<$t>) -> Self { Self { x: v.x, y: v.y, z: v.z } }
        }
        impl From<$name> for arael::vect::vect3<$t> {
            fn from(v: $name) -> Self { arael::vect::vect3::new(v.x, v.y, v.z) }
        }
    };
}
macro_rules! c_mat2 {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub m: [[$t; 2]; 2] }
        impl From<arael::matrix::matrix2<$t>> for $name {
            fn from(v: arael::matrix::matrix2<$t>) -> Self {
                Self { m: [[v.rows[0].x, v.rows[0].y], [v.rows[1].x, v.rows[1].y]] }
            }
        }
        impl From<$name> for arael::matrix::matrix2<$t> {
            fn from(v: $name) -> Self {
                arael::matrix::matrix2::from_elements(v.m[0][0], v.m[0][1], v.m[1][0], v.m[1][1])
            }
        }
    };
}
macro_rules! c_mat3 {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub m: [[$t; 3]; 3] }
        impl From<arael::matrix::matrix3<$t>> for $name {
            fn from(v: arael::matrix::matrix3<$t>) -> Self {
                Self { m: [
                    [v.rows[0].x, v.rows[0].y, v.rows[0].z],
                    [v.rows[1].x, v.rows[1].y, v.rows[1].z],
                    [v.rows[2].x, v.rows[2].y, v.rows[2].z],
                ] }
            }
        }
        impl From<$name> for arael::matrix::matrix3<$t> {
            fn from(v: $name) -> Self { arael::matrix::matrix3::from_array(v.m) }
        }
    };
}
macro_rules! c_quat {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub t: $t, pub x: $t, pub y: $t, pub z: $t }
        impl From<arael::quatern::quatern<$t>> for $name {
            fn from(q: arael::quatern::quatern<$t>) -> Self {
                Self { t: q.t, x: q.v.x, y: q.v.y, z: q.v.z }
            }
        }
        impl From<$name> for arael::quatern::quatern<$t> {
            fn from(q: $name) -> Self {
                arael::quatern::quatern::new(q.t, arael::vect::vect3::new(q.x, q.y, q.z))
            }
        }
    };
}
c_vec2!(CVec2F32, f32);
c_vec2!(CVec2F64, f64);
c_vec3!(CVec3F32, f32);
c_vec3!(CVec3F64, f64);
c_mat2!(CMat2F32, f32);
c_mat2!(CMat2F64, f64);
c_mat3!(CMat3F32, f32);
c_mat3!(CMat3F64, f64);
c_quat!(CQuatF32, f32);
c_quat!(CQuatF64, f64);

fn status_code(s: &LmStatus) -> i32 {
    match s {
        LmStatus::Converged => 0,
        LmStatus::CostThreshold => 1,
        LmStatus::MaxIterations => 2,
        LmStatus::GradientTolerance => 3,
        LmStatus::ParameterTolerance => 4,
        LmStatus::PredictedReduction => 5,
        LmStatus::LambdaCeiling => 6,
        LmStatus::DriverTerminated => 7,
        LmStatus::ObserverTerminated => 8,
        LmStatus::TimeLimit => 9,
        LmStatus::RetryBudgetExhausted => 10,
        LmStatus::Aborted => 11,
    }
}

fn set_text(h: &mut PathHandle, msg: &str) {
    h.text = CString::new(msg.replace('\0', " ")).unwrap();
}

fn panic_text(p: Box<dyn std::any::Any + Send>) -> String {
    if let Some(s) = p.downcast_ref::<&str>() {
        (*s).to_string()
    } else if let Some(s) = p.downcast_ref::<String>() {
        s.clone()
    } else {
        "panic".to_string()
    }
}

/// C mirror of `arael::option<T>` ({has, value}; layouts must match).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct COptF {
    pub has: bool,
    pub v: f32,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct COptSeconds {
    pub has: bool,
    pub v: f64,
}

fn copt(o: Option<f32>) -> COptF {
    match o {
        Some(v) => COptF { has: true, v },
        None => COptF { has: false, v: 0.0 },
    }
}

fn opt_of(c: COptF) -> Option<f32> {
    c.has.then_some(c.v)
}

/// One damped attempt, as the observer callback sees it. Field order
/// is C ABI. `params` points at the CURRENT parameter vector for this
/// attempt; valid only during the callback.
#[repr(C)]
pub struct CLmIter {
    pub iter: u32,
    pub inner: u32,
    pub accepted: bool,
    pub factorization_failed: bool,
    pub cost: f32,
    pub new_cost: f32,
    pub lambda: f32,
    pub accepted_total: u32,
    pub params: *const f32,
    pub params_len: u32,
}

/// The C observer: called once per damped attempt; return false to
/// stop the solve (status ObserverTerminated).
type CObserverFn = extern "C" fn(*mut core::ffi::c_void, *const CLmIter) -> bool;

#[derive(Clone)]
struct CObserver {
    f: CObserverFn,
    user: *mut core::ffi::c_void,
}

impl arael::simple_lm::LmObserver<f32> for CObserver {
    fn on_iteration(
        &mut self,
        it: &arael::simple_lm::LmIter<'_, f32>,
    ) -> std::ops::ControlFlow<()> {
        let c = CLmIter {
            iter: it.iter as u32,
            inner: it.inner as u32,
            accepted: it.accepted,
            factorization_failed: it.factorization_failed,
            cost: it.cost,
            new_cost: it.new_cost,
            lambda: it.lambda,
            accepted_total: it.accepted_total as u32,
            params: it.params.as_ptr(),
            params_len: it.params.len() as u32,
        };
        if (self.f)(self.user, &c) {
            std::ops::ControlFlow::Continue(())
        } else {
            std::ops::ControlFlow::Break(())
        }
    }
}

/// The solver config as REAL values: constructed by
/// path_lm_config (which copies them out of the actual Rust
/// LmConfig preset), edited freely, passed back whole. The preset tag
/// stays the base for the Rust fields this struct does not expose
/// (lambda driver). Field order is C ABI.
#[repr(C)]
pub struct CLmConfig {
    pub preset: u32,
    pub max_iters: u32,
    pub min_iters: u32,
    pub patience: u32,
    pub num_threads: u32,
    pub verbose: bool,
    pub gather_timing: bool,
    pub abs_precision: f32,
    pub rel_precision: f32,
    pub initial_lambda: f32,
    pub cost_threshold: f32,
    pub lambda_floor: f32,
    pub gradient_tolerance: COptF,
    pub parameter_tolerance: COptF,
    pub predicted_reduction_tolerance: COptF,
    pub min_diagonal: COptF,
    pub time_limit_seconds: COptSeconds,
    pub observer: Option<CObserverFn>,
    pub observer_user: *mut core::ffi::c_void,
}

/// The sparse backend's options as plain data: constructed by
/// path_sparse_options (which copies the actual Rust defaults),
/// edited freely, passed to path_solve_sparse (null there means
/// these defaults). Field order is C ABI. Not exposed: the
/// marginalize range list (the model's own marginalize hint covers
/// it) and the iterative Schur routes.
#[repr(C)]
pub struct CSparseOptions {
    /// SchurPolicy: 0 Auto, 1 Force, 2 Never.
    pub schur: u32,
    /// FaerOrdering: 0 Auto, 1 Amd, 2 MarginalizeFirst, 3 Natural,
    /// 4 NestedDissection.
    pub ordering: u32,
    /// EnvelopeMode: 0 Auto, 1 Always, 2 Never.
    pub envelope: u32,
    /// Envelope panel width; 0 picks it automatically.
    pub envelope_panel_width: u32,
    pub supernodal: bool,
    pub narrow_band: bool,
    /// SchurPolicy::Auto tuning: the reduction must beat the whole
    /// system by this flop factor to be taken...
    pub flop_margin: f64,
    /// ...and below this cheap ratio it is taken without the exact
    /// pricing.
    pub obvious_flop_ratio: f64,
}

impl CSparseOptions {
    fn to_options(&self) -> Result<SparseFaerOptions, String> {
        use arael::simple_lm::{EnvelopeMode, FaerOrdering, SchurPolicy};
        let policy = match self.schur {
            0 => SchurPolicy::Auto {
                flop_margin: self.flop_margin,
                obvious_flop_ratio: self.obvious_flop_ratio,
            },
            1 => SchurPolicy::Force,
            2 => SchurPolicy::Never,
            t => return Err(format!("unknown schur policy tag {t}")),
        };
        let ordering = match self.ordering {
            0 => FaerOrdering::Auto,
            1 => FaerOrdering::Amd,
            2 => FaerOrdering::MarginalizeFirst,
            3 => FaerOrdering::Natural,
            4 => FaerOrdering::NestedDissection,
            t => return Err(format!("unknown ordering tag {t}")),
        };
        let envelope = match self.envelope {
            0 => EnvelopeMode::Auto,
            1 => EnvelopeMode::Always,
            2 => EnvelopeMode::Never,
            t => return Err(format!("unknown envelope mode tag {t}")),
        };
        let width = self.envelope_panel_width;
        Ok(SparseFaerOptions::auto()
            .with_policy(policy)
            .with_ordering(ordering)
            .with_envelope_schur(envelope)
            .with_envelope_panel_width((width > 0).then_some(width as usize))
            .with_supernodal(self.supernodal)
            .with_narrow_band(self.narrow_band))
    }
}

/// Fill `out` with the sparse backend's actual Rust defaults.
#[no_mangle]
pub unsafe extern "C" fn path_sparse_options(out: *mut CSparseOptions) {
    use arael::simple_lm::{EnvelopeMode, FaerOrdering, SchurPolicy};
    let d = SparseFaerOptions::default();
    let (flop_margin, obvious_flop_ratio) = match d.policy {
        SchurPolicy::Auto { flop_margin, obvious_flop_ratio } => {
            (flop_margin, obvious_flop_ratio)
        }
        _ => (0.0, 0.0),
    };
    *out = CSparseOptions {
        schur: match d.policy {
            SchurPolicy::Auto { .. } => 0,
            SchurPolicy::Force => 1,
            SchurPolicy::Never => 2,
        },
        ordering: match d.ordering {
            FaerOrdering::Auto => 0,
            FaerOrdering::Amd => 1,
            FaerOrdering::MarginalizeFirst => 2,
            FaerOrdering::Natural => 3,
            FaerOrdering::NestedDissection => 4,
        },
        envelope: match d.envelope {
            EnvelopeMode::Auto => 0,
            EnvelopeMode::Always => 1,
            EnvelopeMode::Never => 2,
        },
        envelope_panel_width: d.envelope_panel_width.unwrap_or(0) as u32,
        supernodal: d.supernodal,
        narrow_band: d.narrow_band,
        flop_margin,
        obvious_flop_ratio,
    };
}

fn preset_config(preset: u32) -> LmConfig<f32> {
    match preset {
        1 => LmConfig::conservative(),
        2 => LmConfig::well_conditioned(),
        3 => LmConfig::ill_conditioned(),
        _ => LmConfig::default(),
    }
}

/// Fill `out` with the preset's actual Rust values (0 = defaults,
/// 1 = conservative, 2 = well_conditioned, 3 = ill_conditioned).
#[no_mangle]
pub unsafe extern "C" fn path_lm_config(preset: u32, out: *mut CLmConfig) {
    let c = preset_config(preset);
    *out = CLmConfig {
        preset,
        max_iters: c.max_iters as u32,
        min_iters: c.min_iters as u32,
        patience: c.patience as u32,
        num_threads: c.num_threads as u32,
        verbose: c.verbose,
        gather_timing: c.gather_timing,
        abs_precision: c.abs_precision,
        rel_precision: c.rel_precision,
        initial_lambda: c.initial_lambda,
        cost_threshold: c.cost_threshold,
        lambda_floor: c.lambda_floor,
        gradient_tolerance: copt(c.gradient_tolerance),
        parameter_tolerance: copt(c.parameter_tolerance),
        predicted_reduction_tolerance: copt(c.predicted_reduction_tolerance),
        min_diagonal: copt(c.min_diagonal),
        time_limit_seconds: match c.time_limit {
            Some(d) => COptSeconds { has: true, v: d.as_secs_f64() },
            None => COptSeconds { has: false, v: 0.0 },
        },
        observer: None,
        observer_user: std::ptr::null_mut(),
    };
}

impl CLmConfig {
    fn to_config(&self) -> LmConfig<f32> {
        let mut c = preset_config(self.preset);
        c.max_iters = self.max_iters as usize;
        c.min_iters = self.min_iters as usize;
        c.patience = self.patience as usize;
        c.num_threads = self.num_threads as usize;
        c.verbose = self.verbose;
        c.gather_timing = self.gather_timing;
        c.abs_precision = self.abs_precision;
        c.rel_precision = self.rel_precision;
        c.initial_lambda = self.initial_lambda;
        c.cost_threshold = self.cost_threshold;
        c.lambda_floor = self.lambda_floor;
        c.gradient_tolerance = opt_of(self.gradient_tolerance);
        c.parameter_tolerance = opt_of(self.parameter_tolerance);
        c.predicted_reduction_tolerance = opt_of(self.predicted_reduction_tolerance);
        c.min_diagonal = opt_of(self.min_diagonal);
        c.time_limit = self.time_limit_seconds.has.then(|| {
            std::time::Duration::from_secs_f64(self.time_limit_seconds.v)
        });
        if let Some(f) = self.observer {
            c = c.with_observer(CObserver { f, user: self.observer_user });
        }
        c
    }
}

/// LmTiming mirror: per-phase wall-clock seconds plus call counts.
/// The Rust per-step records (LmTiming::steps) stay Rust-side.
#[repr(C)]
#[derive(Default, Clone, Copy)]
pub struct CLmTiming {
    pub total: f64,
    pub assembly: f64,
    pub first_assembly: f64,
    pub analysis: f64,
    pub linear_solve: f64,
    pub first_linear_solve: f64,
    pub cost_eval: f64,
    pub first_cost_eval: f64,
    pub advance: f64,
    pub first_advance: f64,
    pub assembly_count: u32,
    pub analysis_count: u32,
    pub linear_solve_count: u32,
    pub cost_eval_count: u32,
    pub advance_count: u32,
}

#[repr(C)]
pub struct CLmResult {
    pub start_cost: f32,
    pub end_cost: f32,
    pub iterations: u32,
    pub accepted_iterations: u32,
    pub status: i32,
    pub final_lambda: f32,
    /// Valid iff has_timing (config.gather_timing was set).
    pub timing: CLmTiming,
    pub has_timing: bool,
    /// The full Rust result (render it with path_result_report,
    /// read its plan with path_result_plan). Owned by the caller:
    /// release with path_result_free. On a failed solve it holds
    /// the partial result when the solver produced one, else null.
    pub detail: *mut ResultDetail,
}

/// {has, v} mirrors of `arael::option<T>` for the plan's optional
/// statistics (layouts must match the C++ side).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct COptDouble {
    pub has: bool,
    pub v: f64,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct COptU32 {
    pub has: bool,
    pub v: u32,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct COptI32 {
    pub has: bool,
    pub v: i32,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct CRouteFlops {
    pub reduced: f64,
    pub full: f64,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct COptRouteFlops {
    pub has: bool,
    pub v: CRouteFlops,
}

/// Mirror of arael's SchurPlan: what the sparse backend decided.
/// Field order is C ABI and follows the Rust struct.
#[repr(C)]
pub struct CSchurPlan {
    pub reduced: bool,
    pub eliminated_blocks: u32,
    pub eliminated_params: u32,
    pub kept_params: u32,
    pub fill_ratio: COptDouble,
    pub route_flops: COptRouteFlops,
    pub cg_iterations: COptU32,
    pub flop_ratio: COptDouble,
    /// ReducedOrdering: 0 NaturalBanded, 1 NaturalDense, 2 Amd, 3 Nd.
    pub ordering: COptI32,
    pub kept_bandwidth: u32,
    pub envelope: bool,
}

unsafe fn fill_plan(out: *mut CSchurPlan, p: &arael::simple_lm::SchurPlan) {
    use arael::simple_lm::ReducedOrdering;
    let od = |o: Option<f64>| match o {
        Some(v) => COptDouble { has: true, v },
        None => COptDouble { has: false, v: 0.0 },
    };
    *out = CSchurPlan {
        reduced: p.reduced,
        eliminated_blocks: p.eliminated_blocks as u32,
        eliminated_params: p.eliminated_params as u32,
        kept_params: p.kept_params as u32,
        fill_ratio: od(p.fill_ratio),
        route_flops: match p.route_flops {
            Some((reduced, full)) => COptRouteFlops {
                has: true,
                v: CRouteFlops { reduced, full },
            },
            None => COptRouteFlops {
                has: false,
                v: CRouteFlops { reduced: 0.0, full: 0.0 },
            },
        },
        cg_iterations: match p.cg_iterations {
            Some(n) => COptU32 { has: true, v: n as u32 },
            None => COptU32 { has: false, v: 0 },
        },
        flop_ratio: od(p.flop_ratio),
        ordering: match p.ordering {
            Some(o) => COptI32 {
                has: true,
                v: match o {
                    ReducedOrdering::NaturalBanded => 0,
                    ReducedOrdering::NaturalDense => 1,
                    ReducedOrdering::Amd => 2,
                    ReducedOrdering::Nd => 3,
                },
            },
            None => COptI32 { has: false, v: 0 },
        },
        kept_bandwidth: p.kept_bandwidth as u32,
        envelope: p.envelope,
    };
}

unsafe fn zero_result(out: *mut CLmResult) {
    *out = CLmResult {
        start_cost: 0.0, end_cost: 0.0, iterations: 0,
        accepted_iterations: 0, status: -1, final_lambda: 0.0,
        timing: CLmTiming::default(), has_timing: false,
        detail: std::ptr::null_mut(),
    };
}

unsafe fn fill_result(out: *mut CLmResult, r: &arael::simple_lm::LmResult<f32>) -> i32 {
    let code = status_code(&r.status);
    let (timing, has_timing) = match &r.timing {
        Some(t) => (CLmTiming {
            total: t.total.as_secs_f64(),
            assembly: t.assembly.as_secs_f64(),
            first_assembly: t.first_assembly.as_secs_f64(),
            analysis: t.analysis.as_secs_f64(),
            linear_solve: t.linear_solve.as_secs_f64(),
            first_linear_solve: t.first_linear_solve.as_secs_f64(),
            cost_eval: t.cost_eval.as_secs_f64(),
            first_cost_eval: t.first_cost_eval.as_secs_f64(),
            advance: t.advance.as_secs_f64(),
            first_advance: t.first_advance.as_secs_f64(),
            assembly_count: t.assembly_count as u32,
            analysis_count: t.analysis_count as u32,
            linear_solve_count: t.linear_solve_count as u32,
            cost_eval_count: t.cost_eval_count as u32,
            advance_count: t.advance_count as u32,
        }, true),
        None => (CLmTiming::default(), false),
    };
    *out = CLmResult {
        start_cost: r.start_cost,
        end_cost: r.end_cost,
        iterations: r.iterations as u32,
        accepted_iterations: r.accepted_iterations as u32,
        status: code,
        final_lambda: r.final_lambda,
        timing,
        has_timing,
        detail: std::ptr::null_mut(),
    };
    code
}

fn boxed(r: arael::simple_lm::LmResult<f32>) -> *mut ResultDetail {
    Box::into_raw(Box::new(ResultDetail { result: r, buf: CString::default() }))
}

#[no_mangle]
pub extern "C" fn path_new() -> *mut PathHandle {
    Box::into_raw(Box::new(PathHandle {
        model: Default::default(),
        text: CString::default(),
        cov: None,
    }))
}

#[no_mangle]
pub unsafe extern "C" fn path_free(h: *mut PathHandle) {
    if !h.is_null() {
        drop(Box::from_raw(h));
    }
}

#[no_mangle]
pub unsafe extern "C" fn path_last_error(h: *const PathHandle) -> *const c_char {
    (*h).text.as_ptr()
}

/// Text report of the result behind `d` (status, cost, iterations,
/// damping, plus the timing breakdown and the backend's plan when it
/// has them). `pretty` adds colour and box-drawing glyphs. The
/// pointer is valid until the next report call on the same result or
/// path_result_free.
#[no_mangle]
pub unsafe extern "C" fn path_result_report(d: *mut ResultDetail, pretty: bool) -> *const c_char {
    let dd = &mut *d;
    let text = if pretty { dd.result.pretty_report() } else { dd.result.report() };
    dd.buf = CString::new(text.replace('\0', " ")).unwrap_or_default();
    dd.buf.as_ptr()
}

/// The sparse backend's plan for the result behind `d`. Returns false
/// with `out` untouched when the solve carried none (dense and band
/// solves).
#[no_mangle]
pub unsafe extern "C" fn path_result_plan(d: *const ResultDetail, out: *mut CSchurPlan) -> bool {
    match &(*d).result.solver {
        Some(arael::simple_lm::SolverReport::Schur(p)) => {
            fill_plan(out, p);
            true
        }
        _ => false,
    }
}

/// Release the Rust result behind a CLmResult. Null is fine.
#[no_mangle]
pub unsafe extern "C" fn path_result_free(d: *mut ResultDetail) {
    if !d.is_null() {
        drop(Box::from_raw(d));
    }
}

/// Drop arael log messages above `level` (0 Off, 1 Error, 2 Warn,
/// 3 Info; Info -- everything -- is the default). Process-wide: all
/// models and roots share it.
#[no_mangle]
pub extern "C" fn path_set_log_level(level: u32) {
    arael::log::set_level(match level {
        0 => arael::log::Level::Off,
        1 => arael::log::Level::Error,
        2 => arael::log::Level::Warn,
        _ => arael::log::Level::Info,
    });
}

/// Empty string when the model is clean, the Diagnostic text otherwise.
#[no_mangle]
pub unsafe extern "C" fn path_validate(h: *mut PathHandle) -> *const c_char {
    let hh = &mut *h;
    let text = match catch_unwind(AssertUnwindSafe(|| {
        let d = hh.model.validate();
        if d.is_clean() { String::new() } else { d.to_string() }
    })) {
        Ok(t) => t,
        Err(p) => panic_text(p),
    };
    set_text(hh, &text);
    hh.text.as_ptr()
}

/// Returns the status code (>= 0: LmStatus; -1: solve failure; -2:
/// panic). Failure text via path_last_error. On success (and on
/// a failure that got past its first assembly, where `out` carries
/// the partial result) `out.detail` owns the full Rust result --
/// release it with path_result_free.
#[no_mangle]
pub unsafe extern "C" fn path_solve_dense(
    h: *mut PathHandle,
    cfg: *const CLmConfig,
    out: *mut CLmResult,
) -> i32 {
    let hh = &mut *h;
    let c = (*cfg).to_config();
    zero_result(out);
    match catch_unwind(AssertUnwindSafe(|| hh.model.solve_dense(&c))) {
        Ok(Ok(r)) => {
            let code = fill_result(out, &r);
            (*out).detail = boxed(r);
            set_text(hh, "");
            code
        }
        Ok(Err(f)) => {
            set_text(hh, &f.to_string());
            if let Some(p) = f.partial {
                fill_result(out, &p);
                (*out).status = -1;
                (*out).detail = boxed(*p);
            }
            -1
        }
        Err(p) => {
            let msg = panic_text(p);
            set_text(hh, &msg);
            (*out).status = -2;
            -2
        }
    }
}

/// As path_solve_dense, with the sparse backend. `opts` selects
/// its route (ordering, Schur policy, envelope); null means the
/// defaults (path_sparse_options shows them).
#[no_mangle]
pub unsafe extern "C" fn path_solve_sparse(
    h: *mut PathHandle,
    cfg: *const CLmConfig,
    opts: *const CSparseOptions,
    out: *mut CLmResult,
) -> i32 {
    let hh = &mut *h;
    let c = (*cfg).to_config();
    zero_result(out);
    let solver = if opts.is_null() {
        None
    } else {
        match (*opts).to_options() {
            Ok(o) => Some(SparseFaer::<f32>::from_options(&o)),
            Err(e) => {
                set_text(hh, &e);
                return -1;
            }
        }
    };
    match catch_unwind(AssertUnwindSafe(|| match solver {
        Some(mut s) => hh.model.solve_with(&mut s, &c),
        None => hh.model.solve_sparse(&c),
    })) {
        Ok(Ok(r)) => {
            let code = fill_result(out, &r);
            (*out).detail = boxed(r);
            set_text(hh, "");
            code
        }
        Ok(Err(f)) => {
            set_text(hh, &f.to_string());
            if let Some(p) = f.partial {
                fill_result(out, &p);
                (*out).status = -1;
                (*out).detail = boxed(*p);
            }
            -1
        }
        Err(p) => {
            let msg = panic_text(p);
            set_text(hh, &msg);
            (*out).status = -2;
            -2
        }
    }
}

/// A warm-reuse session over the sparse backend (Rust's LmSession):
/// keeps the analysis -- pattern, ordering, symbolic factorization,
/// Schur plan -- across solves, so only the first pays for it. Warm
/// solves are bit-identical to cold ones. A parameter-count change
/// re-analyzes by itself; path_session_invalidate covers a
/// structural change at the same count (solving warm through one is
/// undefined).
pub struct PathSession {
    session: LmSession<f32, SparseFaer<f32>>,
}

/// New session; `opts` as in path_solve_sparse (null =
/// defaults). Returns null when the options are invalid.
#[no_mangle]
pub unsafe extern "C" fn path_session_new(
    opts: *const CSparseOptions,
) -> *mut PathSession {
    let solver = if opts.is_null() {
        SparseFaer::<f32>::new()
    } else {
        match (*opts).to_options() {
            Ok(o) => SparseFaer::<f32>::from_options(&o),
            Err(_) => return std::ptr::null_mut(),
        }
    };
    Box::into_raw(Box::new(PathSession {
        session: LmSession::new(solver),
    }))
}

#[no_mangle]
pub unsafe extern "C" fn path_session_free(s: *mut PathSession) {
    if !s.is_null() {
        drop(Box::from_raw(s));
    }
}

/// Drop the learned structure; the next solve runs cold.
#[no_mangle]
pub unsafe extern "C" fn path_session_invalidate(s: *mut PathSession) {
    (*s).session.invalidate();
}

/// As path_solve_sparse, through the session's cached analysis.
/// Error text lands on the model handle (path_last_error).
#[no_mangle]
pub unsafe extern "C" fn path_session_solve(
    s: *mut PathSession,
    h: *mut PathHandle,
    cfg: *const CLmConfig,
    out: *mut CLmResult,
) -> i32 {
    let ss = &mut *s;
    let hh = &mut *h;
    let c = (*cfg).to_config();
    zero_result(out);
    match catch_unwind(AssertUnwindSafe(|| ss.session.solve(&mut hh.model, &c))) {
        Ok(Ok(r)) => {
            let code = fill_result(out, &r);
            (*out).detail = boxed(r);
            set_text(hh, "");
            code
        }
        Ok(Err(f)) => {
            set_text(hh, &f.to_string());
            if let Some(p) = f.partial {
                fill_result(out, &p);
                (*out).status = -1;
                (*out).detail = boxed(*p);
            }
            -1
        }
        Err(p) => {
            let msg = panic_text(p);
            set_text(hh, &msg);
            (*out).status = -2;
            -2
        }
    }
}

/// Band Cholesky solve; `kd` is the Hessian half-bandwidth in scalar
/// parameters. Returns the status code (>= 0: LmStatus; -1: solve
/// failure; -2: panic). Failure text via path_last_error;
/// `out.detail` as in the other solves.
#[no_mangle]
pub unsafe extern "C" fn path_solve_band(
    h: *mut PathHandle,
    kd: u32,
    cfg: *const CLmConfig,
    out: *mut CLmResult,
) -> i32 {
    let hh = &mut *h;
    let c = (*cfg).to_config();
    zero_result(out);
    match catch_unwind(AssertUnwindSafe(|| {
        let mut x0 = Vec::new();
        hh.model.serialize32(&mut x0);
        arael::simple_lm::solve_band_f32(&x0, kd as usize, &mut hh.model, &c).map(|r| {
            hh.model.deserialize32(&r.x);
            r
        })
    })) {
        Ok(Ok(r)) => {
            let code = fill_result(out, &r);
            (*out).detail = boxed(r);
            set_text(hh, "");
            code
        }
        Ok(Err(f)) => {
            set_text(hh, &f.to_string());
            if let Some(p) = f.partial {
                fill_result(out, &p);
                (*out).status = -1;
                (*out).detail = boxed(*p);
            }
            -1
        }
        Err(p) => {
            let msg = panic_text(p);
            set_text(hh, &msg);
            (*out).status = -2;
            -2
        }
    }
}

/// Total cost at the current parameter values (evaluated at the
/// model's precision, returned as f64).
#[no_mangle]
pub unsafe extern "C" fn path_cost(h: *mut PathHandle) -> f64 {
    let m = &mut (*h).model;
    let mut params = Vec::new();
    m.serialize32(&mut params);
    m.calc_cost(&params) as f64
}

/// mode: 0 = PerQuery, 1 = AllMarginals, 2 = TriDiagonal. Returns 0,
/// -1 (error, text via path_last_error), -2 (panic).
#[no_mangle]
pub unsafe extern "C" fn path_assemble_covariance(h: *mut PathHandle, mode: u32) -> i32 {
    let hh = &mut *h;
    let m = match mode {
        0 => CovMode::PerQuery,
        2 => CovMode::TriDiagonal,
        _ => CovMode::AllMarginals,
    };
    hh.cov = None;
    match catch_unwind(AssertUnwindSafe(|| hh.model.assemble_covariance(m))) {
        Ok(Ok(c)) => {
            hh.cov = Some(c);
            set_text(hh, "");
            0
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p) => {
            let msg = panic_text(p);
            set_text(hh, &msg);
            -2
        }
    }
}

/// Row-major dim x dim marginal covariance (f64) of one `Landmark`; returns
/// dim, or -1 (error) / -2 (panic) / -3 (no assembly or buffer too
/// small), text via path_last_error.
#[no_mangle]
pub unsafe extern "C" fn path_landmark_marginal_cov(
    h: *mut PathHandle,
    p: *const Landmark,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "marginal_cov: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.marginal_cov(&*p))) {
        Ok(Ok(m)) => {
            let dim = m.nrows();
            if (dim * dim) as u32 > cap {
                set_text(hh, "marginal_cov: buffer too small");
                return -3;
            }
            for r in 0..dim {
                for c in 0..dim {
                    *out.add(r * dim + c) = m[(r, c)];
                }
            }
            dim as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}
/// Row-major dim x dim conditional covariance (f64) of one `Landmark`
/// (all other parameters held fixed); returns dim, or -1 (error) /
/// -2 (panic) / -3 (no assembly or buffer too small), text via
/// path_last_error.
#[no_mangle]
pub unsafe extern "C" fn path_landmark_conditional_cov(
    h: *mut PathHandle,
    p: *const Landmark,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "conditional_cov: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.conditional_cov(&*p))) {
        Ok(Ok(m)) => {
            let dim = m.nrows();
            if (dim * dim) as u32 > cap {
                set_text(hh, "conditional_cov: buffer too small");
                return -3;
            }
            for r in 0..dim {
                for c in 0..dim {
                    *out.add(r * dim + c) = m[(r, c)];
                }
            }
            dim as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}
/// Per-parameter standard deviations (sqrt of the marginal diagonal)
/// of one `Landmark`; returns the count, or -1 (error) / -2 (panic) / -3
/// (no assembly or buffer too small), text via path_last_error.
/// Works on every CovMode, including TriDiagonal.
#[no_mangle]
pub unsafe extern "C" fn path_landmark_std_dev(
    h: *mut PathHandle,
    p: *const Landmark,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "std_dev: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.std_dev(&*p))) {
        Ok(Ok(sd)) => {
            if sd.len() as u32 > cap {
                set_text(hh, "std_dev: buffer too small");
                return -3;
            }
            for (i, v) in sd.iter().enumerate() {
                *out.add(i) = *v;
            }
            sd.len() as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}

/// Row-major dim x dim marginal covariance (f64) of one `Pose`; returns
/// dim, or -1 (error) / -2 (panic) / -3 (no assembly or buffer too
/// small), text via path_last_error.
#[no_mangle]
pub unsafe extern "C" fn path_pose_marginal_cov(
    h: *mut PathHandle,
    p: *const Pose,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "marginal_cov: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.marginal_cov(&*p))) {
        Ok(Ok(m)) => {
            let dim = m.nrows();
            if (dim * dim) as u32 > cap {
                set_text(hh, "marginal_cov: buffer too small");
                return -3;
            }
            for r in 0..dim {
                for c in 0..dim {
                    *out.add(r * dim + c) = m[(r, c)];
                }
            }
            dim as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}
/// Row-major dim x dim conditional covariance (f64) of one `Pose`
/// (all other parameters held fixed); returns dim, or -1 (error) /
/// -2 (panic) / -3 (no assembly or buffer too small), text via
/// path_last_error.
#[no_mangle]
pub unsafe extern "C" fn path_pose_conditional_cov(
    h: *mut PathHandle,
    p: *const Pose,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "conditional_cov: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.conditional_cov(&*p))) {
        Ok(Ok(m)) => {
            let dim = m.nrows();
            if (dim * dim) as u32 > cap {
                set_text(hh, "conditional_cov: buffer too small");
                return -3;
            }
            for r in 0..dim {
                for c in 0..dim {
                    *out.add(r * dim + c) = m[(r, c)];
                }
            }
            dim as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}
/// Per-parameter standard deviations (sqrt of the marginal diagonal)
/// of one `Pose`; returns the count, or -1 (error) / -2 (panic) / -3
/// (no assembly or buffer too small), text via path_last_error.
/// Works on every CovMode, including TriDiagonal.
#[no_mangle]
pub unsafe extern "C" fn path_pose_std_dev(
    h: *mut PathHandle,
    p: *const Pose,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "std_dev: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.std_dev(&*p))) {
        Ok(Ok(sd)) => {
            if sd.len() as u32 > cap {
                set_text(hh, "std_dev: buffer too small");
                return -3;
            }
            for (i, v) in sd.iter().enumerate() {
                *out.add(i) = *v;
            }
            sd.len() as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}

/// Row-major pa x pb cross-covariance (f64) between a `Landmark` and a
/// `Landmark`; returns the row count, or -1 (error) / -2 (panic) / -3 (no
/// assembly or buffer too small), text via path_last_error.
#[no_mangle]
pub unsafe extern "C" fn path_landmark_landmark_cross_cov(
    h: *mut PathHandle,
    a: *const Landmark,
    b: *const Landmark,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "cross_cov: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.cross_cov(&*a, &*b))) {
        Ok(Ok(m)) => {
            let (rows, cols) = (m.nrows(), m.ncols());
            if (rows * cols) as u32 > cap {
                set_text(hh, "cross_cov: buffer too small");
                return -3;
            }
            for r in 0..rows {
                for c in 0..cols {
                    *out.add(r * cols + c) = m[(r, c)];
                }
            }
            rows as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}

/// Row-major pa x pb cross-covariance (f64) between a `Landmark` and a
/// `Pose`; returns the row count, or -1 (error) / -2 (panic) / -3 (no
/// assembly or buffer too small), text via path_last_error.
#[no_mangle]
pub unsafe extern "C" fn path_landmark_pose_cross_cov(
    h: *mut PathHandle,
    a: *const Landmark,
    b: *const Pose,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "cross_cov: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.cross_cov(&*a, &*b))) {
        Ok(Ok(m)) => {
            let (rows, cols) = (m.nrows(), m.ncols());
            if (rows * cols) as u32 > cap {
                set_text(hh, "cross_cov: buffer too small");
                return -3;
            }
            for r in 0..rows {
                for c in 0..cols {
                    *out.add(r * cols + c) = m[(r, c)];
                }
            }
            rows as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}

/// Row-major pa x pb cross-covariance (f64) between a `Pose` and a
/// `Landmark`; returns the row count, or -1 (error) / -2 (panic) / -3 (no
/// assembly or buffer too small), text via path_last_error.
#[no_mangle]
pub unsafe extern "C" fn path_pose_landmark_cross_cov(
    h: *mut PathHandle,
    a: *const Pose,
    b: *const Landmark,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "cross_cov: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.cross_cov(&*a, &*b))) {
        Ok(Ok(m)) => {
            let (rows, cols) = (m.nrows(), m.ncols());
            if (rows * cols) as u32 > cap {
                set_text(hh, "cross_cov: buffer too small");
                return -3;
            }
            for r in 0..rows {
                for c in 0..cols {
                    *out.add(r * cols + c) = m[(r, c)];
                }
            }
            rows as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}

/// Row-major pa x pb cross-covariance (f64) between a `Pose` and a
/// `Pose`; returns the row count, or -1 (error) / -2 (panic) / -3 (no
/// assembly or buffer too small), text via path_last_error.
#[no_mangle]
pub unsafe extern "C" fn path_pose_pose_cross_cov(
    h: *mut PathHandle,
    a: *const Pose,
    b: *const Pose,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "cross_cov: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.cross_cov(&*a, &*b))) {
        Ok(Ok(m)) => {
            let (rows, cols) = (m.nrows(), m.ncols());
            if (rows * cols) as u32 > cap {
                set_text(hh, "cross_cov: buffer too small");
                return -3;
            }
            for r in 0..rows {
                for c in 0..cols {
                    *out.add(r * cols + c) = m[(r, c)];
                }
            }
            rows as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_len(p: *const PathHandle) -> u32 {
    (*p).model.poses.len() as u32
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_reserve(p: *mut PathHandle, additional: u32) {
    (*p).model.poses.reserve(additional as usize);
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_push_back(p: *mut PathHandle) -> *mut Pose {
    let m = &mut (*p).model.poses;
    let r = m.push_back(Default::default());
    &mut m[r] as *mut Pose
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_push_front(p: *mut PathHandle) -> *mut Pose {
    let m = &mut (*p).model.poses;
    let r = m.push_front(Default::default());
    &mut m[r] as *mut Pose
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_at(p: *mut PathHandle, i: u32) -> *mut Pose {
    let m = &mut (*p).model.poses;
    &mut m[i as usize] as *mut Pose
}
/// Drops the back element; false when already empty.
#[no_mangle]
pub unsafe extern "C" fn path_poses_pop_back(p: *mut PathHandle) -> bool {
    (*p).model.poses.pop_back().is_some()
}
/// Drops the front element; false when already empty.
#[no_mangle]
pub unsafe extern "C" fn path_poses_pop_front(p: *mut PathHandle) -> bool {
    (*p).model.poses.pop_front().is_some()
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_clear(p: *mut PathHandle) {
    (*p).model.poses.clear();
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_truncate(p: *mut PathHandle, len: u32) {
    (*p).model.poses.truncate(len as usize);
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_ref_at(p: *const PathHandle, i: u32) -> u32 {
    (*p).model.poses.ref_at(i as usize).to_raw()
}
/// Ref of the first/last element, or u32::MAX when empty.
#[no_mangle]
pub unsafe extern "C" fn path_poses_front_ref(p: *const PathHandle) -> u32 {
    match (*p).model.poses.front_ref() {
        Some(r) => r.to_raw(),
        None => u32::MAX,
    }
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_back_ref(p: *const PathHandle) -> u32 {
    match (*p).model.poses.back_ref() {
        Some(r) => r.to_raw(),
        None => u32::MAX,
    }
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_get(p: *mut PathHandle, r: u32) -> *mut Pose {
    let m = &mut (*p).model.poses;
    &mut m[arael::refs::Ref::from_raw(r)] as *mut Pose
}
/// True while `r` addresses a live element of this collection.
#[no_mangle]
pub unsafe extern "C" fn path_poses_contains(p: *const PathHandle, r: u32) -> bool {
    (*p).model.poses.contains_ref(arael::refs::Ref::from_raw(r))
}
/// Like get, but null for a stale or foreign ref instead of a panic.
#[no_mangle]
pub unsafe extern "C" fn path_poses_try_get(p: *mut PathHandle, r: u32) -> *mut Pose {
    let m = &mut (*p).model.poses;
    match m.get_mut(arael::refs::Ref::from_raw(r)) {
        Some(e) => e as *mut Pose,
        None => std::ptr::null_mut(),
    }
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pairs_len(p: *const PathHandle) -> u32 {
    (*p).model.pose_pairs.len() as u32
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pairs_reserve(p: *mut PathHandle, additional: u32) {
    (*p).model.pose_pairs.reserve(additional as usize);
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pairs_push(p: *mut PathHandle) -> *mut PosePair {
    let m = &mut (*p).model.pose_pairs;
    m.push(Default::default());
    m.last_mut().unwrap() as *mut PosePair
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pairs_at(p: *mut PathHandle, i: u32) -> *mut PosePair {
    let m = &mut (*p).model.pose_pairs;
    &mut m[i as usize] as *mut PosePair
}
/// Drops the last element; false when already empty.
#[no_mangle]
pub unsafe extern "C" fn path_pose_pairs_pop(p: *mut PathHandle) -> bool {
    (*p).model.pose_pairs.pop().is_some()
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pairs_clear(p: *mut PathHandle) {
    (*p).model.pose_pairs.clear();
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pairs_truncate(p: *mut PathHandle, len: u32) {
    (*p).model.pose_pairs.truncate(len as usize);
}
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_len(p: *const PathHandle) -> u32 {
    (*p).model.landmarks.len() as u32
}
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_reserve(p: *mut PathHandle, additional: u32) {
    (*p).model.landmarks.reserve(additional as usize);
}
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_push(p: *mut PathHandle) -> u32 {
    let m = &mut (*p).model.landmarks;
    m.push(Default::default()).to_raw()
}
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_remove(p: *mut PathHandle, r: u32) -> bool {
    let m = &mut (*p).model.landmarks;
    m.remove(arael::refs::Ref::from_raw(r)).is_some()
}
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_clear(p: *mut PathHandle) {
    (*p).model.landmarks.clear();
}
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_get(p: *mut PathHandle, r: u32) -> *mut Landmark {
    let m = &mut (*p).model.landmarks;
    &mut m[arael::refs::Ref::from_raw(r)] as *mut Landmark
}
/// True while `r` addresses a live element of this collection.
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_contains(p: *const PathHandle, r: u32) -> bool {
    (*p).model.landmarks.contains_ref(arael::refs::Ref::from_raw(r))
}
/// Like get, but null for a stale or foreign ref instead of a panic.
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_try_get(p: *mut PathHandle, r: u32) -> *mut Landmark {
    let m = &mut (*p).model.landmarks;
    match m.get_mut(arael::refs::Ref::from_raw(r)) {
        Some(e) => e as *mut Landmark,
        None => std::ptr::null_mut(),
    }
}
/// First live element's packed ref, or u32::MAX when empty.
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_first(p: *const PathHandle) -> u32 {
    match (*p).model.landmarks.first_ref() {
        Some(r) => r.to_raw(),
        None => u32::MAX,
    }
}
/// The next live element after `r`'s slot, or u32::MAX past the end.
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_next(p: *const PathHandle, r: u32) -> u32 {
    match (*p).model.landmarks.next_ref(arael::refs::Ref::from_raw(r)) {
        Some(n) => n.to_raw(),
        None => u32::MAX,
    }
}
/// Last live element's packed ref, or u32::MAX when empty.
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_last(p: *const PathHandle) -> u32 {
    match (*p).model.landmarks.last_ref() {
        Some(r) => r.to_raw(),
        None => u32::MAX,
    }
}
/// The previous live element before `r`'s slot, or u32::MAX past the front.
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_prev(p: *const PathHandle, r: u32) -> u32 {
    match (*p).model.landmarks.prev_ref(arael::refs::Ref::from_raw(r)) {
        Some(n) => n.to_raw(),
        None => u32::MAX,
    }
}
#[no_mangle]
pub unsafe extern "C" fn path_frine_pose(p: *const Frine) -> u32 {
    (*p).pose.to_raw()
}
#[no_mangle]
pub unsafe extern "C" fn path_frine_set_pose(p: *mut Frine, v: u32) {
    (*p).pose = arael::refs::Ref::from_raw(v);
}
#[no_mangle]
pub unsafe extern "C" fn path_frine_bearing(p: *const Frine) -> f32 {
    (*p).bearing
}
#[no_mangle]
pub unsafe extern "C" fn path_frine_set_bearing(p: *mut Frine, v: f32) {
    (*p).bearing = v;
}
#[no_mangle]
pub unsafe extern "C" fn path_frine_isigma(p: *const Frine) -> f32 {
    (*p).isigma
}
#[no_mangle]
pub unsafe extern "C" fn path_frine_set_isigma(p: *mut Frine, v: f32) {
    (*p).isigma = v;
}
#[no_mangle]
pub unsafe extern "C" fn path_landmark_pos(p: *const Landmark) -> CVec2F32 {
    (*p).pos.value.into()
}
#[no_mangle]
pub unsafe extern "C" fn path_landmark_set_pos(p: *mut Landmark, v: CVec2F32) {
    (*p).pos.value = v.into();
}
#[no_mangle]
pub unsafe extern "C" fn path_landmark_pos_optimize(p: *const Landmark) -> bool {
    (*p).pos.optimize
}
#[no_mangle]
pub unsafe extern "C" fn path_landmark_pos_set_optimize(p: *mut Landmark, v: bool) {
    (*p).pos.optimize = v;
}
#[no_mangle]
pub unsafe extern "C" fn path_landmark_frines_len(p: *const Landmark) -> u32 {
    (*p).frines.len() as u32
}
#[no_mangle]
pub unsafe extern "C" fn path_landmark_frines_reserve(p: *mut Landmark, additional: u32) {
    (*p).frines.reserve(additional as usize);
}
#[no_mangle]
pub unsafe extern "C" fn path_landmark_frines_push(p: *mut Landmark) -> *mut Frine {
    let m = &mut (*p).frines;
    m.push(Default::default());
    m.last_mut().unwrap() as *mut Frine
}
#[no_mangle]
pub unsafe extern "C" fn path_landmark_frines_at(p: *mut Landmark, i: u32) -> *mut Frine {
    let m = &mut (*p).frines;
    &mut m[i as usize] as *mut Frine
}
/// Drops the last element; false when already empty.
#[no_mangle]
pub unsafe extern "C" fn path_landmark_frines_pop(p: *mut Landmark) -> bool {
    (*p).frines.pop().is_some()
}
#[no_mangle]
pub unsafe extern "C" fn path_landmark_frines_clear(p: *mut Landmark) {
    (*p).frines.clear();
}
#[no_mangle]
pub unsafe extern "C" fn path_landmark_frines_truncate(p: *mut Landmark, len: u32) {
    (*p).frines.truncate(len as usize);
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pos(p: *const Pose) -> CVec2F32 {
    (*p).pos.value.into()
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_set_pos(p: *mut Pose, v: CVec2F32) {
    (*p).pos.value = v.into();
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pos_optimize(p: *const Pose) -> bool {
    (*p).pos.optimize
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pos_set_optimize(p: *mut Pose, v: bool) {
    (*p).pos.optimize = v;
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_gamma(p: *const Pose) -> f32 {
    (*p).gamma.value
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_set_gamma(p: *mut Pose, v: f32) {
    (*p).gamma.value = v;
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_gamma_optimize(p: *const Pose) -> bool {
    (*p).gamma.optimize
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_gamma_set_optimize(p: *mut Pose, v: bool) {
    (*p).gamma.optimize = v;
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_delta_pos(p: *const Pose) -> CVec2F32 {
    (*p).delta_pos.into()
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_set_delta_pos(p: *mut Pose, v: CVec2F32) {
    (*p).delta_pos = v.into();
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_delta_gamma(p: *const Pose) -> f32 {
    (*p).delta_gamma
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_set_delta_gamma(p: *mut Pose, v: f32) {
    (*p).delta_gamma = v;
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_delta_pos_isigma(p: *const Pose) -> f32 {
    (*p).delta_pos_isigma
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_set_delta_pos_isigma(p: *mut Pose, v: f32) {
    (*p).delta_pos_isigma = v;
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_delta_gamma_isigma(p: *const Pose) -> f32 {
    (*p).delta_gamma_isigma
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_set_delta_gamma_isigma(p: *mut Pose, v: f32) {
    (*p).delta_gamma_isigma = v;
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pair_prev(p: *const PosePair) -> u32 {
    (*p).prev.to_raw()
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pair_set_prev(p: *mut PosePair, v: u32) {
    (*p).prev = arael::refs::Ref::from_raw(v);
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pair_cur(p: *const PosePair) -> u32 {
    (*p).cur.to_raw()
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pair_set_cur(p: *mut PosePair, v: u32) {
    (*p).cur = arael::refs::Ref::from_raw(v);
}
