// GENERATED by cargo-arael from the `Path` model sidecar. Do not edit;
// regenerate with `cargo arael export` (check drift with `cargo arael check`).
#![allow(clippy::missing_safety_doc)]

use std::ffi::CString;
use std::os::raw::c_char;
use std::panic::{AssertUnwindSafe, catch_unwind};
use arael::covariance::{CovAssembly, CovMode, Covariance};
use arael::simple_lm::{LmConfig, LmProblem, LmStatus};
use slam2d_simple::{Frine, Landmark, Path, Pose, PosePair};

/// The opaque handle the C ABI hands out: the model, the error /
/// diagnostic text buffer `last_error` points into, and the covariance
/// assembly once requested.
pub struct PathHandle {
    model: Path,
    text: CString,
    cov: Option<CovAssembly>,
}

macro_rules! c_vec2 {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub x: $t, pub y: $t }
        impl From<arael::vect::vect2<$t>> for $name {
            fn from(v: arael::vect::vect2<$t>) -> Self { Self { x: v.x, y: v.y } }
        }
        impl From<$name> for arael::vect::vect2<$t> {
            fn from(v: $name) -> Self { arael::vect::vect2::new(v.x, v.y) }
        }
    };
}
macro_rules! c_vec3 {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub x: $t, pub y: $t, pub z: $t }
        impl From<arael::vect::vect3<$t>> for $name {
            fn from(v: arael::vect::vect3<$t>) -> Self { Self { x: v.x, y: v.y, z: v.z } }
        }
        impl From<$name> for arael::vect::vect3<$t> {
            fn from(v: $name) -> Self { arael::vect::vect3::new(v.x, v.y, v.z) }
        }
    };
}
macro_rules! c_mat2 {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub m: [[$t; 2]; 2] }
        impl From<arael::matrix::matrix2<$t>> for $name {
            fn from(v: arael::matrix::matrix2<$t>) -> Self {
                Self { m: [[v.rows[0].x, v.rows[0].y], [v.rows[1].x, v.rows[1].y]] }
            }
        }
        impl From<$name> for arael::matrix::matrix2<$t> {
            fn from(v: $name) -> Self {
                arael::matrix::matrix2::from_elements(v.m[0][0], v.m[0][1], v.m[1][0], v.m[1][1])
            }
        }
    };
}
macro_rules! c_mat3 {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub m: [[$t; 3]; 3] }
        impl From<arael::matrix::matrix3<$t>> for $name {
            fn from(v: arael::matrix::matrix3<$t>) -> Self {
                Self { m: [
                    [v.rows[0].x, v.rows[0].y, v.rows[0].z],
                    [v.rows[1].x, v.rows[1].y, v.rows[1].z],
                    [v.rows[2].x, v.rows[2].y, v.rows[2].z],
                ] }
            }
        }
        impl From<$name> for arael::matrix::matrix3<$t> {
            fn from(v: $name) -> Self { arael::matrix::matrix3::from_array(v.m) }
        }
    };
}
macro_rules! c_quat {
    ($name:ident, $t:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct $name { pub t: $t, pub x: $t, pub y: $t, pub z: $t }
        impl From<arael::quatern::quatern<$t>> for $name {
            fn from(q: arael::quatern::quatern<$t>) -> Self {
                Self { t: q.t, x: q.v.x, y: q.v.y, z: q.v.z }
            }
        }
        impl From<$name> for arael::quatern::quatern<$t> {
            fn from(q: $name) -> Self {
                arael::quatern::quatern::new(q.t, arael::vect::vect3::new(q.x, q.y, q.z))
            }
        }
    };
}
c_vec2!(CVec2F32, f32);
c_vec2!(CVec2F64, f64);
c_vec3!(CVec3F32, f32);
c_vec3!(CVec3F64, f64);
c_mat2!(CMat2F32, f32);
c_mat2!(CMat2F64, f64);
c_mat3!(CMat3F32, f32);
c_mat3!(CMat3F64, f64);
c_quat!(CQuatF32, f32);
c_quat!(CQuatF64, f64);

fn status_code(s: &LmStatus) -> i32 {
    match s {
        LmStatus::Converged => 0,
        LmStatus::CostThreshold => 1,
        LmStatus::MaxIterations => 2,
        LmStatus::GradientTolerance => 3,
        LmStatus::ParameterTolerance => 4,
        LmStatus::PredictedReduction => 5,
        LmStatus::LambdaCeiling => 6,
        LmStatus::DriverTerminated => 7,
        LmStatus::ObserverTerminated => 8,
        LmStatus::TimeLimit => 9,
        LmStatus::RetryBudgetExhausted => 10,
        LmStatus::Aborted => 11,
    }
}

fn set_text(h: &mut PathHandle, msg: &str) {
    h.text = CString::new(msg.replace('\0', " ")).unwrap();
}

fn panic_text(p: Box<dyn std::any::Any + Send>) -> String {
    if let Some(s) = p.downcast_ref::<&str>() {
        (*s).to_string()
    } else if let Some(s) = p.downcast_ref::<String>() {
        s.clone()
    } else {
        "panic".to_string()
    }
}

/// Sentinel-based config: UINT32_MAX / NaN fields keep the preset's
/// value (0 = defaults, 1 = conservative, 2 = well_conditioned).
#[repr(C)]
pub struct CLmConfig {
    pub preset: u32,
    pub max_iters: u32,
    pub min_iters: u32,
    pub patience: u32,
    pub abs_precision: f32,
    pub rel_precision: f32,
    pub initial_lambda: f32,
    pub cost_threshold: f32,
}

impl CLmConfig {
    fn to_config(&self) -> LmConfig<f32> {
        let mut c: LmConfig<f32> = match self.preset {
            1 => LmConfig::conservative(),
            2 => LmConfig::well_conditioned(),
            _ => LmConfig::default(),
        };
        if self.max_iters != u32::MAX { c.max_iters = self.max_iters as usize; }
        if self.min_iters != u32::MAX { c.min_iters = self.min_iters as usize; }
        if self.patience != u32::MAX { c.patience = self.patience as usize; }
        if !self.abs_precision.is_nan() { c.abs_precision = self.abs_precision; }
        if !self.rel_precision.is_nan() { c.rel_precision = self.rel_precision; }
        if !self.initial_lambda.is_nan() { c.initial_lambda = self.initial_lambda; }
        if !self.cost_threshold.is_nan() { c.cost_threshold = self.cost_threshold; }
        c
    }
}

#[repr(C)]
pub struct CLmResult {
    pub start_cost: f32,
    pub end_cost: f32,
    pub iterations: u32,
    pub accepted_iterations: u32,
    pub status: i32,
    pub lambda: f32,
}

#[no_mangle]
pub extern "C" fn path_new() -> *mut PathHandle {
    Box::into_raw(Box::new(PathHandle {
        model: Default::default(),
        text: CString::default(),
        cov: None,
    }))
}

#[no_mangle]
pub unsafe extern "C" fn path_free(h: *mut PathHandle) {
    if !h.is_null() {
        drop(Box::from_raw(h));
    }
}

#[no_mangle]
pub unsafe extern "C" fn path_last_error(h: *const PathHandle) -> *const c_char {
    (*h).text.as_ptr()
}

/// Empty string when the model is clean, the Diagnostic text otherwise.
#[no_mangle]
pub unsafe extern "C" fn path_validate(h: *mut PathHandle) -> *const c_char {
    let hh = &mut *h;
    let text = match catch_unwind(AssertUnwindSafe(|| {
        let d = hh.model.validate();
        if d.is_clean() { String::new() } else { d.to_string() }
    })) {
        Ok(t) => t,
        Err(p) => panic_text(p),
    };
    set_text(hh, &text);
    hh.text.as_ptr()
}

/// Returns the status code (>= 0: LmStatus; -1: solve failure; -2:
/// panic). Failure text via path_last_error.
#[no_mangle]
pub unsafe extern "C" fn path_solve_dense(
    h: *mut PathHandle,
    cfg: *const CLmConfig,
    out: *mut CLmResult,
) -> i32 {
    let hh = &mut *h;
    let c = (*cfg).to_config();
    *out = CLmResult {
        start_cost: 0.0, end_cost: 0.0, iterations: 0,
        accepted_iterations: 0, status: -1, lambda: 0.0,
    };
    match catch_unwind(AssertUnwindSafe(|| hh.model.solve_dense(&c))) {
        Ok(Ok(r)) => {
            let code = status_code(&r.status);
            *out = CLmResult {
                start_cost: r.start_cost,
                end_cost: r.end_cost,
                iterations: r.iterations as u32,
                accepted_iterations: r.accepted_iterations as u32,
                status: code,
                lambda: r.final_lambda,
            };
            set_text(hh, "");
            code
        }
        Ok(Err(f)) => {
            set_text(hh, &format!("solve failure: {:?}", f.kind));
            (*out).status = -1;
            -1
        }
        Err(p) => {
            let msg = panic_text(p);
            set_text(hh, &msg);
            (*out).status = -2;
            -2
        }
    }
}

/// Returns the status code (>= 0: LmStatus; -1: solve failure; -2:
/// panic). Failure text via path_last_error.
#[no_mangle]
pub unsafe extern "C" fn path_solve_sparse(
    h: *mut PathHandle,
    cfg: *const CLmConfig,
    out: *mut CLmResult,
) -> i32 {
    let hh = &mut *h;
    let c = (*cfg).to_config();
    *out = CLmResult {
        start_cost: 0.0, end_cost: 0.0, iterations: 0,
        accepted_iterations: 0, status: -1, lambda: 0.0,
    };
    match catch_unwind(AssertUnwindSafe(|| hh.model.solve_sparse(&c))) {
        Ok(Ok(r)) => {
            let code = status_code(&r.status);
            *out = CLmResult {
                start_cost: r.start_cost,
                end_cost: r.end_cost,
                iterations: r.iterations as u32,
                accepted_iterations: r.accepted_iterations as u32,
                status: code,
                lambda: r.final_lambda,
            };
            set_text(hh, "");
            code
        }
        Ok(Err(f)) => {
            set_text(hh, &format!("solve failure: {:?}", f.kind));
            (*out).status = -1;
            -1
        }
        Err(p) => {
            let msg = panic_text(p);
            set_text(hh, &msg);
            (*out).status = -2;
            -2
        }
    }
}

/// mode: 0 = PerQuery, 1 = AllMarginals, 2 = TriDiagonal. Returns 0,
/// -1 (error, text via path_last_error), -2 (panic).
#[no_mangle]
pub unsafe extern "C" fn path_assemble_covariance(h: *mut PathHandle, mode: u32) -> i32 {
    let hh = &mut *h;
    let m = match mode {
        0 => CovMode::PerQuery,
        2 => CovMode::TriDiagonal,
        _ => CovMode::AllMarginals,
    };
    hh.cov = None;
    match catch_unwind(AssertUnwindSafe(|| hh.model.assemble_covariance(m))) {
        Ok(Ok(c)) => {
            hh.cov = Some(c);
            set_text(hh, "");
            0
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p) => {
            let msg = panic_text(p);
            set_text(hh, &msg);
            -2
        }
    }
}

/// Row-major dim x dim marginal covariance (f64) of one `Landmark`; returns
/// dim, or -1 (error) / -2 (panic) / -3 (no assembly or buffer too
/// small), text via path_last_error.
#[no_mangle]
pub unsafe extern "C" fn landmark_marginal_cov(
    h: *mut PathHandle,
    p: *const Landmark,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "marginal_cov: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.marginal_cov(&*p))) {
        Ok(Ok(m)) => {
            let dim = m.nrows();
            if (dim * dim) as u32 > cap {
                set_text(hh, "marginal_cov: buffer too small");
                return -3;
            }
            for r in 0..dim {
                for c in 0..dim {
                    *out.add(r * dim + c) = m[(r, c)];
                }
            }
            dim as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}

/// Row-major dim x dim marginal covariance (f64) of one `Pose`; returns
/// dim, or -1 (error) / -2 (panic) / -3 (no assembly or buffer too
/// small), text via path_last_error.
#[no_mangle]
pub unsafe extern "C" fn pose_marginal_cov(
    h: *mut PathHandle,
    p: *const Pose,
    out: *mut f64,
    cap: u32,
) -> i32 {
    let hh = &mut *h;
    let Some(cov) = hh.cov.as_ref() else {
        set_text(hh, "marginal_cov: assemble_covariance was not called");
        return -3;
    };
    match catch_unwind(AssertUnwindSafe(|| cov.marginal_cov(&*p))) {
        Ok(Ok(m)) => {
            let dim = m.nrows();
            if (dim * dim) as u32 > cap {
                set_text(hh, "marginal_cov: buffer too small");
                return -3;
            }
            for r in 0..dim {
                for c in 0..dim {
                    *out.add(r * dim + c) = m[(r, c)];
                }
            }
            dim as i32
        }
        Ok(Err(e)) => {
            set_text(hh, &format!("{}", e));
            -1
        }
        Err(p2) => {
            let msg = panic_text(p2);
            set_text(hh, &msg);
            -2
        }
    }
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_len(p: *const PathHandle) -> u32 {
    (*p).model.poses.len() as u32
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_push_back(p: *mut PathHandle) -> *mut Pose {
    let m = &mut (*p).model.poses;
    let r = m.push_back(Default::default());
    &mut m[r] as *mut Pose
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_push_front(p: *mut PathHandle) -> *mut Pose {
    let m = &mut (*p).model.poses;
    let r = m.push_front(Default::default());
    &mut m[r] as *mut Pose
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_at(p: *mut PathHandle, i: u32) -> *mut Pose {
    let m = &mut (*p).model.poses;
    &mut m[i as usize] as *mut Pose
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_ref_at(p: *const PathHandle, i: u32) -> u32 {
    (*p).model.poses.ref_at(i as usize).to_raw()
}
#[no_mangle]
pub unsafe extern "C" fn path_poses_get(p: *mut PathHandle, r: u32) -> *mut Pose {
    let m = &mut (*p).model.poses;
    &mut m[arael::refs::Ref::from_raw(r)] as *mut Pose
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pairs_len(p: *const PathHandle) -> u32 {
    (*p).model.pose_pairs.len() as u32
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pairs_push(p: *mut PathHandle) -> *mut PosePair {
    let m = &mut (*p).model.pose_pairs;
    m.push(Default::default());
    m.last_mut().unwrap() as *mut PosePair
}
#[no_mangle]
pub unsafe extern "C" fn path_pose_pairs_at(p: *mut PathHandle, i: u32) -> *mut PosePair {
    let m = &mut (*p).model.pose_pairs;
    &mut m[i as usize] as *mut PosePair
}
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_len(p: *const PathHandle) -> u32 {
    (*p).model.landmarks.len() as u32
}
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_push(p: *mut PathHandle) -> u32 {
    let m = &mut (*p).model.landmarks;
    m.push(Default::default()).to_raw()
}
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_remove(p: *mut PathHandle, r: u32) -> bool {
    let m = &mut (*p).model.landmarks;
    m.remove(arael::refs::Ref::from_raw(r)).is_some()
}
#[no_mangle]
pub unsafe extern "C" fn path_landmarks_get(p: *mut PathHandle, r: u32) -> *mut Landmark {
    let m = &mut (*p).model.landmarks;
    &mut m[arael::refs::Ref::from_raw(r)] as *mut Landmark
}
#[no_mangle]
pub unsafe extern "C" fn frine_pose(p: *const Frine) -> u32 {
    (*p).pose.to_raw()
}
#[no_mangle]
pub unsafe extern "C" fn frine_set_pose(p: *mut Frine, v: u32) {
    (*p).pose = arael::refs::Ref::from_raw(v);
}
#[no_mangle]
pub unsafe extern "C" fn frine_bearing(p: *const Frine) -> f32 {
    (*p).bearing
}
#[no_mangle]
pub unsafe extern "C" fn frine_set_bearing(p: *mut Frine, v: f32) {
    (*p).bearing = v;
}
#[no_mangle]
pub unsafe extern "C" fn frine_isigma(p: *const Frine) -> f32 {
    (*p).isigma
}
#[no_mangle]
pub unsafe extern "C" fn frine_set_isigma(p: *mut Frine, v: f32) {
    (*p).isigma = v;
}
#[no_mangle]
pub unsafe extern "C" fn landmark_pos(p: *const Landmark) -> CVec2F32 {
    (*p).pos.value.into()
}
#[no_mangle]
pub unsafe extern "C" fn landmark_set_pos(p: *mut Landmark, v: CVec2F32) {
    (*p).pos.value = v.into();
}
#[no_mangle]
pub unsafe extern "C" fn landmark_pos_optimize(p: *const Landmark) -> bool {
    (*p).pos.optimize
}
#[no_mangle]
pub unsafe extern "C" fn landmark_pos_set_optimize(p: *mut Landmark, v: bool) {
    (*p).pos.optimize = v;
}
#[no_mangle]
pub unsafe extern "C" fn landmark_frines_len(p: *const Landmark) -> u32 {
    (*p).frines.len() as u32
}
#[no_mangle]
pub unsafe extern "C" fn landmark_frines_push(p: *mut Landmark) -> *mut Frine {
    let m = &mut (*p).frines;
    m.push(Default::default());
    m.last_mut().unwrap() as *mut Frine
}
#[no_mangle]
pub unsafe extern "C" fn landmark_frines_at(p: *mut Landmark, i: u32) -> *mut Frine {
    let m = &mut (*p).frines;
    &mut m[i as usize] as *mut Frine
}
#[no_mangle]
pub unsafe extern "C" fn pose_pos(p: *const Pose) -> CVec2F32 {
    (*p).pos.value.into()
}
#[no_mangle]
pub unsafe extern "C" fn pose_set_pos(p: *mut Pose, v: CVec2F32) {
    (*p).pos.value = v.into();
}
#[no_mangle]
pub unsafe extern "C" fn pose_pos_optimize(p: *const Pose) -> bool {
    (*p).pos.optimize
}
#[no_mangle]
pub unsafe extern "C" fn pose_pos_set_optimize(p: *mut Pose, v: bool) {
    (*p).pos.optimize = v;
}
#[no_mangle]
pub unsafe extern "C" fn pose_gamma(p: *const Pose) -> f32 {
    (*p).gamma.value
}
#[no_mangle]
pub unsafe extern "C" fn pose_set_gamma(p: *mut Pose, v: f32) {
    (*p).gamma.value = v;
}
#[no_mangle]
pub unsafe extern "C" fn pose_gamma_optimize(p: *const Pose) -> bool {
    (*p).gamma.optimize
}
#[no_mangle]
pub unsafe extern "C" fn pose_gamma_set_optimize(p: *mut Pose, v: bool) {
    (*p).gamma.optimize = v;
}
#[no_mangle]
pub unsafe extern "C" fn pose_delta_pos(p: *const Pose) -> CVec2F32 {
    (*p).delta_pos.into()
}
#[no_mangle]
pub unsafe extern "C" fn pose_set_delta_pos(p: *mut Pose, v: CVec2F32) {
    (*p).delta_pos = v.into();
}
#[no_mangle]
pub unsafe extern "C" fn pose_delta_gamma(p: *const Pose) -> f32 {
    (*p).delta_gamma
}
#[no_mangle]
pub unsafe extern "C" fn pose_set_delta_gamma(p: *mut Pose, v: f32) {
    (*p).delta_gamma = v;
}
#[no_mangle]
pub unsafe extern "C" fn pose_delta_pos_isigma(p: *const Pose) -> f32 {
    (*p).delta_pos_isigma
}
#[no_mangle]
pub unsafe extern "C" fn pose_set_delta_pos_isigma(p: *mut Pose, v: f32) {
    (*p).delta_pos_isigma = v;
}
#[no_mangle]
pub unsafe extern "C" fn pose_delta_gamma_isigma(p: *const Pose) -> f32 {
    (*p).delta_gamma_isigma
}
#[no_mangle]
pub unsafe extern "C" fn pose_set_delta_gamma_isigma(p: *mut Pose, v: f32) {
    (*p).delta_gamma_isigma = v;
}
#[no_mangle]
pub unsafe extern "C" fn pose_pair_prev(p: *const PosePair) -> u32 {
    (*p).prev.to_raw()
}
#[no_mangle]
pub unsafe extern "C" fn pose_pair_set_prev(p: *mut PosePair, v: u32) {
    (*p).prev = arael::refs::Ref::from_raw(v);
}
#[no_mangle]
pub unsafe extern "C" fn pose_pair_cur(p: *const PosePair) -> u32 {
    (*p).cur.to_raw()
}
#[no_mangle]
pub unsafe extern "C" fn pose_pair_set_cur(p: *mut PosePair, v: u32) {
    (*p).cur = arael::refs::Ref::from_raw(v);
}
