//! Rust FFI shim emitter: `#[no_mangle] extern "C"` functions over the
//! model, compiled in the generated capi crate (edition 2021, so no
//! inner unsafe blocks are needed). The surface is pure C ABI -- it
//! serves both the C++ header and the Python ctypes module.

use crate::ir::{Field, Model, snake};

/// C-ABI scalar spelling for a Rust scalar type; None = not a scalar
/// the skeleton supports.
fn scalar_c(of: &str) -> Option<&'static str> {
    Some(match of {
        "f64" => "f64",
        "f32" => "f32",
        "bool" => "bool",
        "u32" => "u32",
        "i32" => "i32",
        _ => return None,
    })
}

/// Collection flavor from the recorded spelling. refs::Vec has stable
/// element addresses and push() returns a Ref; std::vec::Vec moves on
/// realloc and push() returns unit.
enum Flavor {
    Refs,
    Std,
}

fn vec_flavor(f: &Field) -> Result<Flavor, String> {
    let sp = f.spelled.as_deref().unwrap_or("");
    if sp.starts_with("refs::Vec<") || sp.contains("::refs::Vec<") {
        Ok(Flavor::Refs)
    } else if sp.starts_with("std::vec::Vec<") {
        Ok(Flavor::Std)
    } else {
        Err(format!(
            "collection `{}` spelled `{}`: spell it `refs::Vec<..>` or `std::vec::Vec<..>` \
             so the generator knows the container flavor",
            f.name, sp))
    }
}

fn unsupported(type_name: &str, f: &Field) -> String {
    format!("`{}.{}` kind `{}` is not supported by the cargo-arael skeleton yet",
        type_name, f.name, f.kind)
}

/// Per-field accessor pair over an entity pointer expression.
fn field_accessors(
    out: &mut String,
    fn_prefix: &str,
    ptr_ty: &str,
    access: &str,
    type_name: &str,
    f: &Field,
) -> Result<(), String> {
    let name = &f.name;
    let of = f.of.as_deref().unwrap_or("");
    match f.kind.as_str() {
        "data" => {
            let c = scalar_c(of).ok_or_else(|| unsupported(type_name, f))?;
            out.push_str(&format!(
"#[no_mangle]
pub unsafe extern \"C\" fn {fn_prefix}_{name}(p: *const {ptr_ty}) -> {c} {{
    {access}.{name}
}}
#[no_mangle]
pub unsafe extern \"C\" fn {fn_prefix}_set_{name}(p: *mut {ptr_ty}, v: {c}) {{
    {access}.{name} = v;
}}
"));
        }
        "param" => {
            let c = scalar_c(of).ok_or_else(|| unsupported(type_name, f))?;
            out.push_str(&format!(
"#[no_mangle]
pub unsafe extern \"C\" fn {fn_prefix}_{name}(p: *const {ptr_ty}) -> {c} {{
    {access}.{name}.value
}}
#[no_mangle]
pub unsafe extern \"C\" fn {fn_prefix}_set_{name}(p: *mut {ptr_ty}, v: {c}) {{
    {access}.{name}.value = v;
}}
"));
        }
        "self_block" | "cross_block" | "triplet_block" | "skip" | "opaque" => {}
        _ => return Err(unsupported(type_name, f)),
    }
    Ok(())
}

pub fn emit(model: &Model, model_crate: &str) -> Result<String, String> {
    let root = &model.root;
    let root_sn = snake(root);
    let fp = &model.precision; // "f32" | "f64"
    let handle = format!("{root}Handle");

    let mut used: Vec<&str> = vec![root.as_str()];
    for (tn, t) in &model.types {
        if t.role == "entity" && !t.builtin {
            used.push(tn.as_str());
        }
    }
    used.sort();
    used.dedup();

    let mut out = String::new();
    out.push_str(&format!(
"// GENERATED by cargo-arael from the `{root}` model sidecar. Do not edit;
// regenerate with `cargo arael export` (check drift with `cargo arael check`).
#![allow(clippy::missing_safety_doc)]

use std::ffi::CString;
use std::os::raw::c_char;
use std::panic::{{AssertUnwindSafe, catch_unwind}};
use arael::simple_lm::{{LmConfig, LmProblem, LmStatus}};
use {model_crate}::{{{}}};

/// The opaque handle the C ABI hands out: the model plus the error /
/// diagnostic text buffer `last_error` points into.
pub struct {handle} {{
    model: {root},
    text: CString,
}}

fn status_code(s: &LmStatus) -> i32 {{
    match s {{
        LmStatus::Converged => 0,
        LmStatus::CostThreshold => 1,
        LmStatus::MaxIterations => 2,
        LmStatus::GradientTolerance => 3,
        LmStatus::ParameterTolerance => 4,
        LmStatus::PredictedReduction => 5,
        LmStatus::LambdaCeiling => 6,
        LmStatus::DriverTerminated => 7,
        LmStatus::ObserverTerminated => 8,
        LmStatus::TimeLimit => 9,
        LmStatus::RetryBudgetExhausted => 10,
        LmStatus::Aborted => 11,
    }}
}}

fn set_text(h: &mut {handle}, msg: &str) {{
    h.text = CString::new(msg.replace('\\0', \" \")).unwrap();
}}

fn panic_text(p: Box<dyn std::any::Any + Send>) -> String {{
    if let Some(s) = p.downcast_ref::<&str>() {{
        (*s).to_string()
    }} else if let Some(s) = p.downcast_ref::<String>() {{
        s.clone()
    }} else {{
        \"panic\".to_string()
    }}
}}

/// Sentinel-based config: UINT32_MAX / NaN fields keep the preset's
/// value (0 = defaults, 1 = conservative).
#[repr(C)]
pub struct CLmConfig {{
    pub preset: u32,
    pub max_iters: u32,
    pub min_iters: u32,
    pub patience: u32,
    pub abs_precision: {fp},
    pub rel_precision: {fp},
    pub initial_lambda: {fp},
    pub cost_threshold: {fp},
}}

impl CLmConfig {{
    fn to_config(&self) -> LmConfig<{fp}> {{
        let mut c: LmConfig<{fp}> = match self.preset {{
            1 => LmConfig::conservative(),
            _ => LmConfig::default(),
        }};
        if self.max_iters != u32::MAX {{ c.max_iters = self.max_iters as usize; }}
        if self.min_iters != u32::MAX {{ c.min_iters = self.min_iters as usize; }}
        if self.patience != u32::MAX {{ c.patience = self.patience as usize; }}
        if !self.abs_precision.is_nan() {{ c.abs_precision = self.abs_precision; }}
        if !self.rel_precision.is_nan() {{ c.rel_precision = self.rel_precision; }}
        if !self.initial_lambda.is_nan() {{ c.initial_lambda = self.initial_lambda; }}
        if !self.cost_threshold.is_nan() {{ c.cost_threshold = self.cost_threshold; }}
        c
    }}
}}

#[repr(C)]
pub struct CLmResult {{
    pub start_cost: {fp},
    pub end_cost: {fp},
    pub iterations: u32,
    pub accepted_iterations: u32,
    pub status: i32,
    pub lambda: {fp},
}}

#[no_mangle]
pub extern \"C\" fn {root_sn}_new() -> *mut {handle} {{
    Box::into_raw(Box::new({handle} {{
        model: Default::default(),
        text: CString::default(),
    }}))
}}

#[no_mangle]
pub unsafe extern \"C\" fn {root_sn}_free(h: *mut {handle}) {{
    if !h.is_null() {{
        drop(Box::from_raw(h));
    }}
}}

#[no_mangle]
pub unsafe extern \"C\" fn {root_sn}_last_error(h: *const {handle}) -> *const c_char {{
    (*h).text.as_ptr()
}}

/// Empty string when the model is clean, the Diagnostic text otherwise.
#[no_mangle]
pub unsafe extern \"C\" fn {root_sn}_validate(h: *mut {handle}) -> *const c_char {{
    let hh = &mut *h;
    let text = match catch_unwind(AssertUnwindSafe(|| {{
        let d = hh.model.validate();
        if d.is_clean() {{ String::new() }} else {{ d.to_string() }}
    }})) {{
        Ok(t) => t,
        Err(p) => panic_text(p),
    }};
    set_text(hh, &text);
    hh.text.as_ptr()
}}
",
        used.join(", ")));

    for method in ["solve_dense", "solve_sparse"] {
        out.push_str(&format!(
"
/// Returns the status code (>= 0: LmStatus; -1: solve failure; -2:
/// panic). Failure text via {root_sn}_last_error.
#[no_mangle]
pub unsafe extern \"C\" fn {root_sn}_{method}(
    h: *mut {handle},
    cfg: *const CLmConfig,
    out: *mut CLmResult,
) -> i32 {{
    let hh = &mut *h;
    let c = (*cfg).to_config();
    *out = CLmResult {{
        start_cost: 0.0, end_cost: 0.0, iterations: 0,
        accepted_iterations: 0, status: -1, lambda: 0.0,
    }};
    match catch_unwind(AssertUnwindSafe(|| hh.model.{method}(&c))) {{
        Ok(Ok(r)) => {{
            let code = status_code(&r.status);
            *out = CLmResult {{
                start_cost: r.start_cost,
                end_cost: r.end_cost,
                iterations: r.iterations as u32,
                accepted_iterations: r.accepted_iterations as u32,
                status: code,
                lambda: r.final_lambda,
            }};
            set_text(hh, \"\");
            code
        }}
        Ok(Err(f)) => {{
            set_text(hh, &format!(\"solve failure: {{:?}}\", f.kind));
            (*out).status = -1;
            -1
        }}
        Err(p) => {{
            let msg = panic_text(p);
            set_text(hh, &msg);
            (*out).status = -2;
            -2
        }}
    }}
}}
"));
    }

    // Root's own fields: accessors through the handle.
    let root_ty = model.types.get(root).ok_or("root type missing from sidecar")?;
    for f in &root_ty.fields {
        match f.kind.as_str() {
            "collection" => {
                let elem = f.of.as_deref().ok_or("collection without element")?;
                let elem_sn_fns = format!("{root_sn}_{}", f.name);
                let field = &f.name;
                if f.container.as_deref() != Some("vec") {
                    return Err(format!(
                        "collection `{field}`: only vec containers in the skeleton"));
                }
                let push_body = match vec_flavor(f)? {
                    Flavor::Refs => format!(
"    let m = &mut (*h).model;
    let r = m.{field}.push(Default::default());
    &mut m.{field}[r] as *mut {elem}"),
                    Flavor::Std => format!(
"    let m = &mut (*h).model;
    m.{field}.push(Default::default());
    m.{field}.last_mut().unwrap() as *mut {elem}"),
                };
                out.push_str(&format!(
"
#[no_mangle]
pub unsafe extern \"C\" fn {elem_sn_fns}_len(h: *const {handle}) -> u32 {{
    (*h).model.{field}.len() as u32
}}
#[no_mangle]
pub unsafe extern \"C\" fn {elem_sn_fns}_push(h: *mut {handle}) -> *mut {elem} {{
{push_body}
}}
#[no_mangle]
pub unsafe extern \"C\" fn {elem_sn_fns}_at(h: *mut {handle}, i: u32) -> *mut {elem} {{
    let m = &mut (*h).model;
    &mut m.{field}[i as usize] as *mut {elem}
}}
"));
            }
            _ => field_accessors(&mut out, &root_sn, &handle, "(*p).model", root, f)?,
        }
    }

    // Entity types: accessors over raw entity pointers.
    for (tn, t) in &model.types {
        if t.role != "entity" || t.builtin {
            continue;
        }
        let sn = snake(tn);
        for f in &t.fields {
            if f.kind == "collection" {
                return Err(format!(
                    "`{tn}.{}`: nested collections are not in the skeleton yet", f.name));
            }
            field_accessors(&mut out, &sn, tn, "(*p)", tn, f)?;
        }
    }

    Ok(out)
}
