//! The export pipeline: build the model crate with the sidecar
//! enabled, harvest the JSON, emit the generated tree (capi crate,
//! C++ header, vendored math headers). `check` regenerates in memory
//! and diffs against the committed tree.

use crate::ir::Model;
use std::path::{Path, PathBuf};

const MARKER: &str = "GENERATED by cargo-arael";
const STUB_NOTE: &str = "placeholder until the export completes";

/// What `run_export` does with one generated file, given the file's
/// tree-relative path, what is on disk (`None` = absent) and the new
/// content.
///
/// Scaffold files (`capi/Cargo.toml`) are written ONCE: a user may
/// edit them (dependencies, crate-type, profile), so an existing one
/// is kept unless it is still the pre-harvest stub -- delete the file
/// to regenerate. Everything else overwrites its own marker-stamped
/// output and refuses a file that does not look generated. A file
/// whose content is already the new content is left untouched, so an
/// export that changes nothing moves no timestamp and the consumer's
/// build has nothing to redo.
#[derive(Debug, PartialEq, Eq)]
pub enum WriteAction {
    Write,
    Keep,
    Refuse,
    Unchanged,
}

pub fn write_action(rel: &Path, on_disk: Option<&str>, content: &str) -> WriteAction {
    let scaffold = rel == Path::new("capi/Cargo.toml");
    match on_disk {
        None => WriteAction::Write,
        Some(old) if scaffold => {
            if old.contains(STUB_NOTE) { WriteAction::Write } else { WriteAction::Keep }
        }
        Some(old) if old == content => WriteAction::Unchanged,
        Some(old) => {
            if old.contains(MARKER) { WriteAction::Write } else { WriteAction::Refuse }
        }
    }
}

/// The vendored math headers, embedded so an installed binary is
/// self-contained.
/// The vendored Python support library, embedded like the headers.
const PY_SUPPORT: &[(&str, &str)] = &[
    ("__init__.py", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/python/arael/__init__.py"))),
    ("math.py", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/python/arael/math.py"))),
    ("geometry.py", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/python/arael/geometry.py"))),
    ("g2o.py", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/python/arael/g2o.py"))),
    ("solver.py", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/python/arael/solver.py"))),
    ("columns.py", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/python/arael/columns.py"))),
    ("transform.py", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/python/arael/transform.py"))),
];

const MATH_HEADERS: &[(&str, &str)] = &[
    ("vect.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/vect.hpp"))),
    ("matrix.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/matrix.hpp"))),
    ("quatern.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/quatern.hpp"))),
    ("transform.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/transform.hpp"))),
    ("eigen.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/eigen.hpp"))),
    ("geometry.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/geometry.hpp"))),
    ("g2o.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/g2o.hpp"))),
    ("math.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/math.hpp"))),
    ("result.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/result.hpp"))),
    ("assert.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/assert.hpp"))),
    ("solver.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/solver.hpp"))),
];

/// Minimal Cargo.toml scan: `name = "..."` in [package], the
/// `arael = ...` dependency line from [dependencies], and an optional
/// `namespace = "..."` under [package.metadata.arael] (the C++
/// namespace; defaults to the crate name with hyphens as
/// underscores).
fn scan_manifest(dir: &Path) -> Result<(String, String, Option<String>), String> {
    let text = std::fs::read_to_string(dir.join("Cargo.toml"))
        .map_err(|e| format!("read {}/Cargo.toml: {e}", dir.display()))?;
    let mut section = String::new();
    let mut name = None;
    let mut arael_dep = None;
    let mut namespace = None;
    for line in text.lines() {
        let t = line.trim();
        if t.starts_with('[') {
            section = t.to_string();
            continue;
        }
        if section == "[package]" && t.starts_with("name") {
            if let Some(v) = t.split('"').nth(1) {
                name = Some(v.to_string());
            }
        }
        if section == "[package.metadata.arael]" && t.starts_with("namespace") {
            if let Some(v) = t.split('"').nth(1) {
                namespace = Some(v.to_string());
            }
        }
        if section == "[dependencies]"
            && (t.starts_with("arael ") || t.starts_with("arael="))
        {
            arael_dep = Some(t.split_once('=').map(|(_, v)| v.trim().to_string())
                .ok_or("malformed arael dependency line")?);
        }
    }
    let name = name.ok_or("no [package] name in Cargo.toml")?;
    let arael_dep = arael_dep.ok_or("no `arael` entry under [dependencies]")?;
    Ok((name, arael_dep, namespace))
}

/// The generated files for a crate's models, as (relative path,
/// content). One root gets today's flat layout; several roots share
/// one capi crate (each root's shim in its own module -- symbols are
/// root-prefixed) and each root's header nests its namespace:
/// `{ns}::{root_sn}`.
pub fn generate(
    models: &[&Model],
    crate_name: &str,
    arael_dep: &str,
    namespace: Option<&str>,
) -> Result<Vec<(PathBuf, String)>, String> {
    let rust_ident = crate_name.replace('-', "_");
    let ns = namespace.map(str::to_string).unwrap_or_else(|| rust_ident.clone());
    let multi = models.len() > 1;

    let ffi = if multi {
        let roots: Vec<&str> = models.iter().map(|m| m.root.as_str()).collect();
        let mut out = format!(
"// GENERATED by cargo-arael from the {} model sidecars. Do not edit;
// regenerate with `cargo arael export` (check drift with `cargo arael check`).
#![allow(clippy::missing_safety_doc)]
", roots.join(" / "));
        for m in models {
            let root_sn = crate::ir::snake(&m.root);
            out.push_str(&format!("\npub mod {root_sn} {{\n\n{}\n}} // mod {root_sn}\n",
                crate::emit_ffi::emit_body(m, &rust_ident)?));
        }
        out
    } else {
        crate::emit_ffi::emit(models[0], &rust_ident)?
    };

    let mut headers = Vec::new();
    for m in models {
        let root_sn = crate::ir::snake(&m.root);
        let root_ns = if multi { format!("{ns}::{root_sn}") } else { ns.clone() };
        headers.push((root_sn, crate::emit_hpp::emit(m, &root_ns)?));
    }

    let lib_ident_py = format!("{}_capi", rust_ident);
    let mut py_modules = Vec::new();
    for m in models {
        let root_sn = crate::ir::snake(&m.root);
        let (ffi_py, api_py) = crate::emit_py::emit(m, &lib_ident_py)?;
        py_modules.push((root_sn, ffi_py, api_py));
    }
    let py_init = {
        let roots: Vec<&str> = py_modules.iter().map(|(sn, _, _)| sn.as_str()).collect();
        let mut init = format!(
"# {MARKER}: package init for the `{}` model interface. Do not edit.
from . import arael  # noqa: F401
", roots.join("` / `"));
        for sn in &roots {
            init.push_str(&format!("from . import {sn}  # noqa: F401\n"));
        }
        if roots.len() == 1 {
            init.push_str(&format!("from .{} import *  # noqa: F401,F403\n", roots[0]));
        }
        init
    };

    let roots_label = models.iter().map(|m| m.root.as_str())
        .collect::<Vec<_>>().join("` / `");

    let arael_dep = if arael_dep.contains("path = \"") && !arael_dep.contains("path = \"/") {
        // Relative path dep: the capi crate is one directory deeper.
        arael_dep.replacen("path = \"", "path = \"../", 1)
    } else {
        arael_dep.to_string()
    };

    let capi_toml = format!(
"# {MARKER}: shim crate for the `{roots_label}` model. Written once -- edit freely; delete the file to regenerate.
[package]
name = \"{crate_name}-capi\"
version = \"0.1.0\"
edition = \"2021\"

[lib]
crate-type = [\"cdylib\", \"staticlib\"]

[dependencies]
{crate_name} = {{ path = \"..\" }}
arael = {arael_dep}
",
        );

    let lib_ident = format!("{}_capi", rust_ident);
    let target = rust_ident.clone();
    let cmake = format!(
"# {MARKER}: build glue for the `{roots_label}` model interface. Do not edit.
") + &format!("
#
# Consumer usage:
#   add_subdirectory(path/to/cxx)        # or FetchContent
#   target_link_libraries(app PRIVATE arael::{target})
#
# Requires a Rust toolchain (cargo builds the capi staticlib; cargo is
# its own dependency tracker, so the custom target always runs and
# no-ops when nothing changed).
cmake_minimum_required(VERSION 3.16)

if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  project({target}_capi NONE)
endif()

set(_arael_capi_dir \"${{CMAKE_CURRENT_SOURCE_DIR}}/../capi\")
set(_arael_cargo_target \"${{CMAKE_CURRENT_BINARY_DIR}}/cargo\")
set(_arael_capi_lib \"${{_arael_cargo_target}}/release/lib{lib_ident}.a\")

add_custom_target({target}_capi_build
  COMMAND cargo build --release
          --manifest-path \"${{_arael_capi_dir}}/Cargo.toml\"
          --target-dir \"${{_arael_cargo_target}}\"
  BYPRODUCTS \"${{_arael_capi_lib}}\"
  VERBATIM)

add_library(arael_{target} STATIC IMPORTED GLOBAL)
set_target_properties(arael_{target} PROPERTIES
  IMPORTED_LOCATION \"${{_arael_capi_lib}}\"
  INTERFACE_INCLUDE_DIRECTORIES \"${{CMAKE_CURRENT_SOURCE_DIR}}/include\")
if(UNIX)
  set_property(TARGET arael_{target} APPEND PROPERTY
    INTERFACE_LINK_LIBRARIES pthread dl m)
endif()
add_dependencies(arael_{target} {target}_capi_build)
add_library(arael::{target} ALIAS arael_{target})
");

    let mut files = vec![
        (PathBuf::from("capi/Cargo.toml"), capi_toml),
        (PathBuf::from("capi/src/lib.rs"), ffi),
        (PathBuf::from("cxx/CMakeLists.txt"), cmake),
    ];
    for (sn, hpp) in headers {
        files.push((PathBuf::from(format!("cxx/include/{sn}.hpp")), hpp));
    }
    for (name, content) in MATH_HEADERS {
        // Vendored copy: the marker line makes it overwritable on
        // regeneration (the source of truth ships with cargo-arael).
        let stamped = format!("// {MARKER} (vendored math header). Do not edit.\n{content}");
        files.push((PathBuf::from(format!("cxx/include/arael/{name}")), stamped));
    }

    files.push((PathBuf::from(format!("python/{ns}/__init__.py")), py_init));
    for (sn, ffi_py, api_py) in py_modules {
        files.push((PathBuf::from(format!("python/{ns}/_{sn}_ffi.py")), ffi_py));
        files.push((PathBuf::from(format!("python/{ns}/{sn}.py")), api_py));
    }
    for (name, content) in PY_SUPPORT {
        let stamped = format!("# {MARKER} (vendored python support). Do not edit.\n{content}");
        files.push((PathBuf::from(format!("python/{ns}/arael/{name}")), stamped));
    }
    Ok(files)
}

/// A workspace listing `model/capi` before the first export cannot
/// even build the model crate (missing member). Stub the capi crate so
/// the harvest build resolves; the real files overwrite it.
fn stub_capi(dir: &Path, crate_name: &str) -> Result<(), String> {
    let capi = dir.join("capi");
    if capi.join("Cargo.toml").exists() {
        return Ok(());
    }
    std::fs::create_dir_all(capi.join("src")).map_err(|e| format!("mkdir capi: {e}"))?;
    std::fs::write(capi.join("Cargo.toml"), format!(
"# {MARKER}: {STUB_NOTE}. Do not edit.
[package]
name = \"{crate_name}-capi\"
version = \"0.0.0\"
edition = \"2021\"
")).map_err(|e| format!("write capi stub: {e}"))?;
    std::fs::write(capi.join("src/lib.rs"),
        format!("// {MARKER}: placeholder until the export completes.\n"))
        .map_err(|e| format!("write capi stub: {e}"))?;
    Ok(())
}

/// Build the model crate with the sidecar enabled and read the JSONs.
fn harvest(dir: &Path) -> Result<Vec<Model>, String> {
    // The env var is not in cargo's fingerprint: touch the sources so
    // the crate re-expands.
    let src = dir.join("src");
    if let Ok(entries) = std::fs::read_dir(&src) {
        for e in entries.flatten() {
            let p = e.path();
            if p.extension().is_some_and(|x| x == "rs") {
                let _ = std::fs::OpenOptions::new().append(true).open(&p)
                    .and_then(|f| f.set_modified(std::time::SystemTime::now()));
            }
        }
    }
    // Absolute path: the proc macro writes to it from rustc's CWD, which for
    // a workspace member is the workspace root, not `dir`. An absolute target
    // is CWD-independent, so the macro writes exactly where we read.
    let sidecar_dir = std::fs::canonicalize(dir)
        .unwrap_or_else(|_| dir.to_path_buf())
        .join("target/arael-sidecar");
    let _ = std::fs::remove_dir_all(&sidecar_dir);
    let status = std::process::Command::new("cargo")
        .arg("build")
        .current_dir(dir)
        .env("ARAEL_SIDECAR_DIR", &sidecar_dir)
        .status()
        .map_err(|e| format!("cargo build: {e}"))?;
    if !status.success() {
        return Err("cargo build failed".to_string());
    }
    let mut models = Vec::new();
    for e in std::fs::read_dir(&sidecar_dir)
        .map_err(|e| format!("no sidecar output at {}: {e}", sidecar_dir.display()))?
        .flatten()
    {
        let text = std::fs::read_to_string(e.path())
            .map_err(|e2| format!("read {}: {e2}", e.path().display()))?;
        models.push(Model::parse(&text)?);
    }
    models.sort_by(|a, b| a.root.cmp(&b.root));
    if models.is_empty() {
        return Err("the build emitted no sidecar files -- does the crate have an #[arael(root)]?".to_string());
    }
    Ok(models)
}

/// Every root by default; `--root` narrows to one (flat single-root
/// layout).
fn pick<'m>(models: &'m [Model], root: Option<&str>) -> Result<Vec<&'m Model>, String> {
    match root {
        Some(r) => models.iter().find(|m| m.root == r)
            .map(|m| vec![m])
            .ok_or_else(|| format!("no root `{r}` among: {}",
                models.iter().map(|m| m.root.as_str()).collect::<Vec<_>>().join(", "))),
        None => Ok(models.iter().collect()),
    }
}

pub fn run_export(dir: &Path, root: Option<&str>) -> Result<(), String> {
    let (crate_name, arael_dep, ns) = scan_manifest(dir)?;
    stub_capi(dir, &crate_name)?;
    let models = harvest(dir)?;
    let picked = pick(&models, root)?;
    let files = generate(&picked, &crate_name, &arael_dep, ns.as_deref())?;
    let mut unchanged = 0usize;
    for (rel, content) in &files {
        let path = dir.join(rel);
        let on_disk = std::fs::read_to_string(&path).ok();
        match write_action(rel, on_disk.as_deref(), content) {
            WriteAction::Refuse => {
                return Err(format!(
                    "{} exists and does not look generated -- refusing to overwrite",
                    path.display()));
            }
            WriteAction::Keep => {
                if on_disk.as_deref() != Some(content.as_str()) {
                    println!("kept {} (written once -- delete it to regenerate)",
                        path.display());
                }
            }
            WriteAction::Unchanged => unchanged += 1,
            WriteAction::Write => {
                if let Some(parent) = path.parent() {
                    std::fs::create_dir_all(parent).map_err(|e| format!("mkdir: {e}"))?;
                }
                std::fs::write(&path, content)
                    .map_err(|e| format!("write {}: {e}", path.display()))?;
                println!("wrote {}", path.display());
            }
        }
    }
    if unchanged > 0 {
        println!("{unchanged} of {} files unchanged, left untouched", files.len());
    }
    Ok(())
}

pub fn run_check(dir: &Path, root: Option<&str>) -> Result<(), String> {
    let (crate_name, arael_dep, ns) = scan_manifest(dir)?;
    let models = harvest(dir)?;
    let picked = pick(&models, root)?;
    let files = generate(&picked, &crate_name, &arael_dep, ns.as_deref())?;
    let mut stale = Vec::new();
    for (rel, content) in &files {
        let path = dir.join(rel);
        let on_disk = std::fs::read_to_string(&path).ok();
        match write_action(rel, on_disk.as_deref(), content) {
            // A kept scaffold is user-owned: only its absence is stale.
            WriteAction::Keep | WriteAction::Unchanged => {}
            _ => {
                if on_disk.as_deref() != Some(content.as_str()) {
                    stale.push(rel.display().to_string());
                }
            }
        }
    }
    if stale.is_empty() {
        println!("generated interface is up to date");
        Ok(())
    } else {
        Err(format!("stale generated files (rerun `cargo arael export`): {}",
            stale.join(", ")))
    }
}
