//! The export pipeline: build the model crate with the sidecar
//! enabled, harvest the JSON, emit the generated tree (capi crate,
//! C++ header, vendored math headers). `check` regenerates in memory
//! and diffs against the committed tree.

use crate::ir::Model;
use std::path::{Path, PathBuf};

const MARKER: &str = "GENERATED by cargo-arael";

/// The vendored math headers, embedded so an installed binary is
/// self-contained.
const MATH_HEADERS: &[(&str, &str)] = &[
    ("vect.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/vect.hpp"))),
    ("matrix.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/matrix.hpp"))),
    ("quatern.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/quatern.hpp"))),
    ("math.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/math.hpp"))),
    ("result.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/result.hpp"))),
    ("assert.hpp", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/headers/arael/assert.hpp"))),
];

/// Minimal Cargo.toml scan: `name = "..."` in [package], and the
/// `arael = ...` dependency line from [dependencies].
fn scan_manifest(dir: &Path) -> Result<(String, String), String> {
    let text = std::fs::read_to_string(dir.join("Cargo.toml"))
        .map_err(|e| format!("read {}/Cargo.toml: {e}", dir.display()))?;
    let mut section = String::new();
    let mut name = None;
    let mut arael_dep = None;
    for line in text.lines() {
        let t = line.trim();
        if t.starts_with('[') {
            section = t.to_string();
            continue;
        }
        if section == "[package]" && t.starts_with("name") {
            if let Some(v) = t.split('"').nth(1) {
                name = Some(v.to_string());
            }
        }
        if section == "[dependencies]"
            && (t.starts_with("arael ") || t.starts_with("arael="))
        {
            arael_dep = Some(t.split_once('=').map(|(_, v)| v.trim().to_string())
                .ok_or("malformed arael dependency line")?);
        }
    }
    let name = name.ok_or("no [package] name in Cargo.toml")?;
    let arael_dep = arael_dep.ok_or("no `arael` entry under [dependencies]")?;
    Ok((name, arael_dep))
}

/// The generated files for one model, as (relative path, content).
pub fn generate(model: &Model, crate_name: &str, arael_dep: &str) -> Result<Vec<(PathBuf, String)>, String> {
    let rust_ident = crate_name.replace('-', "_");
    let ffi = crate::emit_ffi::emit(model, &rust_ident)?;
    let hpp = crate::emit_hpp::emit(model)?;
    let root_sn = crate::ir::snake(&model.root);

    let arael_dep = if arael_dep.contains("path = \"") && !arael_dep.contains("path = \"/") {
        // Relative path dep: the capi crate is one directory deeper.
        arael_dep.replacen("path = \"", "path = \"../", 1)
    } else {
        arael_dep.to_string()
    };

    let capi_toml = format!(
"# {MARKER}: shim crate for the `{root}` model. Do not edit.
[package]
name = \"{crate_name}-capi\"
version = \"0.1.0\"
edition = \"2021\"

[lib]
crate-type = [\"cdylib\", \"staticlib\"]

[dependencies]
{crate_name} = {{ path = \"..\" }}
arael = {arael_dep}
",
        root = model.root);

    let mut files = vec![
        (PathBuf::from("capi/Cargo.toml"), capi_toml),
        (PathBuf::from("capi/src/lib.rs"), ffi),
        (PathBuf::from(format!("cxx/include/{root_sn}.hpp")), hpp),
    ];
    for (name, content) in MATH_HEADERS {
        // Vendored copy: the marker line makes it overwritable on
        // regeneration (the source of truth ships with cargo-arael).
        let stamped = format!("// {MARKER} (vendored math header). Do not edit.\n{content}");
        files.push((PathBuf::from(format!("cxx/include/arael/{name}")), stamped));
    }
    Ok(files)
}

/// Build the model crate with the sidecar enabled and read the JSONs.
fn harvest(dir: &Path) -> Result<Vec<Model>, String> {
    // The env var is not in cargo's fingerprint: touch the sources so
    // the crate re-expands.
    let src = dir.join("src");
    if let Ok(entries) = std::fs::read_dir(&src) {
        for e in entries.flatten() {
            let p = e.path();
            if p.extension().is_some_and(|x| x == "rs") {
                let _ = std::fs::OpenOptions::new().append(true).open(&p)
                    .and_then(|f| f.set_modified(std::time::SystemTime::now()));
            }
        }
    }
    let sidecar_dir = dir.join("target/arael-sidecar");
    let _ = std::fs::remove_dir_all(&sidecar_dir);
    let status = std::process::Command::new("cargo")
        .arg("build")
        .current_dir(dir)
        .env("ARAEL_SIDECAR_DIR", &sidecar_dir)
        .status()
        .map_err(|e| format!("cargo build: {e}"))?;
    if !status.success() {
        return Err("cargo build failed".to_string());
    }
    let mut models = Vec::new();
    for e in std::fs::read_dir(&sidecar_dir)
        .map_err(|e| format!("no sidecar output at {}: {e}", sidecar_dir.display()))?
        .flatten()
    {
        let text = std::fs::read_to_string(e.path())
            .map_err(|e2| format!("read {}: {e2}", e.path().display()))?;
        models.push(Model::parse(&text)?);
    }
    models.sort_by(|a, b| a.root.cmp(&b.root));
    if models.is_empty() {
        return Err("the build emitted no sidecar files -- does the crate have an #[arael(root)]?".to_string());
    }
    Ok(models)
}

fn pick<'m>(models: &'m [Model], root: Option<&str>) -> Result<&'m Model, String> {
    match root {
        Some(r) => models.iter().find(|m| m.root == r)
            .ok_or_else(|| format!("no root `{r}` among: {}",
                models.iter().map(|m| m.root.as_str()).collect::<Vec<_>>().join(", "))),
        None if models.len() == 1 => Ok(&models[0]),
        None => Err(format!("several roots ({}) -- pick one with --root",
            models.iter().map(|m| m.root.as_str()).collect::<Vec<_>>().join(", "))),
    }
}

pub fn run_export(dir: &Path, root: Option<&str>) -> Result<(), String> {
    let (crate_name, arael_dep) = scan_manifest(dir)?;
    let models = harvest(dir)?;
    let model = pick(&models, root)?;
    let files = generate(model, &crate_name, &arael_dep)?;
    for (rel, content) in &files {
        let path = dir.join(rel);
        if path.exists() {
            let old = std::fs::read_to_string(&path).unwrap_or_default();
            if !old.contains(MARKER) {
                return Err(format!(
                    "{} exists and does not look generated -- refusing to overwrite",
                    path.display()));
            }
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| format!("mkdir: {e}"))?;
        }
        std::fs::write(&path, content).map_err(|e| format!("write {}: {e}", path.display()))?;
        println!("wrote {}", path.display());
    }
    Ok(())
}

pub fn run_check(dir: &Path, root: Option<&str>) -> Result<(), String> {
    let (crate_name, arael_dep) = scan_manifest(dir)?;
    let models = harvest(dir)?;
    let model = pick(&models, root)?;
    let files = generate(model, &crate_name, &arael_dep)?;
    let mut stale = Vec::new();
    for (rel, content) in &files {
        let path = dir.join(rel);
        let on_disk = std::fs::read_to_string(&path).unwrap_or_default();
        if on_disk != *content {
            stale.push(rel.display().to_string());
        }
    }
    if stale.is_empty() {
        println!("generated interface is up to date");
        Ok(())
    } else {
        Err(format!("stale generated files (rerun `cargo arael export`): {}",
            stale.join(", ")))
    }
}
