// GENERATED by cargo-arael from the `Decay` / `Line` model sidecars. Do not edit;
// regenerate with `cargo arael export` (check drift with `cargo arael check`).
#![allow(clippy::all)]
#![allow(dead_code, unused_imports, unused_variables)]

use std::cell::RefCell;
use std::rc::Rc;
use wasm_bindgen::prelude::*;
use arael::covariance::{CovAssembly, CovMode, CovOptions, CovOrdering, Covariance as _};
use arael::simple_lm::{LmProblem, LmStatus, RootProblem, SparseFaer, SparseFaerOptions};
use cxx_mr as m;

#[wasm_bindgen(start)]
pub fn __arael_start() {
    console_error_panic_hook::set_once();
}

fn js_err(msg: &str) -> JsValue {
    js_sys::Error::new(msg).into()
}

fn stale() -> JsValue {
    js_err("stale handle: the element it addressed is gone")
}

fn js_set(o: &js_sys::Object, key: &str, v: &JsValue) {
    let _ = js_sys::Reflect::set(o, &JsValue::from_str(key), v);
}

fn js_obj(pairs: &[(&str, f64)]) -> JsValue {
    let o = js_sys::Object::new();
    for (k, v) in pairs {
        js_set(&o, k, &JsValue::from_f64(*v));
    }
    o.into()
}

fn js_opt(v: Option<f64>) -> JsValue {
    match v {
        Some(x) => JsValue::from_f64(x),
        None => JsValue::UNDEFINED,
    }
}

fn js_num(v: &JsValue, key: &str) -> Result<f64, JsValue> {
    js_sys::Reflect::get(v, &JsValue::from_str(key))?
        .as_f64()
        .ok_or_else(|| js_err(&format!("`{key}` is not a number")))
}

fn js_at(v: &JsValue, i: usize) -> Result<JsValue, JsValue> {
    js_sys::Reflect::get_u32(v, i as u32)
}

fn js_num_at(v: &JsValue, i: usize) -> Result<f64, JsValue> {
    js_at(v, i)?.as_f64().ok_or_else(|| js_err(&format!("element {i} is not a number")))
}

/// A dense matrix as a row-major typed array.
fn dense_to_js(rows: usize, cols: usize, at: impl Fn(usize, usize) -> f64) -> js_sys::Float64Array {
    let mut v = Vec::with_capacity(rows * cols);
    for i in 0..rows {
        for j in 0..cols {
            v.push(at(i, j));
        }
    }
    js_sys::Float64Array::from(&v[..])
}

/// A scalar that crosses as a JavaScript number.
trait Js: arael::utils::Float {
    fn to(self) -> f64;
    fn of(v: f64) -> Self;
}
impl Js for f64 {
    fn to(self) -> f64 { self }
    fn of(v: f64) -> Self { v }
}
impl Js for f32 {
    fn to(self) -> f64 { self as f64 }
    fn of(v: f64) -> Self { v as f32 }
}

fn vect2_to_js<T: Js>(v: arael::vect::vect2<T>) -> JsValue {
    js_obj(&[("x", v.x.to()), ("y", v.y.to())])
}
fn vect2_from_js<T: Js>(v: &JsValue) -> Result<arael::vect::vect2<T>, JsValue> {
    Ok(arael::vect::vect2::new(T::of(js_num(v, "x")?), T::of(js_num(v, "y")?)))
}
fn vect3_to_js<T: Js>(v: arael::vect::vect3<T>) -> JsValue {
    js_obj(&[("x", v.x.to()), ("y", v.y.to()), ("z", v.z.to())])
}
fn vect3_from_js<T: Js>(v: &JsValue) -> Result<arael::vect::vect3<T>, JsValue> {
    Ok(arael::vect::vect3::new(T::of(js_num(v, "x")?), T::of(js_num(v, "y")?), T::of(js_num(v, "z")?)))
}
/// A quaternion crosses as `{t, x, y, z}`, the scalar part first.
fn quat_to_js<T: Js>(q: arael::quatern::quatern<T>) -> JsValue {
    js_obj(&[("t", q.t.to()), ("x", q.v.x.to()), ("y", q.v.y.to()), ("z", q.v.z.to())])
}
fn quat_from_js<T: Js>(v: &JsValue) -> Result<arael::quatern::quatern<T>, JsValue> {
    Ok(arael::quatern::quatern::new(
        T::of(js_num(v, "t")?),
        arael::vect::vect3::new(T::of(js_num(v, "x")?), T::of(js_num(v, "y")?), T::of(js_num(v, "z")?)),
    ))
}
fn rows_to_js(rows: &[Vec<f64>]) -> JsValue {
    let outer = js_sys::Array::new();
    for r in rows {
        let inner = js_sys::Array::new();
        for x in r {
            inner.push(&JsValue::from_f64(*x));
        }
        outer.push(&inner);
    }
    outer.into()
}
fn rows_from_js(v: &JsValue, r: usize, c: usize) -> Result<Vec<Vec<f64>>, JsValue> {
    let mut out = Vec::with_capacity(r);
    for i in 0..r {
        let row = js_at(v, i)?;
        let mut vals = Vec::with_capacity(c);
        for j in 0..c {
            vals.push(js_num_at(&row, j)?);
        }
        out.push(vals);
    }
    Ok(out)
}
/// A matrix crosses as an array of row arrays.
fn mat2_to_js<T: Js>(m: arael::matrix::matrix2<T>) -> JsValue {
    rows_to_js(&[vec![m.rows[0].x.to(), m.rows[0].y.to()], vec![m.rows[1].x.to(), m.rows[1].y.to()]])
}
fn mat2_from_js<T: Js>(v: &JsValue) -> Result<arael::matrix::matrix2<T>, JsValue> {
    let r = rows_from_js(v, 2, 2)?;
    Ok(arael::matrix::matrix2::from_elements(T::of(r[0][0]), T::of(r[0][1]), T::of(r[1][0]), T::of(r[1][1])))
}
fn mat3_to_js<T: Js>(m: arael::matrix::matrix3<T>) -> JsValue {
    rows_to_js(&[
        vec![m.rows[0].x.to(), m.rows[0].y.to(), m.rows[0].z.to()],
        vec![m.rows[1].x.to(), m.rows[1].y.to(), m.rows[1].z.to()],
        vec![m.rows[2].x.to(), m.rows[2].y.to(), m.rows[2].z.to()],
    ])
}
fn mat3_from_js<T: Js>(v: &JsValue) -> Result<arael::matrix::matrix3<T>, JsValue> {
    let r = rows_from_js(v, 3, 3)?;
    Ok(arael::matrix::matrix3::from_array(std::array::from_fn(|i| std::array::from_fn(|j| T::of(r[i][j])))))
}
fn vecn_to_js<T: Js, const N: usize>(v: arael::vect::vect<T, N>) -> JsValue {
    let arr = js_sys::Array::new();
    for x in v.e {
        arr.push(&JsValue::from_f64(x.to()));
    }
    arr.into()
}
fn vecn_from_js<T: Js, const N: usize>(v: &JsValue) -> Result<arael::vect::vect<T, N>, JsValue> {
    let mut e = [T::of(0.0); N];
    for (i, x) in e.iter_mut().enumerate() {
        *x = T::of(js_num_at(v, i)?);
    }
    Ok(arael::vect::vect { e })
}
fn matn_to_js<T: Js, const R: usize, const C: usize>(m: arael::matrix::matrix<T, R, C>) -> JsValue {
    let rows: Vec<Vec<f64>> = m.rows.iter().map(|r| r.e.iter().map(|x| x.to()).collect()).collect();
    rows_to_js(&rows)
}
fn matn_from_js<T: Js, const R: usize, const C: usize>(v: &JsValue) -> Result<arael::matrix::matrix<T, R, C>, JsValue> {
    let r = rows_from_js(v, R, C)?;
    Ok(arael::matrix::matrix {
        rows: std::array::from_fn(|i| arael::vect::vect { e: std::array::from_fn(|j| T::of(r[i][j])) }),
    })
}

/// A value's flat form, for the bulk accessors.
trait Flat {
    fn flat(&self, out: &mut Vec<f64>);
    fn unflat(c: &[f64]) -> Self;
}
impl<T: Js> Flat for arael::vect::vect2<T> {
    fn flat(&self, out: &mut Vec<f64>) { out.extend([self.x.to(), self.y.to()]); }
    fn unflat(c: &[f64]) -> Self { arael::vect::vect2::new(T::of(c[0]), T::of(c[1])) }
}
impl<T: Js> Flat for arael::vect::vect3<T> {
    fn flat(&self, out: &mut Vec<f64>) { out.extend([self.x.to(), self.y.to(), self.z.to()]); }
    fn unflat(c: &[f64]) -> Self { arael::vect::vect3::new(T::of(c[0]), T::of(c[1]), T::of(c[2])) }
}
impl<T: Js> Flat for arael::quatern::quatern<T> {
    fn flat(&self, out: &mut Vec<f64>) { out.extend([self.t.to(), self.v.x.to(), self.v.y.to(), self.v.z.to()]); }
    fn unflat(c: &[f64]) -> Self {
        arael::quatern::quatern::new(T::of(c[0]), arael::vect::vect3::new(T::of(c[1]), T::of(c[2]), T::of(c[3])))
    }
}
impl<T: Js> Flat for arael::matrix::matrix2<T> {
    fn flat(&self, out: &mut Vec<f64>) {
        out.extend([self.rows[0].x.to(), self.rows[0].y.to(), self.rows[1].x.to(), self.rows[1].y.to()]);
    }
    fn unflat(c: &[f64]) -> Self {
        arael::matrix::matrix2::from_elements(T::of(c[0]), T::of(c[1]), T::of(c[2]), T::of(c[3]))
    }
}
impl<T: Js> Flat for arael::matrix::matrix3<T> {
    fn flat(&self, out: &mut Vec<f64>) {
        for r in &self.rows {
            out.extend([r.x.to(), r.y.to(), r.z.to()]);
        }
    }
    fn unflat(c: &[f64]) -> Self {
        arael::matrix::matrix3::from_array(std::array::from_fn(|i| std::array::from_fn(|j| T::of(c[i * 3 + j]))))
    }
}
impl<T: Js, const N: usize> Flat for arael::vect::vect<T, N> {
    fn flat(&self, out: &mut Vec<f64>) { out.extend(self.e.iter().map(|x| x.to())); }
    fn unflat(c: &[f64]) -> Self { arael::vect::vect { e: std::array::from_fn(|i| T::of(c[i])) } }
}
impl<T: Js, const R: usize, const C: usize> Flat for arael::matrix::matrix<T, R, C> {
    fn flat(&self, out: &mut Vec<f64>) {
        for r in &self.rows {
            out.extend(r.e.iter().map(|x| x.to()));
        }
    }
    fn unflat(c: &[f64]) -> Self {
        arael::matrix::matrix {
            rows: std::array::from_fn(|i| arael::vect::vect { e: std::array::from_fn(|j| T::of(c[i * C + j])) }),
        }
    }
}

fn status_code(s: &LmStatus) -> i32 {
    match s {
        LmStatus::Converged => 0,
        LmStatus::CostThreshold => 1,
        LmStatus::MaxIterations => 2,
        LmStatus::GradientTolerance => 3,
        LmStatus::ParameterTolerance => 4,
        LmStatus::PredictedReduction => 5,
        LmStatus::LambdaCeiling => 6,
        LmStatus::DriverTerminated => 7,
        LmStatus::ObserverTerminated => 8,
        LmStatus::TimeLimit => 9,
        LmStatus::RetryBudgetExhausted => 10,
        LmStatus::Aborted => 11,
    }
}

// ---------------------------------------------------------------- Decay
pub mod decay {
use super::*;

/// A handle's way to its element: through the model, mutably.
type At<T> = Rc<dyn for<'a> Fn(&'a mut m::Decay) -> Option<&'a mut T>>;
/// The same, shared.
type See<T> = Rc<dyn for<'a> Fn(&'a m::Decay) -> Option<&'a T>>;

fn mk_at<T>(f: impl for<'a> Fn(&'a mut m::Decay) -> Option<&'a mut T> + 'static) -> At<T> {
    Rc::new(f)
}
fn mk_see<T>(f: impl for<'a> Fn(&'a m::Decay) -> Option<&'a T> + 'static) -> See<T> {
    Rc::new(f)
}

fn preset_config(preset: u32) -> arael::simple_lm::LmConfig<f32> {
    match preset {
        1 => arael::simple_lm::LmConfig::conservative(),
        2 => arael::simple_lm::LmConfig::well_conditioned(),
        3 => arael::simple_lm::LmConfig::ill_conditioned(),
        _ => arael::simple_lm::LmConfig::default(),
    }
}

fn failure(f: arael::simple_lm::SolveFailure<f32>) -> JsValue {
    js_err(&f.to_string())
}

/// The `Decay` model and its solver entries.
#[wasm_bindgen]
pub struct DecayDecay {
    root: Rc<RefCell<m::Decay>>,
}

#[wasm_bindgen]
impl DecayDecay {
    #[wasm_bindgen(constructor)]
    pub fn new() -> DecayDecay {
        DecayDecay { root: Rc::new(RefCell::new(Default::default())) }
    }
    fn with<R>(&self, f: impl FnOnce(&mut m::Decay) -> R) -> Result<R, JsValue> {
        let mut g = self.root.borrow_mut();
        Ok(f(&mut *g))
    }
    /// The cost at the current parameters.
    pub fn cost(&self) -> f64 {
        let mut g = self.root.borrow_mut();
        let mut params = Vec::new();
        g.serialize(&mut params);
        g.calc_cost(&params) as f64
    }
    /// The model's diagnostics as text; empty when clean.
    pub fn validate(&self) -> String {
        let mut g = self.root.borrow_mut();
        let d = g.validate();
        if d.is_clean() { String::new() } else { d.to_string() }
    }
    #[wasm_bindgen(js_name = "solveDense")]
    pub fn solve_dense(&self, cfg: &DecayLmConfig) -> Result<DecayLmResult, JsValue> {
        let c = cfg.to_config();
        let mut g = self.root.borrow_mut();
        g.solve_dense(&c).map(|r| DecayLmResult { r }).map_err(failure)
    }
    /// The sparse solve, with the backend's defaults or `opts`.
    #[wasm_bindgen(js_name = "solveSparse")]
    pub fn solve_sparse(&self, cfg: &DecayLmConfig, opts: Option<DecaySparseOptions>) -> Result<DecayLmResult, JsValue> {
        let c = cfg.to_config();
        let mut g = self.root.borrow_mut();
        let r = match opts {
            None => g.solve_sparse(&c),
            Some(o) => {
                let mut s = SparseFaer::<f32>::from_options(&o.to_options()?);
                g.solve_with(&mut s, &c)
            }
        };
        r.map(|r| DecayLmResult { r }).map_err(failure)
    }
    /// The band solve, `kd` the half-bandwidth in scalar parameters.
    #[wasm_bindgen(js_name = "solveBand")]
    pub fn solve_band(&self, kd: u32, cfg: &DecayLmConfig) -> Result<DecayLmResult, JsValue> {
        let c = cfg.to_config();
        let mut g = self.root.borrow_mut();
        g.solve_with(&mut arael::simple_lm::Band::new(kd as usize), &c)
            .map(|r| DecayLmResult { r })
            .map_err(failure)
    }
    /// The covariance at the current parameters; `mode` 0 PerQuery,
    /// 1 AllMarginals (the default), 2 TriDiagonal.
    #[wasm_bindgen(js_name = "assembleCovariance")]
    pub fn assemble_covariance(&self, mode: Option<u32>) -> Result<DecayCovariance, JsValue> {
        self.assemble_covariance_with(mode.unwrap_or(1), 0, 0)
    }
    /// `assembleCovariance` with the assembly spelled out: `ordering` 0
    /// Auto, 1 Amd, 2 NestedDissection, 3 Natural; `blockSupernodal` 0
    /// Auto, 1 Always, 2 Never.
    #[wasm_bindgen(js_name = "assembleCovarianceWith")]
    pub fn assemble_covariance_with(&self, mode: u32, ordering: u32, block_supernodal: u32) -> Result<DecayCovariance, JsValue> {
        let m = match mode {
            0 => CovMode::PerQuery,
            2 => CovMode::TriDiagonal,
            _ => CovMode::AllMarginals,
        };
        let opts = CovOptions {
            ordering: match ordering {
                1 => CovOrdering::Amd,
                2 => CovOrdering::NestedDissection,
                3 => CovOrdering::Natural,
                _ => CovOrdering::Auto,
            },
            block_supernodal: match block_supernodal {
                1 => arael::simple_lm::BlockSupernodalMode::Always,
                2 => arael::simple_lm::BlockSupernodalMode::Never,
                _ => arael::simple_lm::BlockSupernodalMode::Auto,
            },
        };
        let mut g = self.root.borrow_mut();
        let cov = g.assemble_covariance_with(m, &opts).map_err(|e| js_err(&format!("{}", e)))?;
        Ok(DecayCovariance { cov, root: self.root.clone() })
    }
    /// The `cells` collection.
    #[wasm_bindgen(js_name = "cells")]
    pub fn cells(&self) -> DecayDecayCells {
        DecayDecayCells { root: self.root.clone(), at: mk_at(move |o| { Some(o) }), see: mk_see(move |o| { Some(o) }) }
    }
}

/// The `Decay.cells` collection, `refs::Vec<Cell<f32>>`.
#[wasm_bindgen]
pub struct DecayDecayCells {
    root: Rc<RefCell<m::Decay>>,
    at: At<m::Decay>,
    see: See<m::Decay>,
}

#[wasm_bindgen]
impl DecayDecayCells {
    fn with<R>(&self, f: impl FnOnce(&mut m::Decay) -> R) -> Result<R, JsValue> {
        let mut g = self.root.borrow_mut();
        let o = (self.at)(&mut *g).ok_or_else(stale)?;
        Ok(f(o))
    }
    #[wasm_bindgen(getter)]
    pub fn length(&self) -> Result<u32, JsValue> {
        self.with(|o| o.cells.len() as u32)
    }
    pub fn reserve(&self, additional: u32) -> Result<(), JsValue> {
        self.with(|o| o.cells.reserve(additional as usize))
    }
    pub fn clear(&self) -> Result<(), JsValue> {
        self.with(|o| o.cells.clear())
    }
    /// Append a default `Cell` and hand it back.
    pub fn push(&self) -> Result<DecayCell, JsValue> {
        let r = self.with(|o| o.cells.push(Default::default()).to_raw())?;
        Ok(DecayCell { root: self.root.clone(), at: { let p = self.at.clone(); mk_at(move |g| p(g).and_then(|o| o.cells.get_mut(arael::refs::Ref::from_raw(r)))) }, see: { let p = self.see.clone(); mk_see(move |g| p(g).and_then(|o| o.cells.get(arael::refs::Ref::from_raw(r)))) } })
    }
    /// Append `n` default elements; returns the index of the first.
    #[wasm_bindgen(js_name = "pushN")]
    pub fn push_n(&self, n: u32) -> Result<u32, JsValue> {
        self.with(|o| {
            let first = o.cells.len();
            o.cells.reserve(n as usize);
            for _ in 0..n { o.cells.push(Default::default()); }
            first as u32
        })
    }
    /// The element at index `i`; throws past the end.
    pub fn at(&self, i: u32) -> Result<DecayCell, JsValue> {
        let r = self.with(|o| {
            if (i as usize) < o.cells.len() { Some(o.cells.ref_at(i as usize).to_raw()) } else { None }
        })?.ok_or_else(|| js_err("index past the end"))?;
        Ok(DecayCell { root: self.root.clone(), at: { let p = self.at.clone(); mk_at(move |g| p(g).and_then(|o| o.cells.get_mut(arael::refs::Ref::from_raw(r)))) }, see: { let p = self.see.clone(); mk_see(move |g| p(g).and_then(|o| o.cells.get(arael::refs::Ref::from_raw(r)))) } })
    }
    /// Drops the last element; false when already empty.
    pub fn pop(&self) -> Result<bool, JsValue> {
        self.with(|o| o.cells.pop().is_some())
    }
    pub fn truncate(&self, len: u32) -> Result<(), JsValue> {
        self.with(|o| o.cells.truncate(len as usize))
    }
    /// The ref of the element at `i` as a number; 4294967295 past the end.
    #[wasm_bindgen(js_name = "refAt")]
    pub fn ref_at(&self, i: u32) -> Result<u32, JsValue> {
        self.with(|o| {
            if (i as usize) < o.cells.len() { o.cells.ref_at(i as usize).to_raw() } else { u32::MAX }
        })
    }
    /// The refs of the elements from `start`, `n` of them.
    #[wasm_bindgen(js_name = "getRefsN")]
    pub fn get_refs_n(&self, start: u32, n: u32) -> Result<js_sys::Uint32Array, JsValue> {
        let v = self.with(|o| {
            let (s, n) = (start as usize, n as usize);
            if s + n > o.cells.len() { return Err(js_err("range past the end")); }
            Ok((s..s + n).map(|i| o.cells.ref_at(i).to_raw()).collect::<Vec<u32>>())
        })??;
        Ok(js_sys::Uint32Array::from(&v[..]))
    }
    /// The first_ref element's ref, or 4294967295 when empty.
    #[wasm_bindgen(js_name = "firstRef")]
    pub fn first_ref(&self) -> Result<u32, JsValue> {
        self.with(|o| o.cells.first_ref().map_or(u32::MAX, |r| r.to_raw()))
    }
    /// The last_ref element's ref, or 4294967295 when empty.
    #[wasm_bindgen(js_name = "lastRef")]
    pub fn last_ref(&self) -> Result<u32, JsValue> {
        self.with(|o| o.cells.last_ref().map_or(u32::MAX, |r| r.to_raw()))
    }
    /// The element a ref addresses; throws on a stale or foreign ref.
    pub fn get(&self, r: u32) -> Result<DecayCell, JsValue> {
        if !self.contains(r)? { return Err(js_err("ref does not address a live element")); }
        Ok(DecayCell { root: self.root.clone(), at: { let p = self.at.clone(); mk_at(move |g| p(g).and_then(|o| o.cells.get_mut(arael::refs::Ref::from_raw(r)))) }, see: { let p = self.see.clone(); mk_see(move |g| p(g).and_then(|o| o.cells.get(arael::refs::Ref::from_raw(r)))) } })
    }
    /// The element a ref addresses, or undefined.
    #[wasm_bindgen(js_name = "tryGet")]
    pub fn try_get(&self, r: u32) -> Result<Option<DecayCell>, JsValue> {
        Ok(self.contains(r)?.then(|| DecayCell { root: self.root.clone(), at: { let p = self.at.clone(); mk_at(move |g| p(g).and_then(|o| o.cells.get_mut(arael::refs::Ref::from_raw(r)))) }, see: { let p = self.see.clone(); mk_see(move |g| p(g).and_then(|o| o.cells.get(arael::refs::Ref::from_raw(r)))) } }))
    }
    /// True while `r` addresses a live element of this collection.
    pub fn contains(&self, r: u32) -> Result<bool, JsValue> {
        self.with(|o| o.cells.contains_ref(arael::refs::Ref::from_raw(r)))
    }
    /// `v` of the elements from `start`, `n` of them, 1 value(s) each.
    #[wasm_bindgen(js_name = "getVN")]
    pub fn get_v_n(&self, start: u32, n: u32) -> Result<js_sys::Float64Array, JsValue> {
        let v = self.with(|o| {
            let (s, n) = (start as usize, n as usize);
            if s + n > o.cells.len() { return Err(js_err("range past the end")); }
            let mut out: Vec<f64> = Vec::with_capacity(n * 1);
            for i in s..s + n { let e = &o.cells[i]; out.push(e.v.value as f64); }
            Ok(out)
        })??;
        Ok(js_sys::Float64Array::from(&v[..]))
    }
    /// Set `v` of the elements from `start`, 1 value(s) each.
    #[wasm_bindgen(js_name = "setVN")]
    pub fn set_v_n(&self, start: u32, values: &[f64]) -> Result<(), JsValue> {
        self.with(|o| {
            let s = start as usize;
            let n = values.len() / 1;
            if s + n > o.cells.len() { return Err(js_err("range past the end")); }
            for (k, c) in values.chunks_exact(1).enumerate() { let e = &mut o.cells[s + k]; e.v.value = c[0] as f32; }
            Ok(())
        })?
    }
    /// `v_optimize` of the elements from `start`, `n` of them, 1 value(s) each.
    #[wasm_bindgen(js_name = "getVOptimizeN")]
    pub fn get_v_optimize_n(&self, start: u32, n: u32) -> Result<js_sys::Uint8Array, JsValue> {
        let v = self.with(|o| {
            let (s, n) = (start as usize, n as usize);
            if s + n > o.cells.len() { return Err(js_err("range past the end")); }
            let mut out: Vec<u8> = Vec::with_capacity(n * 1);
            for i in s..s + n { let e = &o.cells[i]; out.push(e.v.optimize as u8); }
            Ok(out)
        })??;
        Ok(js_sys::Uint8Array::from(&v[..]))
    }
    /// Set `v_optimize` of the elements from `start`, 1 value(s) each.
    #[wasm_bindgen(js_name = "setVOptimizeN")]
    pub fn set_v_optimize_n(&self, start: u32, values: &[u8]) -> Result<(), JsValue> {
        self.with(|o| {
            let s = start as usize;
            let n = values.len() / 1;
            if s + n > o.cells.len() { return Err(js_err("range past the end")); }
            for (k, c) in values.chunks_exact(1).enumerate() { let e = &mut o.cells[s + k]; e.v.optimize = c[0] != 0; }
            Ok(())
        })?
    }
    /// `t` of the elements from `start`, `n` of them, 1 value(s) each.
    #[wasm_bindgen(js_name = "getTN")]
    pub fn get_t_n(&self, start: u32, n: u32) -> Result<js_sys::Float64Array, JsValue> {
        let v = self.with(|o| {
            let (s, n) = (start as usize, n as usize);
            if s + n > o.cells.len() { return Err(js_err("range past the end")); }
            let mut out: Vec<f64> = Vec::with_capacity(n * 1);
            for i in s..s + n { let e = &o.cells[i]; out.push(e.t as f64); }
            Ok(out)
        })??;
        Ok(js_sys::Float64Array::from(&v[..]))
    }
    /// Set `t` of the elements from `start`, 1 value(s) each.
    #[wasm_bindgen(js_name = "setTN")]
    pub fn set_t_n(&self, start: u32, values: &[f64]) -> Result<(), JsValue> {
        self.with(|o| {
            let s = start as usize;
            let n = values.len() / 1;
            if s + n > o.cells.len() { return Err(js_err("range past the end")); }
            for (k, c) in values.chunks_exact(1).enumerate() { let e = &mut o.cells[s + k]; e.t = c[0] as f32; }
            Ok(())
        })?
    }
    /// `w` of the elements from `start`, `n` of them, 1 value(s) each.
    #[wasm_bindgen(js_name = "getWN")]
    pub fn get_w_n(&self, start: u32, n: u32) -> Result<js_sys::Float64Array, JsValue> {
        let v = self.with(|o| {
            let (s, n) = (start as usize, n as usize);
            if s + n > o.cells.len() { return Err(js_err("range past the end")); }
            let mut out: Vec<f64> = Vec::with_capacity(n * 1);
            for i in s..s + n { let e = &o.cells[i]; out.push(e.w as f64); }
            Ok(out)
        })??;
        Ok(js_sys::Float64Array::from(&v[..]))
    }
    /// Set `w` of the elements from `start`, 1 value(s) each.
    #[wasm_bindgen(js_name = "setWN")]
    pub fn set_w_n(&self, start: u32, values: &[f64]) -> Result<(), JsValue> {
        self.with(|o| {
            let s = start as usize;
            let n = values.len() / 1;
            if s + n > o.cells.len() { return Err(js_err("range past the end")); }
            for (k, c) in values.chunks_exact(1).enumerate() { let e = &mut o.cells[s + k]; e.w = c[0] as f32; }
            Ok(())
        })?
    }
}

/// A `Cell` in its owner's storage, addressed by key rather than by
/// pointer: the element is re-resolved on every access, so growing the
/// collection cannot leave this handle dangling.
#[wasm_bindgen]
pub struct DecayCell {
    root: Rc<RefCell<m::Decay>>,
    at: At<m::Cell<f32>>,
    see: See<m::Cell<f32>>,
}

#[wasm_bindgen]
impl DecayCell {
    fn with<R>(&self, f: impl FnOnce(&mut m::Cell<f32>) -> R) -> Result<R, JsValue> {
        let mut g = self.root.borrow_mut();
        let e = (self.at)(&mut *g).ok_or_else(stale)?;
        Ok(f(e))
    }
    #[wasm_bindgen(getter, js_name = "v")]
    pub fn v(&self) -> Result<f64, JsValue> {
        self.with(|e| e.v.value as f64)
    }
    #[wasm_bindgen(setter, js_name = "v")]
    pub fn set_v(&self, v: f64) -> Result<(), JsValue> {
        let v = v as f32;
        self.with(|e| { e.v.value = v; })
    }
    #[wasm_bindgen(getter, js_name = "vOptimize")]
    pub fn v_optimize(&self) -> Result<bool, JsValue> {
        self.with(|e| e.v.optimize)
    }
    #[wasm_bindgen(setter, js_name = "vOptimize")]
    pub fn set_v_optimize(&self, v: bool) -> Result<(), JsValue> {
        let v = v;
        self.with(|e| { e.v.optimize = v; })
    }
    #[wasm_bindgen(getter, js_name = "t")]
    pub fn t(&self) -> Result<f64, JsValue> {
        self.with(|e| e.t as f64)
    }
    #[wasm_bindgen(setter, js_name = "t")]
    pub fn set_t(&self, v: f64) -> Result<(), JsValue> {
        let v = v as f32;
        self.with(|e| { e.t = v; })
    }
    #[wasm_bindgen(getter, js_name = "w")]
    pub fn w(&self) -> Result<f64, JsValue> {
        self.with(|e| e.w as f64)
    }
    #[wasm_bindgen(setter, js_name = "w")]
    pub fn set_w(&self, v: f64) -> Result<(), JsValue> {
        let v = v as f32;
        self.with(|e| { e.w = v; })
    }
}

/// The solver configuration: a preset's values, edited field by field.
#[wasm_bindgen]
pub struct DecayLmConfig {
    preset: u32,
    #[wasm_bindgen(js_name = "maxIters")]
    pub max_iters: u32,
    #[wasm_bindgen(js_name = "minIters")]
    pub min_iters: u32,
    pub patience: u32,
    #[wasm_bindgen(js_name = "numThreads")]
    pub num_threads: u32,
    pub verbose: bool,
    #[wasm_bindgen(js_name = "gatherTiming")]
    pub gather_timing: bool,
    #[wasm_bindgen(js_name = "absPrecision")]
    pub abs_precision: f64,
    #[wasm_bindgen(js_name = "relPrecision")]
    pub rel_precision: f64,
    #[wasm_bindgen(js_name = "initialLambda")]
    pub initial_lambda: f64,
    #[wasm_bindgen(js_name = "costThreshold")]
    pub cost_threshold: f64,
    #[wasm_bindgen(js_name = "lambdaFloor")]
    pub lambda_floor: f64,
    gradient_tolerance: Option<f64>,
    parameter_tolerance: Option<f64>,
    predicted_reduction_tolerance: Option<f64>,
    min_diagonal: Option<f64>,
    time_limit_seconds: Option<f64>,
    assembly_threads: Option<u32>,
    max_accepted_iters: Option<u32>,
}

#[wasm_bindgen]
impl DecayLmConfig {
    fn from_preset(preset: u32) -> DecayLmConfig {
        let c = preset_config(preset);
        DecayLmConfig {
            preset,
            max_iters: c.max_iters as u32,
            min_iters: c.min_iters as u32,
            patience: c.patience as u32,
            num_threads: c.num_threads as u32,
            verbose: c.verbose,
            gather_timing: c.gather_timing,
            abs_precision: c.abs_precision as f64,
            rel_precision: c.rel_precision as f64,
            initial_lambda: c.initial_lambda as f64,
            cost_threshold: c.cost_threshold as f64,
            lambda_floor: c.lambda_floor as f64,
            gradient_tolerance: c.gradient_tolerance.map(|v| v as f64),
            parameter_tolerance: c.parameter_tolerance.map(|v| v as f64),
            predicted_reduction_tolerance: c.predicted_reduction_tolerance.map(|v| v as f64),
            min_diagonal: c.min_diagonal.map(|v| v as f64),
            time_limit_seconds: c.time_limit.map(|d| d.as_secs_f64()),
            assembly_threads: c.assembly_threads.map(|n| n as u32),
            max_accepted_iters: c.max_accepted_iters.map(|n| n as u32),
        }
    }
    fn to_config(&self) -> arael::simple_lm::LmConfig<f32> {
        let mut c = preset_config(self.preset);
        c.max_iters = self.max_iters as usize;
        c.min_iters = self.min_iters as usize;
        c.patience = self.patience as usize;
        c.num_threads = self.num_threads as usize;
        c.assembly_threads = self.assembly_threads.map(|n| n as usize);
        c.max_accepted_iters = self.max_accepted_iters.map(|n| n as usize);
        c.verbose = self.verbose;
        c.gather_timing = self.gather_timing;
        c.abs_precision = self.abs_precision as f32;
        c.rel_precision = self.rel_precision as f32;
        c.initial_lambda = self.initial_lambda as f32;
        c.cost_threshold = self.cost_threshold as f32;
        c.lambda_floor = self.lambda_floor as f32;
        c.gradient_tolerance = self.gradient_tolerance.map(|v| v as f32);
        c.parameter_tolerance = self.parameter_tolerance.map(|v| v as f32);
        c.predicted_reduction_tolerance = self.predicted_reduction_tolerance.map(|v| v as f32);
        c.min_diagonal = self.min_diagonal.map(|v| v as f32);
        c.time_limit = self.time_limit_seconds.map(std::time::Duration::from_secs_f64);
        c
    }
    /// The defaults.
    #[wasm_bindgen(constructor)]
    pub fn new() -> DecayLmConfig { Self::from_preset(0) }
    pub fn defaults() -> DecayLmConfig { Self::from_preset(0) }
    pub fn conservative() -> DecayLmConfig { Self::from_preset(1) }
    #[wasm_bindgen(js_name = "wellConditioned")]
    pub fn well_conditioned() -> DecayLmConfig { Self::from_preset(2) }
    #[wasm_bindgen(js_name = "illConditioned")]
    pub fn ill_conditioned() -> DecayLmConfig { Self::from_preset(3) }
    #[wasm_bindgen(getter, js_name = "gradientTolerance")]
    pub fn gradient_tolerance(&self) -> Option<f64> { self.gradient_tolerance }
    #[wasm_bindgen(setter, js_name = "gradientTolerance")]
    pub fn set_gradient_tolerance(&mut self, v: Option<f64>) { self.gradient_tolerance = v; }
    #[wasm_bindgen(getter, js_name = "parameterTolerance")]
    pub fn parameter_tolerance(&self) -> Option<f64> { self.parameter_tolerance }
    #[wasm_bindgen(setter, js_name = "parameterTolerance")]
    pub fn set_parameter_tolerance(&mut self, v: Option<f64>) { self.parameter_tolerance = v; }
    #[wasm_bindgen(getter, js_name = "predictedReductionTolerance")]
    pub fn predicted_reduction_tolerance(&self) -> Option<f64> { self.predicted_reduction_tolerance }
    #[wasm_bindgen(setter, js_name = "predictedReductionTolerance")]
    pub fn set_predicted_reduction_tolerance(&mut self, v: Option<f64>) { self.predicted_reduction_tolerance = v; }
    #[wasm_bindgen(getter, js_name = "minDiagonal")]
    pub fn min_diagonal(&self) -> Option<f64> { self.min_diagonal }
    #[wasm_bindgen(setter, js_name = "minDiagonal")]
    pub fn set_min_diagonal(&mut self, v: Option<f64>) { self.min_diagonal = v; }
    #[wasm_bindgen(getter, js_name = "timeLimitSeconds")]
    pub fn time_limit_seconds(&self) -> Option<f64> { self.time_limit_seconds }
    #[wasm_bindgen(setter, js_name = "timeLimitSeconds")]
    pub fn set_time_limit_seconds(&mut self, v: Option<f64>) { self.time_limit_seconds = v; }
    #[wasm_bindgen(getter, js_name = "assemblyThreads")]
    pub fn assembly_threads(&self) -> Option<u32> { self.assembly_threads }
    #[wasm_bindgen(setter, js_name = "assemblyThreads")]
    pub fn set_assembly_threads(&mut self, v: Option<u32>) { self.assembly_threads = v; }
    #[wasm_bindgen(getter, js_name = "maxAcceptedIters")]
    pub fn max_accepted_iters(&self) -> Option<u32> { self.max_accepted_iters }
    #[wasm_bindgen(setter, js_name = "maxAcceptedIters")]
    pub fn set_max_accepted_iters(&mut self, v: Option<u32>) { self.max_accepted_iters = v; }
}

/// The sparse backend's options as plain data, starting from the Rust
/// defaults. The enum fields carry the tags of the C ABI: schur 0 Auto,
/// 1 Force, 2 Never; ordering 0 Auto, 1 Amd, 2 MarginalizeFirst,
/// 3 Natural, 4 NestedDissection; envelope 0 Auto, 1 Always, 2 Never;
/// schurSolve 0 Factorize, 1 Iterative, 2 IterativeImplicit;
/// blockSupernodal 0 Auto, 1 Always, 2 Never.
#[wasm_bindgen]
pub struct DecaySparseOptions {
    pub schur: u32,
    pub ordering: u32,
    pub envelope: u32,
    #[wasm_bindgen(js_name = "envelopePanelWidth")]
    pub envelope_panel_width: u32,
    pub supernodal: bool,
    #[wasm_bindgen(js_name = "narrowBand")]
    pub narrow_band: bool,
    #[wasm_bindgen(js_name = "flopMargin")]
    pub flop_margin: f64,
    #[wasm_bindgen(js_name = "obviousFlopRatio")]
    pub obvious_flop_ratio: f64,
    #[wasm_bindgen(js_name = "cgTol")]
    pub cg_tol: f64,
    #[wasm_bindgen(js_name = "schurSolve")]
    pub schur_solve: u32,
    #[wasm_bindgen(js_name = "cgMaxIters")]
    pub cg_max_iters: u32,
    #[wasm_bindgen(js_name = "cgRestartEvery")]
    pub cg_restart_every: u32,
    #[wasm_bindgen(js_name = "blockSupernodal")]
    pub block_supernodal: u32,
    #[wasm_bindgen(js_name = "blockSupernodalBatch")]
    pub block_supernodal_batch: f64,
    #[wasm_bindgen(js_name = "blockSupernodalMemoryLean")]
    pub block_supernodal_memory_lean: bool,
}

#[wasm_bindgen]
impl DecaySparseOptions {
    /// The Rust defaults.
    #[wasm_bindgen(constructor)]
    pub fn new() -> DecaySparseOptions {
        use arael::simple_lm::{BlockSupernodalMode, EnvelopeMode, SolveOrdering, SchurPolicy};
        let d = SparseFaerOptions::default();
        let (flop_margin, obvious_flop_ratio) = match d.policy {
            SchurPolicy::Auto { flop_margin, obvious_flop_ratio } => (flop_margin, obvious_flop_ratio),
            _ => (0.0, 0.0),
        };
        DecaySparseOptions {
            schur: match d.policy {
                SchurPolicy::Auto { .. } => 0,
                SchurPolicy::Force => 1,
                SchurPolicy::Never => 2,
            },
            ordering: match d.ordering {
                SolveOrdering::Auto => 0,
                SolveOrdering::Amd => 1,
                SolveOrdering::MarginalizeFirst => 2,
                SolveOrdering::Natural => 3,
                SolveOrdering::NestedDissection => 4,
            },
            envelope: match d.envelope {
                EnvelopeMode::Auto => 0,
                EnvelopeMode::Always => 1,
                EnvelopeMode::Never => 2,
            },
            envelope_panel_width: d.envelope_panel_width.unwrap_or(0) as u32,
            supernodal: d.scalar_supernodal,
            narrow_band: d.narrow_band,
            flop_margin,
            obvious_flop_ratio,
            cg_tol: arael::simple_lm::CgOptions::default().tol,
            schur_solve: 0,
            cg_max_iters: 0,
            cg_restart_every: 0,
            block_supernodal: match d.block_supernodal {
                BlockSupernodalMode::Auto => 0,
                BlockSupernodalMode::Always => 1,
                BlockSupernodalMode::Never => 2,
            },
            block_supernodal_batch: d.block_supernodal_batch.unwrap_or(0.0),
            block_supernodal_memory_lean: d.block_supernodal_memory_lean,
        }
    }
    fn to_options(&self) -> Result<SparseFaerOptions, JsValue> {
        use arael::simple_lm::{BlockSupernodalMode, EnvelopeMode, SolveOrdering, SchurPolicy};
        let policy = match self.schur {
            0 => SchurPolicy::Auto { flop_margin: self.flop_margin, obvious_flop_ratio: self.obvious_flop_ratio },
            1 => SchurPolicy::Force,
            2 => SchurPolicy::Never,
            t => return Err(js_err(&format!("unknown schur policy tag {t}"))),
        };
        let ordering = match self.ordering {
            0 => SolveOrdering::Auto,
            1 => SolveOrdering::Amd,
            2 => SolveOrdering::MarginalizeFirst,
            3 => SolveOrdering::Natural,
            4 => SolveOrdering::NestedDissection,
            t => return Err(js_err(&format!("unknown ordering tag {t}"))),
        };
        let envelope = match self.envelope {
            0 => EnvelopeMode::Auto,
            1 => EnvelopeMode::Always,
            2 => EnvelopeMode::Never,
            t => return Err(js_err(&format!("unknown envelope mode tag {t}"))),
        };
        let block_supernodal = match self.block_supernodal {
            0 => BlockSupernodalMode::Auto,
            1 => BlockSupernodalMode::Always,
            2 => BlockSupernodalMode::Never,
            t => return Err(js_err(&format!("unknown block supernodal mode tag {t}"))),
        };
        let batch = self.block_supernodal_batch;
        let width = self.envelope_panel_width;
        let o = SparseFaerOptions::auto()
            .with_policy(policy)
            .with_ordering(ordering)
            .with_envelope_schur(envelope)
            .with_envelope_panel_width((width > 0).then_some(width as usize))
            .with_scalar_supernodal(self.supernodal)
            .with_narrow_band(self.narrow_band)
            .with_block_supernodal(block_supernodal)
            .with_block_supernodal_batching((batch > 0.0).then_some(batch))
            .with_block_supernodal_memory_lean(self.block_supernodal_memory_lean);
        let cg = arael::simple_lm::CgOptions {
            tol: self.cg_tol,
            max_iters: self.cg_max_iters as usize,
            restart_every: self.cg_restart_every as usize,
        };
        Ok(match self.schur_solve {
            0 => o,
            1 => o.with_iterative_schur(cg),
            2 => o.with_implicit_schur(cg),
            t => return Err(js_err(&format!("unknown schur solve tag {t}"))),
        })
    }
}

/// A completed solve. `status` is the C ABI code (0 Converged, 1
/// CostThreshold, 2 MaxIterations, 3 GradientTolerance, 4
/// ParameterTolerance, 5 PredictedReduction, 6 LambdaCeiling, 7
/// DriverTerminated, 8 ObserverTerminated, 9 TimeLimit, 10
/// RetryBudgetExhausted, 11 Aborted); `statusName` spells it.
#[wasm_bindgen]
pub struct DecayLmResult {
    r: arael::simple_lm::LmResult<f32>,
}

#[wasm_bindgen]
impl DecayLmResult {
    #[wasm_bindgen(getter, js_name = "startCost")]
    pub fn start_cost(&self) -> f64 { self.r.start_cost as f64 }
    #[wasm_bindgen(getter, js_name = "endCost")]
    pub fn end_cost(&self) -> f64 { self.r.end_cost as f64 }
    #[wasm_bindgen(getter)]
    pub fn iterations(&self) -> u32 { self.r.iterations as u32 }
    #[wasm_bindgen(getter, js_name = "acceptedIterations")]
    pub fn accepted_iterations(&self) -> u32 { self.r.accepted_iterations as u32 }
    #[wasm_bindgen(getter)]
    pub fn status(&self) -> i32 { status_code(&self.r.status) }
    #[wasm_bindgen(getter, js_name = "statusName")]
    pub fn status_name(&self) -> String { format!("{:?}", self.r.status) }
    /// Did the solve reach a minimum, as opposed to running out of
    /// something?
    #[wasm_bindgen(getter, js_name = "isSuccess")]
    pub fn is_success(&self) -> bool { self.r.status.is_success() }
    #[wasm_bindgen(getter, js_name = "finalLambda")]
    pub fn final_lambda(&self) -> f64 { self.r.final_lambda as f64 }
    /// The report text, plain.
    pub fn report(&self) -> String { self.r.report() }
    /// The report text with colour and glyphs.
    #[wasm_bindgen(js_name = "prettyReport")]
    pub fn pretty_report(&self) -> String { self.r.pretty_report() }
    /// Per-phase seconds and call counts, or undefined when the solve
    /// ran without `gatherTiming`.
    pub fn timing(&self) -> JsValue {
        match &self.r.timing {
            Some(t) => js_obj(&[
                ("total", t.total.as_secs_f64()),
                ("assembly", t.assembly.as_secs_f64()),
                ("firstAssembly", t.first_assembly.as_secs_f64()),
                ("analysis", t.analysis.as_secs_f64()),
                ("linearSolve", t.linear_solve.as_secs_f64()),
                ("firstLinearSolve", t.first_linear_solve.as_secs_f64()),
                ("costEval", t.cost_eval.as_secs_f64()),
                ("firstCostEval", t.first_cost_eval.as_secs_f64()),
                ("advance", t.advance.as_secs_f64()),
                ("firstAdvance", t.first_advance.as_secs_f64()),
                ("assemblyCount", t.assembly_count as f64),
                ("analysisCount", t.analysis_count as f64),
                ("linearSolveCount", t.linear_solve_count as f64),
                ("costEvalCount", t.cost_eval_count as f64),
                ("advanceCount", t.advance_count as f64),
            ]),
            None => JsValue::UNDEFINED,
        }
    }
    /// The sparse backend's plan, or undefined when the solve carried
    /// none. Absent statistics are undefined; `ordering` is 0
    /// NaturalBanded, 1 NaturalDense, 2 Amd, 3 Nd.
    pub fn plan(&self) -> JsValue {
        use arael::simple_lm::ReducedOrdering;
        let p = match &self.r.solver {
            Some(arael::simple_lm::SolverReport::Schur(p)) => p,
            _ => return JsValue::UNDEFINED,
        };
        let o = js_sys::Object::new();
        js_set(&o, "reduced", &JsValue::from_bool(p.reduced));
        js_set(&o, "eliminatedBlocks", &JsValue::from_f64(p.eliminated_blocks as f64));
        js_set(&o, "eliminatedParams", &JsValue::from_f64(p.eliminated_params as f64));
        js_set(&o, "keptParams", &JsValue::from_f64(p.kept_params as f64));
        js_set(&o, "fillRatio", &js_opt(p.fill_ratio));
        js_set(&o, "routeFlops", &match p.route_flops {
            Some((reduced, full)) => js_obj(&[("reduced", reduced), ("full", full)]),
            None => JsValue::UNDEFINED,
        });
        js_set(&o, "cgIterations", &js_opt(p.cg_iterations.map(|n| n as f64)));
        js_set(&o, "flopRatio", &js_opt(p.flop_ratio));
        js_set(&o, "ordering", &js_opt(p.ordering.map(|o| match o {
            ReducedOrdering::NaturalBanded => 0.0,
            ReducedOrdering::NaturalDense => 1.0,
            ReducedOrdering::Amd => 2.0,
            ReducedOrdering::NestedDissection => 3.0,
        })));
        js_set(&o, "keptBandwidth", &JsValue::from_f64(p.kept_bandwidth as f64));
        js_set(&o, "envelope", &JsValue::from_bool(p.envelope));
        js_set(&o, "blockSupernodal", &JsValue::from_bool(p.block_supernodal));
        o.into()
    }
    /// The per-attempt timeline, one object per attempted step; empty
    /// without `gatherTiming`.
    pub fn steps(&self) -> JsValue {
        let arr = js_sys::Array::new();
        if let Some(t) = &self.r.timing {
            for s in &t.steps {
                let o = js_sys::Object::new();
                js_set(&o, "iter", &JsValue::from_f64(s.iter as f64));
                js_set(&o, "inner", &JsValue::from_f64(s.inner as f64));
                js_set(&o, "accepted", &JsValue::from_bool(s.accepted));
                js_set(&o, "factorizationFailed", &JsValue::from_bool(s.factorization_failed));
                js_set(&o, "lambda", &JsValue::from_f64(s.lambda));
                js_set(&o, "cost", &JsValue::from_f64(s.cost));
                js_set(&o, "newCost", &JsValue::from_f64(s.new_cost));
                js_set(&o, "stepNorm", &JsValue::from_f64(s.step_norm));
                js_set(&o, "gradMax", &JsValue::from_f64(s.grad_max));
                js_set(&o, "time", &JsValue::from_f64(s.time.as_secs_f64()));
                js_set(&o, "assembly", &JsValue::from_f64(s.assembly.as_secs_f64()));
                js_set(&o, "analysis", &JsValue::from_f64(s.analysis.as_secs_f64()));
                js_set(&o, "linearSolve", &JsValue::from_f64(s.linear_solve.as_secs_f64()));
                js_set(&o, "costEval", &JsValue::from_f64(s.cost_eval.as_secs_f64()));
                js_set(&o, "advance", &JsValue::from_f64(s.advance.as_secs_f64()));
                arr.push(&o);
            }
        }
        arr.into()
    }
}

/// A warm re-solve: keeps the backend and what it learns about one
/// problem's structure across solves. Call `invalidate` after any
/// structural change to the model.
#[wasm_bindgen]
pub struct DecayLmSession {
    s: arael::simple_lm::LmSession<f32, SparseFaer<f32>>,
}

#[wasm_bindgen]
impl DecayLmSession {
    /// A session over the sparse backend, with its defaults or `opts`.
    #[wasm_bindgen(constructor)]
    pub fn new(opts: Option<DecaySparseOptions>) -> Result<DecayLmSession, JsValue> {
        let backend = match opts {
            None => SparseFaer::<f32>::new(),
            Some(o) => SparseFaer::<f32>::from_options(&o.to_options()?),
        };
        Ok(DecayLmSession { s: arael::simple_lm::LmSession::new(backend) })
    }
    /// As `solveSparse`, through the session's cached analysis.
    pub fn solve(&mut self, model: &DecayDecay, cfg: &DecayLmConfig) -> Result<DecayLmResult, JsValue> {
        let c = cfg.to_config();
        let mut g = model.root.borrow_mut();
        self.s.solve(&mut *g, &c).map(|r| DecayLmResult { r }).map_err(failure)
    }
    /// Drop the learned structure; the next solve runs cold.
    pub fn invalidate(&mut self) { self.s.invalidate(); }
}

/// The parameter covariance at the solution, `Sigma = 2 H^-1`, queried
/// per entity.
#[wasm_bindgen]
pub struct DecayCovariance {
    cov: CovAssembly,
    root: Rc<RefCell<m::Decay>>,
}

#[wasm_bindgen]
impl DecayCovariance {
    /// What the assembly decided: `ordering` 1 Amd, 2 NestedDissection,
    /// 3 Natural; `candidateFlops` when Auto priced them; the symbolic
    /// analyses built; whether the block route ran.
    pub fn plan(&self) -> JsValue {
        let p = self.cov.plan();
        let o = js_sys::Object::new();
        js_set(&o, "ordering", &JsValue::from_f64(match p.ordering {
            CovOrdering::Auto => 0.0,
            CovOrdering::Amd => 1.0,
            CovOrdering::NestedDissection => 2.0,
            CovOrdering::Natural => 3.0,
        }));
        js_set(&o, "candidateFlops", &match p.candidate_flops {
            Some((amd, nd)) => js_obj(&[("amd", amd), ("nd", nd)]),
            None => JsValue::UNDEFINED,
        });
        js_set(&o, "symbolicsBuilt", &JsValue::from_f64(p.symbolics_built as f64));
        js_set(&o, "blockRoute", &JsValue::from_bool(self.cov.took_block_route()));
        o.into()
    }
    /// Row-major dim x dim marginal covariance of one `Cell`.
    #[wasm_bindgen(js_name = "marginalCell")]
    pub fn marginal_cell(&self, e: &DecayCell) -> Result<js_sys::Float64Array, JsValue> {
        let g = self.root.borrow();
        let x = (e.see)(&*g).ok_or_else(stale)?;
        let m = self.cov.marginal_cov(x).map_err(|e| js_err(&e.to_string()))?;
        Ok(dense_to_js(m.nrows(), m.ncols(), |i, j| m[(i, j)]))
    }
    /// Row-major dim x dim conditional covariance of one `Cell`.
    #[wasm_bindgen(js_name = "conditionalCell")]
    pub fn conditional_cell(&self, e: &DecayCell) -> Result<js_sys::Float64Array, JsValue> {
        let g = self.root.borrow();
        let x = (e.see)(&*g).ok_or_else(stale)?;
        let m = self.cov.conditional_cov(x).map_err(|e| js_err(&e.to_string()))?;
        Ok(dense_to_js(m.nrows(), m.ncols(), |i, j| m[(i, j)]))
    }
    /// Per-parameter standard deviations of one `Cell`.
    #[wasm_bindgen(js_name = "stdDevCell")]
    pub fn std_dev_cell(&self, e: &DecayCell) -> Result<js_sys::Float64Array, JsValue> {
        let g = self.root.borrow();
        let x = (e.see)(&*g).ok_or_else(stale)?;
        let sd = self.cov.std_dev(x).map_err(|e| js_err(&e.to_string()))?;
        Ok(js_sys::Float64Array::from(&sd[..]))
    }
    /// Row-major cross covariance between one `Cell` and one `Cell`.
    #[wasm_bindgen(js_name = "crossCellCell")]
    pub fn cross_cell_cell(&self, a: &DecayCell, b: &DecayCell) -> Result<js_sys::Float64Array, JsValue> {
        let g = self.root.borrow();
        let xa = (a.see)(&*g).ok_or_else(stale)?;
        let xb = (b.see)(&*g).ok_or_else(stale)?;
        let m = self.cov.cross_cov(xa, xb).map_err(|e| js_err(&e.to_string()))?;
        Ok(dense_to_js(m.nrows(), m.ncols(), |i, j| m[(i, j)]))
    }
}

} // mod decay

// ---------------------------------------------------------------- Line
pub mod line {
use super::*;

/// A handle's way to its element: through the model, mutably.
type At<T> = Rc<dyn for<'a> Fn(&'a mut m::Line) -> Option<&'a mut T>>;
/// The same, shared.
type See<T> = Rc<dyn for<'a> Fn(&'a m::Line) -> Option<&'a T>>;

fn mk_at<T>(f: impl for<'a> Fn(&'a mut m::Line) -> Option<&'a mut T> + 'static) -> At<T> {
    Rc::new(f)
}
fn mk_see<T>(f: impl for<'a> Fn(&'a m::Line) -> Option<&'a T> + 'static) -> See<T> {
    Rc::new(f)
}

fn preset_config(preset: u32) -> arael::simple_lm::LmConfig<f64> {
    match preset {
        1 => arael::simple_lm::LmConfig::conservative(),
        2 => arael::simple_lm::LmConfig::well_conditioned(),
        3 => arael::simple_lm::LmConfig::ill_conditioned(),
        _ => arael::simple_lm::LmConfig::default(),
    }
}

fn failure(f: arael::simple_lm::SolveFailure<f64>) -> JsValue {
    js_err(&f.to_string())
}

/// The `Line` model and its solver entries.
#[wasm_bindgen]
pub struct LineLine {
    root: Rc<RefCell<m::Line>>,
}

#[wasm_bindgen]
impl LineLine {
    #[wasm_bindgen(constructor)]
    pub fn new() -> LineLine {
        LineLine { root: Rc::new(RefCell::new(Default::default())) }
    }
    fn with<R>(&self, f: impl FnOnce(&mut m::Line) -> R) -> Result<R, JsValue> {
        let mut g = self.root.borrow_mut();
        Ok(f(&mut *g))
    }
    /// The cost at the current parameters.
    pub fn cost(&self) -> f64 {
        let mut g = self.root.borrow_mut();
        let mut params = Vec::new();
        g.serialize(&mut params);
        g.calc_cost(&params) as f64
    }
    /// The model's diagnostics as text; empty when clean.
    pub fn validate(&self) -> String {
        let mut g = self.root.borrow_mut();
        let d = g.validate();
        if d.is_clean() { String::new() } else { d.to_string() }
    }
    #[wasm_bindgen(js_name = "solveDense")]
    pub fn solve_dense(&self, cfg: &LineLmConfig) -> Result<LineLmResult, JsValue> {
        let c = cfg.to_config();
        let mut g = self.root.borrow_mut();
        g.solve_dense(&c).map(|r| LineLmResult { r }).map_err(failure)
    }
    /// The sparse solve, with the backend's defaults or `opts`.
    #[wasm_bindgen(js_name = "solveSparse")]
    pub fn solve_sparse(&self, cfg: &LineLmConfig, opts: Option<LineSparseOptions>) -> Result<LineLmResult, JsValue> {
        let c = cfg.to_config();
        let mut g = self.root.borrow_mut();
        let r = match opts {
            None => g.solve_sparse(&c),
            Some(o) => {
                let mut s = SparseFaer::<f64>::from_options(&o.to_options()?);
                g.solve_with(&mut s, &c)
            }
        };
        r.map(|r| LineLmResult { r }).map_err(failure)
    }
    /// The band solve, `kd` the half-bandwidth in scalar parameters.
    #[wasm_bindgen(js_name = "solveBand")]
    pub fn solve_band(&self, kd: u32, cfg: &LineLmConfig) -> Result<LineLmResult, JsValue> {
        let c = cfg.to_config();
        let mut g = self.root.borrow_mut();
        g.solve_with(&mut arael::simple_lm::Band::new(kd as usize), &c)
            .map(|r| LineLmResult { r })
            .map_err(failure)
    }
    /// The covariance at the current parameters; `mode` 0 PerQuery,
    /// 1 AllMarginals (the default), 2 TriDiagonal.
    #[wasm_bindgen(js_name = "assembleCovariance")]
    pub fn assemble_covariance(&self, mode: Option<u32>) -> Result<LineCovariance, JsValue> {
        self.assemble_covariance_with(mode.unwrap_or(1), 0, 0)
    }
    /// `assembleCovariance` with the assembly spelled out: `ordering` 0
    /// Auto, 1 Amd, 2 NestedDissection, 3 Natural; `blockSupernodal` 0
    /// Auto, 1 Always, 2 Never.
    #[wasm_bindgen(js_name = "assembleCovarianceWith")]
    pub fn assemble_covariance_with(&self, mode: u32, ordering: u32, block_supernodal: u32) -> Result<LineCovariance, JsValue> {
        let m = match mode {
            0 => CovMode::PerQuery,
            2 => CovMode::TriDiagonal,
            _ => CovMode::AllMarginals,
        };
        let opts = CovOptions {
            ordering: match ordering {
                1 => CovOrdering::Amd,
                2 => CovOrdering::NestedDissection,
                3 => CovOrdering::Natural,
                _ => CovOrdering::Auto,
            },
            block_supernodal: match block_supernodal {
                1 => arael::simple_lm::BlockSupernodalMode::Always,
                2 => arael::simple_lm::BlockSupernodalMode::Never,
                _ => arael::simple_lm::BlockSupernodalMode::Auto,
            },
        };
        let mut g = self.root.borrow_mut();
        let cov = g.assemble_covariance_with(m, &opts).map_err(|e| js_err(&format!("{}", e)))?;
        Ok(LineCovariance { cov, root: self.root.clone() })
    }
    #[wasm_bindgen(getter, js_name = "k")]
    pub fn k(&self) -> Result<f64, JsValue> {
        self.with(|e| e.k.value)
    }
    #[wasm_bindgen(setter, js_name = "k")]
    pub fn set_k(&self, v: f64) -> Result<(), JsValue> {
        let v = v;
        self.with(|e| { e.k.value = v; })
    }
    #[wasm_bindgen(getter, js_name = "kOptimize")]
    pub fn k_optimize(&self) -> Result<bool, JsValue> {
        self.with(|e| e.k.optimize)
    }
    #[wasm_bindgen(setter, js_name = "kOptimize")]
    pub fn set_k_optimize(&self, v: bool) -> Result<(), JsValue> {
        let v = v;
        self.with(|e| { e.k.optimize = v; })
    }
    /// The `obs` collection.
    #[wasm_bindgen(js_name = "obs")]
    pub fn obs(&self) -> LineLineObs {
        LineLineObs { root: self.root.clone(), at: mk_at(move |o| { Some(o) }), see: mk_see(move |o| { Some(o) }) }
    }
}

/// The `Line.obs` collection, `std::vec::Vec<Ob<f64>>`.
#[wasm_bindgen]
pub struct LineLineObs {
    root: Rc<RefCell<m::Line>>,
    at: At<m::Line>,
    see: See<m::Line>,
}

#[wasm_bindgen]
impl LineLineObs {
    fn with<R>(&self, f: impl FnOnce(&mut m::Line) -> R) -> Result<R, JsValue> {
        let mut g = self.root.borrow_mut();
        let o = (self.at)(&mut *g).ok_or_else(stale)?;
        Ok(f(o))
    }
    #[wasm_bindgen(getter)]
    pub fn length(&self) -> Result<u32, JsValue> {
        self.with(|o| o.obs.len() as u32)
    }
    pub fn reserve(&self, additional: u32) -> Result<(), JsValue> {
        self.with(|o| o.obs.reserve(additional as usize))
    }
    pub fn clear(&self) -> Result<(), JsValue> {
        self.with(|o| o.obs.clear())
    }
    /// Append a default `Ob` and hand it back.
    pub fn push(&self) -> Result<LineOb, JsValue> {
        let i = self.with(|o| { o.obs.push(Default::default()); o.obs.len() - 1 })?;
        Ok(LineOb { root: self.root.clone(), at: { let p = self.at.clone(); mk_at(move |g| p(g).and_then(|o| o.obs.get_mut(i))) }, see: { let p = self.see.clone(); mk_see(move |g| p(g).and_then(|o| o.obs.get(i))) } })
    }
    /// Append `n` default elements; returns the index of the first.
    #[wasm_bindgen(js_name = "pushN")]
    pub fn push_n(&self, n: u32) -> Result<u32, JsValue> {
        self.with(|o| {
            let first = o.obs.len();
            o.obs.reserve(n as usize);
            for _ in 0..n { o.obs.push(Default::default()); }
            first as u32
        })
    }
    /// The element at index `i`; throws past the end.
    pub fn at(&self, i: u32) -> Result<LineOb, JsValue> {
        let i = i as usize;
        if !self.with(|o| i < o.obs.len())? { return Err(js_err("index past the end")); }
        Ok(LineOb { root: self.root.clone(), at: { let p = self.at.clone(); mk_at(move |g| p(g).and_then(|o| o.obs.get_mut(i))) }, see: { let p = self.see.clone(); mk_see(move |g| p(g).and_then(|o| o.obs.get(i))) } })
    }
    /// Drops the last element; false when already empty.
    pub fn pop(&self) -> Result<bool, JsValue> {
        self.with(|o| o.obs.pop().is_some())
    }
    pub fn truncate(&self, len: u32) -> Result<(), JsValue> {
        self.with(|o| o.obs.truncate(len as usize))
    }
    /// `x` of the elements from `start`, `n` of them, 1 value(s) each.
    #[wasm_bindgen(js_name = "getXN")]
    pub fn get_x_n(&self, start: u32, n: u32) -> Result<js_sys::Float64Array, JsValue> {
        let v = self.with(|o| {
            let (s, n) = (start as usize, n as usize);
            if s + n > o.obs.len() { return Err(js_err("range past the end")); }
            let mut out: Vec<f64> = Vec::with_capacity(n * 1);
            for i in s..s + n { let e = &o.obs[i]; out.push(e.x); }
            Ok(out)
        })??;
        Ok(js_sys::Float64Array::from(&v[..]))
    }
    /// Set `x` of the elements from `start`, 1 value(s) each.
    #[wasm_bindgen(js_name = "setXN")]
    pub fn set_x_n(&self, start: u32, values: &[f64]) -> Result<(), JsValue> {
        self.with(|o| {
            let s = start as usize;
            let n = values.len() / 1;
            if s + n > o.obs.len() { return Err(js_err("range past the end")); }
            for (k, c) in values.chunks_exact(1).enumerate() { let e = &mut o.obs[s + k]; e.x = c[0]; }
            Ok(())
        })?
    }
    /// `y` of the elements from `start`, `n` of them, 1 value(s) each.
    #[wasm_bindgen(js_name = "getYN")]
    pub fn get_y_n(&self, start: u32, n: u32) -> Result<js_sys::Float64Array, JsValue> {
        let v = self.with(|o| {
            let (s, n) = (start as usize, n as usize);
            if s + n > o.obs.len() { return Err(js_err("range past the end")); }
            let mut out: Vec<f64> = Vec::with_capacity(n * 1);
            for i in s..s + n { let e = &o.obs[i]; out.push(e.y); }
            Ok(out)
        })??;
        Ok(js_sys::Float64Array::from(&v[..]))
    }
    /// Set `y` of the elements from `start`, 1 value(s) each.
    #[wasm_bindgen(js_name = "setYN")]
    pub fn set_y_n(&self, start: u32, values: &[f64]) -> Result<(), JsValue> {
        self.with(|o| {
            let s = start as usize;
            let n = values.len() / 1;
            if s + n > o.obs.len() { return Err(js_err("range past the end")); }
            for (k, c) in values.chunks_exact(1).enumerate() { let e = &mut o.obs[s + k]; e.y = c[0]; }
            Ok(())
        })?
    }
}

/// A `Ob` in its owner's storage, addressed by key rather than by
/// pointer: the element is re-resolved on every access, so growing the
/// collection cannot leave this handle dangling.
#[wasm_bindgen]
pub struct LineOb {
    root: Rc<RefCell<m::Line>>,
    at: At<m::Ob<f64>>,
    see: See<m::Ob<f64>>,
}

#[wasm_bindgen]
impl LineOb {
    fn with<R>(&self, f: impl FnOnce(&mut m::Ob<f64>) -> R) -> Result<R, JsValue> {
        let mut g = self.root.borrow_mut();
        let e = (self.at)(&mut *g).ok_or_else(stale)?;
        Ok(f(e))
    }
    #[wasm_bindgen(getter, js_name = "x")]
    pub fn x(&self) -> Result<f64, JsValue> {
        self.with(|e| e.x)
    }
    #[wasm_bindgen(setter, js_name = "x")]
    pub fn set_x(&self, v: f64) -> Result<(), JsValue> {
        let v = v;
        self.with(|e| { e.x = v; })
    }
    #[wasm_bindgen(getter, js_name = "y")]
    pub fn y(&self) -> Result<f64, JsValue> {
        self.with(|e| e.y)
    }
    #[wasm_bindgen(setter, js_name = "y")]
    pub fn set_y(&self, v: f64) -> Result<(), JsValue> {
        let v = v;
        self.with(|e| { e.y = v; })
    }
}

/// The solver configuration: a preset's values, edited field by field.
#[wasm_bindgen]
pub struct LineLmConfig {
    preset: u32,
    #[wasm_bindgen(js_name = "maxIters")]
    pub max_iters: u32,
    #[wasm_bindgen(js_name = "minIters")]
    pub min_iters: u32,
    pub patience: u32,
    #[wasm_bindgen(js_name = "numThreads")]
    pub num_threads: u32,
    pub verbose: bool,
    #[wasm_bindgen(js_name = "gatherTiming")]
    pub gather_timing: bool,
    #[wasm_bindgen(js_name = "absPrecision")]
    pub abs_precision: f64,
    #[wasm_bindgen(js_name = "relPrecision")]
    pub rel_precision: f64,
    #[wasm_bindgen(js_name = "initialLambda")]
    pub initial_lambda: f64,
    #[wasm_bindgen(js_name = "costThreshold")]
    pub cost_threshold: f64,
    #[wasm_bindgen(js_name = "lambdaFloor")]
    pub lambda_floor: f64,
    gradient_tolerance: Option<f64>,
    parameter_tolerance: Option<f64>,
    predicted_reduction_tolerance: Option<f64>,
    min_diagonal: Option<f64>,
    time_limit_seconds: Option<f64>,
    assembly_threads: Option<u32>,
    max_accepted_iters: Option<u32>,
}

#[wasm_bindgen]
impl LineLmConfig {
    fn from_preset(preset: u32) -> LineLmConfig {
        let c = preset_config(preset);
        LineLmConfig {
            preset,
            max_iters: c.max_iters as u32,
            min_iters: c.min_iters as u32,
            patience: c.patience as u32,
            num_threads: c.num_threads as u32,
            verbose: c.verbose,
            gather_timing: c.gather_timing,
            abs_precision: c.abs_precision as f64,
            rel_precision: c.rel_precision as f64,
            initial_lambda: c.initial_lambda as f64,
            cost_threshold: c.cost_threshold as f64,
            lambda_floor: c.lambda_floor as f64,
            gradient_tolerance: c.gradient_tolerance.map(|v| v as f64),
            parameter_tolerance: c.parameter_tolerance.map(|v| v as f64),
            predicted_reduction_tolerance: c.predicted_reduction_tolerance.map(|v| v as f64),
            min_diagonal: c.min_diagonal.map(|v| v as f64),
            time_limit_seconds: c.time_limit.map(|d| d.as_secs_f64()),
            assembly_threads: c.assembly_threads.map(|n| n as u32),
            max_accepted_iters: c.max_accepted_iters.map(|n| n as u32),
        }
    }
    fn to_config(&self) -> arael::simple_lm::LmConfig<f64> {
        let mut c = preset_config(self.preset);
        c.max_iters = self.max_iters as usize;
        c.min_iters = self.min_iters as usize;
        c.patience = self.patience as usize;
        c.num_threads = self.num_threads as usize;
        c.assembly_threads = self.assembly_threads.map(|n| n as usize);
        c.max_accepted_iters = self.max_accepted_iters.map(|n| n as usize);
        c.verbose = self.verbose;
        c.gather_timing = self.gather_timing;
        c.abs_precision = self.abs_precision as f64;
        c.rel_precision = self.rel_precision as f64;
        c.initial_lambda = self.initial_lambda as f64;
        c.cost_threshold = self.cost_threshold as f64;
        c.lambda_floor = self.lambda_floor as f64;
        c.gradient_tolerance = self.gradient_tolerance.map(|v| v as f64);
        c.parameter_tolerance = self.parameter_tolerance.map(|v| v as f64);
        c.predicted_reduction_tolerance = self.predicted_reduction_tolerance.map(|v| v as f64);
        c.min_diagonal = self.min_diagonal.map(|v| v as f64);
        c.time_limit = self.time_limit_seconds.map(std::time::Duration::from_secs_f64);
        c
    }
    /// The defaults.
    #[wasm_bindgen(constructor)]
    pub fn new() -> LineLmConfig { Self::from_preset(0) }
    pub fn defaults() -> LineLmConfig { Self::from_preset(0) }
    pub fn conservative() -> LineLmConfig { Self::from_preset(1) }
    #[wasm_bindgen(js_name = "wellConditioned")]
    pub fn well_conditioned() -> LineLmConfig { Self::from_preset(2) }
    #[wasm_bindgen(js_name = "illConditioned")]
    pub fn ill_conditioned() -> LineLmConfig { Self::from_preset(3) }
    #[wasm_bindgen(getter, js_name = "gradientTolerance")]
    pub fn gradient_tolerance(&self) -> Option<f64> { self.gradient_tolerance }
    #[wasm_bindgen(setter, js_name = "gradientTolerance")]
    pub fn set_gradient_tolerance(&mut self, v: Option<f64>) { self.gradient_tolerance = v; }
    #[wasm_bindgen(getter, js_name = "parameterTolerance")]
    pub fn parameter_tolerance(&self) -> Option<f64> { self.parameter_tolerance }
    #[wasm_bindgen(setter, js_name = "parameterTolerance")]
    pub fn set_parameter_tolerance(&mut self, v: Option<f64>) { self.parameter_tolerance = v; }
    #[wasm_bindgen(getter, js_name = "predictedReductionTolerance")]
    pub fn predicted_reduction_tolerance(&self) -> Option<f64> { self.predicted_reduction_tolerance }
    #[wasm_bindgen(setter, js_name = "predictedReductionTolerance")]
    pub fn set_predicted_reduction_tolerance(&mut self, v: Option<f64>) { self.predicted_reduction_tolerance = v; }
    #[wasm_bindgen(getter, js_name = "minDiagonal")]
    pub fn min_diagonal(&self) -> Option<f64> { self.min_diagonal }
    #[wasm_bindgen(setter, js_name = "minDiagonal")]
    pub fn set_min_diagonal(&mut self, v: Option<f64>) { self.min_diagonal = v; }
    #[wasm_bindgen(getter, js_name = "timeLimitSeconds")]
    pub fn time_limit_seconds(&self) -> Option<f64> { self.time_limit_seconds }
    #[wasm_bindgen(setter, js_name = "timeLimitSeconds")]
    pub fn set_time_limit_seconds(&mut self, v: Option<f64>) { self.time_limit_seconds = v; }
    #[wasm_bindgen(getter, js_name = "assemblyThreads")]
    pub fn assembly_threads(&self) -> Option<u32> { self.assembly_threads }
    #[wasm_bindgen(setter, js_name = "assemblyThreads")]
    pub fn set_assembly_threads(&mut self, v: Option<u32>) { self.assembly_threads = v; }
    #[wasm_bindgen(getter, js_name = "maxAcceptedIters")]
    pub fn max_accepted_iters(&self) -> Option<u32> { self.max_accepted_iters }
    #[wasm_bindgen(setter, js_name = "maxAcceptedIters")]
    pub fn set_max_accepted_iters(&mut self, v: Option<u32>) { self.max_accepted_iters = v; }
}

/// The sparse backend's options as plain data, starting from the Rust
/// defaults. The enum fields carry the tags of the C ABI: schur 0 Auto,
/// 1 Force, 2 Never; ordering 0 Auto, 1 Amd, 2 MarginalizeFirst,
/// 3 Natural, 4 NestedDissection; envelope 0 Auto, 1 Always, 2 Never;
/// schurSolve 0 Factorize, 1 Iterative, 2 IterativeImplicit;
/// blockSupernodal 0 Auto, 1 Always, 2 Never.
#[wasm_bindgen]
pub struct LineSparseOptions {
    pub schur: u32,
    pub ordering: u32,
    pub envelope: u32,
    #[wasm_bindgen(js_name = "envelopePanelWidth")]
    pub envelope_panel_width: u32,
    pub supernodal: bool,
    #[wasm_bindgen(js_name = "narrowBand")]
    pub narrow_band: bool,
    #[wasm_bindgen(js_name = "flopMargin")]
    pub flop_margin: f64,
    #[wasm_bindgen(js_name = "obviousFlopRatio")]
    pub obvious_flop_ratio: f64,
    #[wasm_bindgen(js_name = "cgTol")]
    pub cg_tol: f64,
    #[wasm_bindgen(js_name = "schurSolve")]
    pub schur_solve: u32,
    #[wasm_bindgen(js_name = "cgMaxIters")]
    pub cg_max_iters: u32,
    #[wasm_bindgen(js_name = "cgRestartEvery")]
    pub cg_restart_every: u32,
    #[wasm_bindgen(js_name = "blockSupernodal")]
    pub block_supernodal: u32,
    #[wasm_bindgen(js_name = "blockSupernodalBatch")]
    pub block_supernodal_batch: f64,
    #[wasm_bindgen(js_name = "blockSupernodalMemoryLean")]
    pub block_supernodal_memory_lean: bool,
}

#[wasm_bindgen]
impl LineSparseOptions {
    /// The Rust defaults.
    #[wasm_bindgen(constructor)]
    pub fn new() -> LineSparseOptions {
        use arael::simple_lm::{BlockSupernodalMode, EnvelopeMode, SolveOrdering, SchurPolicy};
        let d = SparseFaerOptions::default();
        let (flop_margin, obvious_flop_ratio) = match d.policy {
            SchurPolicy::Auto { flop_margin, obvious_flop_ratio } => (flop_margin, obvious_flop_ratio),
            _ => (0.0, 0.0),
        };
        LineSparseOptions {
            schur: match d.policy {
                SchurPolicy::Auto { .. } => 0,
                SchurPolicy::Force => 1,
                SchurPolicy::Never => 2,
            },
            ordering: match d.ordering {
                SolveOrdering::Auto => 0,
                SolveOrdering::Amd => 1,
                SolveOrdering::MarginalizeFirst => 2,
                SolveOrdering::Natural => 3,
                SolveOrdering::NestedDissection => 4,
            },
            envelope: match d.envelope {
                EnvelopeMode::Auto => 0,
                EnvelopeMode::Always => 1,
                EnvelopeMode::Never => 2,
            },
            envelope_panel_width: d.envelope_panel_width.unwrap_or(0) as u32,
            supernodal: d.scalar_supernodal,
            narrow_band: d.narrow_band,
            flop_margin,
            obvious_flop_ratio,
            cg_tol: arael::simple_lm::CgOptions::default().tol,
            schur_solve: 0,
            cg_max_iters: 0,
            cg_restart_every: 0,
            block_supernodal: match d.block_supernodal {
                BlockSupernodalMode::Auto => 0,
                BlockSupernodalMode::Always => 1,
                BlockSupernodalMode::Never => 2,
            },
            block_supernodal_batch: d.block_supernodal_batch.unwrap_or(0.0),
            block_supernodal_memory_lean: d.block_supernodal_memory_lean,
        }
    }
    fn to_options(&self) -> Result<SparseFaerOptions, JsValue> {
        use arael::simple_lm::{BlockSupernodalMode, EnvelopeMode, SolveOrdering, SchurPolicy};
        let policy = match self.schur {
            0 => SchurPolicy::Auto { flop_margin: self.flop_margin, obvious_flop_ratio: self.obvious_flop_ratio },
            1 => SchurPolicy::Force,
            2 => SchurPolicy::Never,
            t => return Err(js_err(&format!("unknown schur policy tag {t}"))),
        };
        let ordering = match self.ordering {
            0 => SolveOrdering::Auto,
            1 => SolveOrdering::Amd,
            2 => SolveOrdering::MarginalizeFirst,
            3 => SolveOrdering::Natural,
            4 => SolveOrdering::NestedDissection,
            t => return Err(js_err(&format!("unknown ordering tag {t}"))),
        };
        let envelope = match self.envelope {
            0 => EnvelopeMode::Auto,
            1 => EnvelopeMode::Always,
            2 => EnvelopeMode::Never,
            t => return Err(js_err(&format!("unknown envelope mode tag {t}"))),
        };
        let block_supernodal = match self.block_supernodal {
            0 => BlockSupernodalMode::Auto,
            1 => BlockSupernodalMode::Always,
            2 => BlockSupernodalMode::Never,
            t => return Err(js_err(&format!("unknown block supernodal mode tag {t}"))),
        };
        let batch = self.block_supernodal_batch;
        let width = self.envelope_panel_width;
        let o = SparseFaerOptions::auto()
            .with_policy(policy)
            .with_ordering(ordering)
            .with_envelope_schur(envelope)
            .with_envelope_panel_width((width > 0).then_some(width as usize))
            .with_scalar_supernodal(self.supernodal)
            .with_narrow_band(self.narrow_band)
            .with_block_supernodal(block_supernodal)
            .with_block_supernodal_batching((batch > 0.0).then_some(batch))
            .with_block_supernodal_memory_lean(self.block_supernodal_memory_lean);
        let cg = arael::simple_lm::CgOptions {
            tol: self.cg_tol,
            max_iters: self.cg_max_iters as usize,
            restart_every: self.cg_restart_every as usize,
        };
        Ok(match self.schur_solve {
            0 => o,
            1 => o.with_iterative_schur(cg),
            2 => o.with_implicit_schur(cg),
            t => return Err(js_err(&format!("unknown schur solve tag {t}"))),
        })
    }
}

/// A completed solve. `status` is the C ABI code (0 Converged, 1
/// CostThreshold, 2 MaxIterations, 3 GradientTolerance, 4
/// ParameterTolerance, 5 PredictedReduction, 6 LambdaCeiling, 7
/// DriverTerminated, 8 ObserverTerminated, 9 TimeLimit, 10
/// RetryBudgetExhausted, 11 Aborted); `statusName` spells it.
#[wasm_bindgen]
pub struct LineLmResult {
    r: arael::simple_lm::LmResult<f64>,
}

#[wasm_bindgen]
impl LineLmResult {
    #[wasm_bindgen(getter, js_name = "startCost")]
    pub fn start_cost(&self) -> f64 { self.r.start_cost as f64 }
    #[wasm_bindgen(getter, js_name = "endCost")]
    pub fn end_cost(&self) -> f64 { self.r.end_cost as f64 }
    #[wasm_bindgen(getter)]
    pub fn iterations(&self) -> u32 { self.r.iterations as u32 }
    #[wasm_bindgen(getter, js_name = "acceptedIterations")]
    pub fn accepted_iterations(&self) -> u32 { self.r.accepted_iterations as u32 }
    #[wasm_bindgen(getter)]
    pub fn status(&self) -> i32 { status_code(&self.r.status) }
    #[wasm_bindgen(getter, js_name = "statusName")]
    pub fn status_name(&self) -> String { format!("{:?}", self.r.status) }
    /// Did the solve reach a minimum, as opposed to running out of
    /// something?
    #[wasm_bindgen(getter, js_name = "isSuccess")]
    pub fn is_success(&self) -> bool { self.r.status.is_success() }
    #[wasm_bindgen(getter, js_name = "finalLambda")]
    pub fn final_lambda(&self) -> f64 { self.r.final_lambda as f64 }
    /// The report text, plain.
    pub fn report(&self) -> String { self.r.report() }
    /// The report text with colour and glyphs.
    #[wasm_bindgen(js_name = "prettyReport")]
    pub fn pretty_report(&self) -> String { self.r.pretty_report() }
    /// Per-phase seconds and call counts, or undefined when the solve
    /// ran without `gatherTiming`.
    pub fn timing(&self) -> JsValue {
        match &self.r.timing {
            Some(t) => js_obj(&[
                ("total", t.total.as_secs_f64()),
                ("assembly", t.assembly.as_secs_f64()),
                ("firstAssembly", t.first_assembly.as_secs_f64()),
                ("analysis", t.analysis.as_secs_f64()),
                ("linearSolve", t.linear_solve.as_secs_f64()),
                ("firstLinearSolve", t.first_linear_solve.as_secs_f64()),
                ("costEval", t.cost_eval.as_secs_f64()),
                ("firstCostEval", t.first_cost_eval.as_secs_f64()),
                ("advance", t.advance.as_secs_f64()),
                ("firstAdvance", t.first_advance.as_secs_f64()),
                ("assemblyCount", t.assembly_count as f64),
                ("analysisCount", t.analysis_count as f64),
                ("linearSolveCount", t.linear_solve_count as f64),
                ("costEvalCount", t.cost_eval_count as f64),
                ("advanceCount", t.advance_count as f64),
            ]),
            None => JsValue::UNDEFINED,
        }
    }
    /// The sparse backend's plan, or undefined when the solve carried
    /// none. Absent statistics are undefined; `ordering` is 0
    /// NaturalBanded, 1 NaturalDense, 2 Amd, 3 Nd.
    pub fn plan(&self) -> JsValue {
        use arael::simple_lm::ReducedOrdering;
        let p = match &self.r.solver {
            Some(arael::simple_lm::SolverReport::Schur(p)) => p,
            _ => return JsValue::UNDEFINED,
        };
        let o = js_sys::Object::new();
        js_set(&o, "reduced", &JsValue::from_bool(p.reduced));
        js_set(&o, "eliminatedBlocks", &JsValue::from_f64(p.eliminated_blocks as f64));
        js_set(&o, "eliminatedParams", &JsValue::from_f64(p.eliminated_params as f64));
        js_set(&o, "keptParams", &JsValue::from_f64(p.kept_params as f64));
        js_set(&o, "fillRatio", &js_opt(p.fill_ratio));
        js_set(&o, "routeFlops", &match p.route_flops {
            Some((reduced, full)) => js_obj(&[("reduced", reduced), ("full", full)]),
            None => JsValue::UNDEFINED,
        });
        js_set(&o, "cgIterations", &js_opt(p.cg_iterations.map(|n| n as f64)));
        js_set(&o, "flopRatio", &js_opt(p.flop_ratio));
        js_set(&o, "ordering", &js_opt(p.ordering.map(|o| match o {
            ReducedOrdering::NaturalBanded => 0.0,
            ReducedOrdering::NaturalDense => 1.0,
            ReducedOrdering::Amd => 2.0,
            ReducedOrdering::NestedDissection => 3.0,
        })));
        js_set(&o, "keptBandwidth", &JsValue::from_f64(p.kept_bandwidth as f64));
        js_set(&o, "envelope", &JsValue::from_bool(p.envelope));
        js_set(&o, "blockSupernodal", &JsValue::from_bool(p.block_supernodal));
        o.into()
    }
    /// The per-attempt timeline, one object per attempted step; empty
    /// without `gatherTiming`.
    pub fn steps(&self) -> JsValue {
        let arr = js_sys::Array::new();
        if let Some(t) = &self.r.timing {
            for s in &t.steps {
                let o = js_sys::Object::new();
                js_set(&o, "iter", &JsValue::from_f64(s.iter as f64));
                js_set(&o, "inner", &JsValue::from_f64(s.inner as f64));
                js_set(&o, "accepted", &JsValue::from_bool(s.accepted));
                js_set(&o, "factorizationFailed", &JsValue::from_bool(s.factorization_failed));
                js_set(&o, "lambda", &JsValue::from_f64(s.lambda));
                js_set(&o, "cost", &JsValue::from_f64(s.cost));
                js_set(&o, "newCost", &JsValue::from_f64(s.new_cost));
                js_set(&o, "stepNorm", &JsValue::from_f64(s.step_norm));
                js_set(&o, "gradMax", &JsValue::from_f64(s.grad_max));
                js_set(&o, "time", &JsValue::from_f64(s.time.as_secs_f64()));
                js_set(&o, "assembly", &JsValue::from_f64(s.assembly.as_secs_f64()));
                js_set(&o, "analysis", &JsValue::from_f64(s.analysis.as_secs_f64()));
                js_set(&o, "linearSolve", &JsValue::from_f64(s.linear_solve.as_secs_f64()));
                js_set(&o, "costEval", &JsValue::from_f64(s.cost_eval.as_secs_f64()));
                js_set(&o, "advance", &JsValue::from_f64(s.advance.as_secs_f64()));
                arr.push(&o);
            }
        }
        arr.into()
    }
}

/// A warm re-solve: keeps the backend and what it learns about one
/// problem's structure across solves. Call `invalidate` after any
/// structural change to the model.
#[wasm_bindgen]
pub struct LineLmSession {
    s: arael::simple_lm::LmSession<f64, SparseFaer<f64>>,
}

#[wasm_bindgen]
impl LineLmSession {
    /// A session over the sparse backend, with its defaults or `opts`.
    #[wasm_bindgen(constructor)]
    pub fn new(opts: Option<LineSparseOptions>) -> Result<LineLmSession, JsValue> {
        let backend = match opts {
            None => SparseFaer::<f64>::new(),
            Some(o) => SparseFaer::<f64>::from_options(&o.to_options()?),
        };
        Ok(LineLmSession { s: arael::simple_lm::LmSession::new(backend) })
    }
    /// As `solveSparse`, through the session's cached analysis.
    pub fn solve(&mut self, model: &LineLine, cfg: &LineLmConfig) -> Result<LineLmResult, JsValue> {
        let c = cfg.to_config();
        let mut g = model.root.borrow_mut();
        self.s.solve(&mut *g, &c).map(|r| LineLmResult { r }).map_err(failure)
    }
    /// Drop the learned structure; the next solve runs cold.
    pub fn invalidate(&mut self) { self.s.invalidate(); }
}

/// The parameter covariance at the solution, `Sigma = 2 H^-1`, queried
/// per entity.
#[wasm_bindgen]
pub struct LineCovariance {
    cov: CovAssembly,
    root: Rc<RefCell<m::Line>>,
}

#[wasm_bindgen]
impl LineCovariance {
    /// What the assembly decided: `ordering` 1 Amd, 2 NestedDissection,
    /// 3 Natural; `candidateFlops` when Auto priced them; the symbolic
    /// analyses built; whether the block route ran.
    pub fn plan(&self) -> JsValue {
        let p = self.cov.plan();
        let o = js_sys::Object::new();
        js_set(&o, "ordering", &JsValue::from_f64(match p.ordering {
            CovOrdering::Auto => 0.0,
            CovOrdering::Amd => 1.0,
            CovOrdering::NestedDissection => 2.0,
            CovOrdering::Natural => 3.0,
        }));
        js_set(&o, "candidateFlops", &match p.candidate_flops {
            Some((amd, nd)) => js_obj(&[("amd", amd), ("nd", nd)]),
            None => JsValue::UNDEFINED,
        });
        js_set(&o, "symbolicsBuilt", &JsValue::from_f64(p.symbolics_built as f64));
        js_set(&o, "blockRoute", &JsValue::from_bool(self.cov.took_block_route()));
        o.into()
    }
}

} // mod line
