// GENERATED by cargo-arael from the `Graph` model sidecar. Do not
// edit; regenerate with `cargo arael export`.
#pragma once

#include <cstdint>
#include <cstddef>
#include <cmath>
#include <iterator>
#include "arael/math.hpp"
#include "arael/result.hpp"
#include "arael/solver.hpp"

namespace m3500_demo {

/// The arael value vocabulary this interface uses, re-exported so a
/// single `using namespace m3500_demo;` brings the model AND the math.
using arael::vect2;
using arael::vect3;
using arael::matrix2;
using arael::matrix3;
using arael::quatern;
using arael::vect2f;
using arael::vect2d;
using arael::vect3f;
using arael::vect3d;
using arael::matrix2f;
using arael::matrix2d;
using arael::matrix3f;
using arael::matrix3d;
using arael::quaternf;
using arael::quaternd;
using arael::option;
using arael::result;
using arael::LmStatus;
using arael::LmPreset;
using arael::LmConfigT;
using arael::LmResultT;
using arael::LmIterT;
using arael::LmTiming;
using arael::SolveResultT;
using arael::SolveError;
using arael::CovMode;
using arael::CovError;

/// Instantiations of the shared solver surface (arael/solver.hpp) at
/// this model's precision, plus the config constructor that fetches
/// the preset's actual Rust values through this root's FFI.
using LmResult = LmResultT<double>;
using LmIter = LmIterT<double>;
using SolveResult = SolveResultT<double>;

struct LmConfig : LmConfigT<double> {
    LmConfig(LmPreset p = LmPreset::Defaults);
    static LmConfig defaults() { return LmConfig(LmPreset::Defaults); }
    static LmConfig conservative() { return LmConfig(LmPreset::Conservative); }
    static LmConfig well_conditioned() { return LmConfig(LmPreset::WellConditioned); }
};

/// Typed handle into the collection that issued it -- the C++
/// spelling of Rust's `Ref<Edge>`. Default-constructed it is the
/// null sentinel (same as Rust `Ref::default()`).
struct EdgeRef {
    uint32_t raw = UINT32_MAX;
    bool valid() const { return raw != UINT32_MAX; }
};
/// Typed handle into the collection that issued it -- the C++
/// spelling of Rust's `Ref<Pose2>`. Default-constructed it is the
/// null sentinel (same as Rust `Ref::default()`).
struct Pose2Ref {
    uint32_t raw = UINT32_MAX;
    bool valid() const { return raw != UINT32_MAX; }
};
/// Typed handle into the collection that issued it -- the C++
/// spelling of Rust's `Ref<Prior>`. Default-constructed it is the
/// null sentinel (same as Rust `Ref::default()`).
struct PriorRef {
    uint32_t raw = UINT32_MAX;
    bool valid() const { return raw != UINT32_MAX; }
};

namespace ffi {
struct Graph;
struct Edge;
struct Pose2;
struct Prior;

extern "C" {
uint32_t graph_edge_a(const Edge*);
void graph_edge_set_a(Edge*, uint32_t);
uint32_t graph_edge_b(const Edge*);
void graph_edge_set_b(Edge*, uint32_t);
vect2d graph_edge_delta(const Edge*);
void graph_edge_set_delta(Edge*, vect2d);
double graph_edge_dth(const Edge*);
void graph_edge_set_dth(Edge*, double);
double graph_edge_wt(const Edge*);
void graph_edge_set_wt(Edge*, double);
double graph_edge_wr(const Edge*);
void graph_edge_set_wr(Edge*, double);
vect2d graph_pose2_pos(const Pose2*);
void graph_pose2_set_pos(Pose2*, vect2d);
bool graph_pose2_pos_optimize(const Pose2*);
void graph_pose2_pos_set_optimize(Pose2*, bool);
double graph_pose2_rot_angle(const Pose2*);
void graph_pose2_rot_set_angle(Pose2*, double);
bool graph_pose2_rot_angle_optimize(const Pose2*);
void graph_pose2_rot_angle_set_optimize(Pose2*, bool);
matrix2d graph_pose2_rot_rotation_matrix(const Pose2*);
uint32_t graph_prior_p(const Prior*);
void graph_prior_set_p(Prior*, uint32_t);
vect2d graph_prior_pos(const Prior*);
void graph_prior_set_pos(Prior*, vect2d);
double graph_prior_th(const Prior*);
void graph_prior_set_th(Prior*, double);
int32_t graph_assemble_covariance(Graph*, uint32_t);
int32_t graph_pose2_marginal_cov(Graph*, const Pose2*, double*, uint32_t);
int32_t graph_pose2_conditional_cov(Graph*, const Pose2*, double*, uint32_t);
int32_t graph_pose2_std_dev(Graph*, const Pose2*, double*, uint32_t);
int32_t graph_pose2_pose2_cross_cov(Graph*, const Pose2*, const Pose2*, double*, uint32_t);
uint32_t graph_poses_len(const Graph*);
void graph_poses_reserve(Graph*, uint32_t);
Pose2* graph_poses_push(Graph*);
Pose2* graph_poses_at(Graph*, uint32_t);
bool graph_poses_pop(Graph*);
void graph_poses_clear(Graph*);
void graph_poses_truncate(Graph*, uint32_t);
uint32_t graph_poses_ref_at(const Graph*, uint32_t);
uint32_t graph_poses_first_ref(const Graph*);
uint32_t graph_poses_last_ref(const Graph*);
Pose2* graph_poses_get(Graph*, uint32_t);
bool graph_poses_contains(const Graph*, uint32_t);
Pose2* graph_poses_try_get(Graph*, uint32_t);
uint32_t graph_edges_len(const Graph*);
void graph_edges_reserve(Graph*, uint32_t);
Edge* graph_edges_push(Graph*);
Edge* graph_edges_at(Graph*, uint32_t);
bool graph_edges_pop(Graph*);
void graph_edges_clear(Graph*);
void graph_edges_truncate(Graph*, uint32_t);
bool graph_has_prior(const Graph*);
Prior* graph_make_prior(Graph*);
void graph_clear_prior(Graph*);
Prior* graph_prior(Graph*);
double graph_cost(Graph*);
int32_t graph_solve_band(Graph*, uint32_t, const LmConfig*, LmResult*);
void graph_lm_config(uint32_t, LmConfig*);
Graph* graph_new(void);
void graph_free(Graph*);
const char* graph_last_error(const Graph*);
const char* graph_last_report(Graph*, bool);
const char* graph_validate(Graph*);
int32_t graph_solve_dense(Graph*, const LmConfig*, LmResult*);
int32_t graph_solve_sparse(Graph*, const LmConfig*, LmResult*);
}
} // namespace ffi

inline LmConfig::LmConfig(LmPreset p) {
    ffi::graph_lm_config(uint32_t(p), this);
}

/// A `Edge` in its owner's storage; a thin pointer wrapper (validity
/// follows the storage -- see the owning container).
class Edge {
public:
    /// Optimized parameters this entity contributes to the solve.
    static constexpr uint32_t param_count = 0;
    Edge() : h_(nullptr) {}
    explicit Edge(ffi::Edge* p) : h_(p) {}
    /// False when default-constructed (e.g. inside an empty option).
    bool valid() const { return h_ != nullptr; }
    /// The underlying C pointer -- the relaxed escape hatch.
    ffi::Edge* raw() const { return h_; }
    Pose2Ref a() const { return Pose2Ref{ffi::graph_edge_a(h_)}; }
    void set_a(Pose2Ref r) { ffi::graph_edge_set_a(h_, r.raw); }
    Pose2Ref b() const { return Pose2Ref{ffi::graph_edge_b(h_)}; }
    void set_b(Pose2Ref r) { ffi::graph_edge_set_b(h_, r.raw); }
    vect2d delta() const { return ffi::graph_edge_delta(h_); }
    void set_delta(vect2d v) { ffi::graph_edge_set_delta(h_, v); }
    double dth() const { return ffi::graph_edge_dth(h_); }
    void set_dth(double v) { ffi::graph_edge_set_dth(h_, v); }
    double wt() const { return ffi::graph_edge_wt(h_); }
    void set_wt(double v) { ffi::graph_edge_set_wt(h_, v); }
    double wr() const { return ffi::graph_edge_wr(h_); }
    void set_wr(double v) { ffi::graph_edge_set_wr(h_, v); }
private:
    ffi::Edge* h_;
};

/// A `Pose2` in its owner's storage; a thin pointer wrapper (validity
/// follows the storage -- see the owning container).
class Pose2 {
public:
    /// Optimized parameters this entity contributes to the solve.
    static constexpr uint32_t param_count = 3;
    Pose2() : h_(nullptr) {}
    explicit Pose2(ffi::Pose2* p) : h_(p) {}
    /// False when default-constructed (e.g. inside an empty option).
    bool valid() const { return h_ != nullptr; }
    /// The underlying C pointer -- the relaxed escape hatch.
    ffi::Pose2* raw() const { return h_; }
    vect2d pos() const { return ffi::graph_pose2_pos(h_); }
    void set_pos(vect2d v) { ffi::graph_pose2_set_pos(h_, v); }
    bool pos_optimize() const { return ffi::graph_pose2_pos_optimize(h_); }
    void set_pos_optimize(bool v) { ffi::graph_pose2_pos_set_optimize(h_, v); }
    double rot_angle() const { return ffi::graph_pose2_rot_angle(h_); }
    void set_rot_angle(double v) { ffi::graph_pose2_rot_set_angle(h_, v); }
    bool rot_angle_optimize() const { return ffi::graph_pose2_rot_angle_optimize(h_); }
    void set_rot_angle_optimize(bool v) { ffi::graph_pose2_rot_angle_set_optimize(h_, v); }
    /// Rotation matrix at the current angle (read-only).
    matrix2d rot_rotation_matrix() const { return ffi::graph_pose2_rot_rotation_matrix(h_); }
private:
    ffi::Pose2* h_;
};

/// A `Prior` in its owner's storage; a thin pointer wrapper (validity
/// follows the storage -- see the owning container).
class Prior {
public:
    /// Optimized parameters this entity contributes to the solve.
    static constexpr uint32_t param_count = 0;
    Prior() : h_(nullptr) {}
    explicit Prior(ffi::Prior* p) : h_(p) {}
    /// False when default-constructed (e.g. inside an empty option).
    bool valid() const { return h_ != nullptr; }
    /// The underlying C pointer -- the relaxed escape hatch.
    ffi::Prior* raw() const { return h_; }
    Pose2Ref p() const { return Pose2Ref{ffi::graph_prior_p(h_)}; }
    void set_p(Pose2Ref r) { ffi::graph_prior_set_p(h_, r.raw); }
    vect2d pos() const { return ffi::graph_prior_pos(h_); }
    void set_pos(vect2d v) { ffi::graph_prior_set_pos(h_, v); }
    double th() const { return ffi::graph_prior_th(h_); }
    void set_th(double v) { ffi::graph_prior_set_th(h_, v); }
private:
    ffi::Prior* h_;
};

/// Covariance prepared at the solution (root.assemble_covariance);
/// queries answer per-entity marginal blocks. Valid until the model
/// is dropped or reassembled.
class Covariance {
public:
    Covariance() : h_(nullptr) {}
    explicit Covariance(ffi::Graph* h) : h_(h) {}
    /// Per-parameter standard deviations into out; returns the count
    /// or a negative code. Works on every CovMode incl. TriDiagonal.
    int32_t std_dev(const Pose2& e, double* out, uint32_t cap) {
        return ffi::graph_pose2_std_dev(h_, e.raw(), out, cap);
    }
    /// Row-major dim x dim conditional covariance (all other
    /// parameters held fixed) into out; returns dim or a negative code.
    int32_t conditional(const Pose2& e, double* out, uint32_t cap) {
        return ffi::graph_pose2_conditional_cov(h_, e.raw(), out, cap);
    }
    result<matrix3d, CovError> marginal(const Pose2& e) {
        double b[9];
        if (ffi::graph_pose2_marginal_cov(h_, e.raw(), b, 9) < 0) return fail<matrix3d>();
        return result<matrix3d, CovError>::ok(matrix3d::from_elements(
            b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8]));
    }
    /// Row-major Pose2::param_count x Pose2::param_count cross-covariance
    /// into out; returns the row count or a negative code.
    int32_t cross(const Pose2& a, const Pose2& b, double* out, uint32_t cap) {
        return ffi::graph_pose2_pose2_cross_cov(h_, a.raw(), b.raw(), out, cap);
    }
private:
    template<class T> result<T, CovError> fail() {
        return result<T, CovError>::err({ffi::graph_last_error(h_)});
    }
    ffi::Graph* h_;
};

/// `Graph.poses`. Element pointers are STABLE across pushes (chunked storage).
class GraphPosesVec {
public:
    explicit GraphPosesVec(ffi::Graph* h) : h_(h) {}
    uint32_t size() const { return ffi::graph_poses_len(h_); }
    bool empty() const { return size() == 0; }
    void reserve(uint32_t additional) { ffi::graph_poses_reserve(h_, additional); }
    /// Appends a default element and returns a wrapper for it.
    ///
    /// The wrapper holds a pointer INTO the collection, so it follows the
    /// std::vector rule: any later push may reallocate, and every wrapper
    /// taken before it -- including wrappers into collections nested inside
    /// these elements -- is then dangling. Either reserve() the count up
    /// front, or re-take the wrapper with operator[] after the growth.
    /// To hold on to an element across pushes, keep its Ref, not a wrapper.
    Pose2 push() { return Pose2(ffi::graph_poses_push(h_)); }
    /// Wrapper for element `i`; see push() on how long it stays valid.
    Pose2 operator[](uint32_t i) { return Pose2(ffi::graph_poses_at(h_, i)); }
    /// Front/back of a non-empty vec (empty = UB, like STL).
    Pose2 front() { return (*this)[0]; }
    Pose2 back() { return (*this)[size() - 1]; }
    /// Drops the last element; false when already empty.
    bool pop() { return ffi::graph_poses_pop(h_); }
    void clear() { ffi::graph_poses_clear(h_); }
    void truncate(uint32_t n) { ffi::graph_poses_truncate(h_, n); }
    Pose2Ref ref_at(uint32_t i) const { return Pose2Ref{ffi::graph_poses_ref_at(h_, i)}; }
    /// Ref of the first/last element; null when empty.
    Pose2Ref first_ref() const { return Pose2Ref{ffi::graph_poses_first_ref(h_)}; }
    Pose2Ref last_ref() const { return Pose2Ref{ffi::graph_poses_last_ref(h_)}; }
    Pose2 get(Pose2Ref r) { return Pose2(ffi::graph_poses_get(h_, r.raw)); }
    /// True while r addresses a live element here.
    bool contains(Pose2Ref r) const { return ffi::graph_poses_contains(h_, r.raw); }
    /// Like get, but empty for a stale or foreign ref.
    option<Pose2> try_get(Pose2Ref r) {
        ffi::Pose2* p = ffi::graph_poses_try_get(h_, r.raw);
        return p ? option<Pose2>(Pose2(p)) : option<Pose2>();
    }
    /// Bidirectional iterator. Standard C++ contract: modifying the
    /// container while iterating is undefined behavior. Dereference
    /// yields a value wrapper (Pose2), like vector<bool> --
    /// reference is a value type.
    class iterator {
    public:
        using iterator_category = std::bidirectional_iterator_tag;
        using value_type = Pose2;
        using difference_type = std::ptrdiff_t;
        using reference = Pose2;
        struct arrow { Pose2 v; Pose2* operator->() { return &v; } };
        using pointer = arrow;

        iterator() : h_(nullptr), i_(0) {}
        iterator(ffi::Graph* h, uint32_t i) : h_(h), i_(i) {}
        Pose2 operator*() const { return Pose2(ffi::graph_poses_at(h_, i_)); }
        arrow operator->() const { return arrow{**this}; }
        iterator& operator++() { ++i_; return *this; }
        iterator& operator--() { --i_; return *this; }
        iterator operator++(int) { iterator t = *this; ++*this; return t; }
        iterator operator--(int) { iterator t = *this; --*this; return t; }
        bool operator==(const iterator& o) const { return i_ == o.i_; }
        bool operator!=(const iterator& o) const { return i_ != o.i_; }
    private:
        ffi::Graph* h_;
        uint32_t i_;
    };
    iterator begin() { return iterator(h_, 0); }
    iterator end() { return iterator(h_, size()); }
    class reverse_iterator {
    public:
        using iterator_category = std::bidirectional_iterator_tag;
        using value_type = Pose2;
        using difference_type = std::ptrdiff_t;
        using reference = Pose2;
        using pointer = iterator::arrow;

        reverse_iterator() {}
        explicit reverse_iterator(iterator base) : base_(base) {}
        iterator base() const { return base_; }
        Pose2 operator*() const { iterator t = base_; --t; return *t; }
        pointer operator->() const { return pointer{**this}; }
        reverse_iterator& operator++() { --base_; return *this; }
        reverse_iterator& operator--() { ++base_; return *this; }
        reverse_iterator operator++(int) { reverse_iterator t = *this; ++*this; return t; }
        reverse_iterator operator--(int) { reverse_iterator t = *this; --*this; return t; }
        bool operator==(const reverse_iterator& o) const { return base_ == o.base_; }
        bool operator!=(const reverse_iterator& o) const { return base_ != o.base_; }
    private:
        iterator base_;
    };
    reverse_iterator rbegin() { return reverse_iterator(end()); }
    reverse_iterator rend() { return reverse_iterator(begin()); }
private:
    ffi::Graph* h_;
};

/// `Graph.edges`. std::vec::Vec storage: pushes may MOVE elements -- re-fetch element refs after a push.
class GraphEdgesVec {
public:
    explicit GraphEdgesVec(ffi::Graph* h) : h_(h) {}
    uint32_t size() const { return ffi::graph_edges_len(h_); }
    bool empty() const { return size() == 0; }
    void reserve(uint32_t additional) { ffi::graph_edges_reserve(h_, additional); }
    /// Appends a default element and returns a wrapper for it.
    ///
    /// The wrapper holds a pointer INTO the collection, so it follows the
    /// std::vector rule: any later push may reallocate, and every wrapper
    /// taken before it -- including wrappers into collections nested inside
    /// these elements -- is then dangling. Either reserve() the count up
    /// front, or re-take the wrapper with operator[] after the growth.
    /// To hold on to an element across pushes, keep its Ref, not a wrapper.
    Edge push() { return Edge(ffi::graph_edges_push(h_)); }
    /// Wrapper for element `i`; see push() on how long it stays valid.
    Edge operator[](uint32_t i) { return Edge(ffi::graph_edges_at(h_, i)); }
    /// Front/back of a non-empty vec (empty = UB, like STL).
    Edge front() { return (*this)[0]; }
    Edge back() { return (*this)[size() - 1]; }
    /// Drops the last element; false when already empty.
    bool pop() { return ffi::graph_edges_pop(h_); }
    void clear() { ffi::graph_edges_clear(h_); }
    void truncate(uint32_t n) { ffi::graph_edges_truncate(h_, n); }
    /// Bidirectional iterator. Standard C++ contract: modifying the
    /// container while iterating is undefined behavior. Dereference
    /// yields a value wrapper (Edge), like vector<bool> --
    /// reference is a value type.
    class iterator {
    public:
        using iterator_category = std::bidirectional_iterator_tag;
        using value_type = Edge;
        using difference_type = std::ptrdiff_t;
        using reference = Edge;
        struct arrow { Edge v; Edge* operator->() { return &v; } };
        using pointer = arrow;

        iterator() : h_(nullptr), i_(0) {}
        iterator(ffi::Graph* h, uint32_t i) : h_(h), i_(i) {}
        Edge operator*() const { return Edge(ffi::graph_edges_at(h_, i_)); }
        arrow operator->() const { return arrow{**this}; }
        iterator& operator++() { ++i_; return *this; }
        iterator& operator--() { --i_; return *this; }
        iterator operator++(int) { iterator t = *this; ++*this; return t; }
        iterator operator--(int) { iterator t = *this; --*this; return t; }
        bool operator==(const iterator& o) const { return i_ == o.i_; }
        bool operator!=(const iterator& o) const { return i_ != o.i_; }
    private:
        ffi::Graph* h_;
        uint32_t i_;
    };
    iterator begin() { return iterator(h_, 0); }
    iterator end() { return iterator(h_, size()); }
    class reverse_iterator {
    public:
        using iterator_category = std::bidirectional_iterator_tag;
        using value_type = Edge;
        using difference_type = std::ptrdiff_t;
        using reference = Edge;
        using pointer = iterator::arrow;

        reverse_iterator() {}
        explicit reverse_iterator(iterator base) : base_(base) {}
        iterator base() const { return base_; }
        Edge operator*() const { iterator t = base_; --t; return *t; }
        pointer operator->() const { return pointer{**this}; }
        reverse_iterator& operator++() { --base_; return *this; }
        reverse_iterator& operator--() { ++base_; return *this; }
        reverse_iterator operator++(int) { reverse_iterator t = *this; ++*this; return t; }
        reverse_iterator operator--(int) { reverse_iterator t = *this; --*this; return t; }
        bool operator==(const reverse_iterator& o) const { return base_ == o.base_; }
        bool operator!=(const reverse_iterator& o) const { return base_ != o.base_; }
    private:
        iterator base_;
    };
    reverse_iterator rbegin() { return reverse_iterator(end()); }
    reverse_iterator rend() { return reverse_iterator(begin()); }
private:
    ffi::Graph* h_;
};

/// The `Graph` model. Owns the Rust-side object; move-only.
class Graph {
public:
    Graph() : h_(ffi::graph_new()) {}
    ~Graph() { if (h_) ffi::graph_free(h_); }
    Graph(const Graph&) = delete;
    Graph& operator=(const Graph&) = delete;
    Graph(Graph&& o) noexcept : h_(o.h_) { o.h_ = nullptr; }
    Graph& operator=(Graph&& o) noexcept {
        if (this != &o) {
            if (h_) ffi::graph_free(h_);
            h_ = o.h_;
            o.h_ = nullptr;
        }
        return *this;
    }

    GraphPosesVec poses() { return GraphPosesVec(h_); }
    GraphEdgesVec edges() { return GraphEdgesVec(h_); }
    bool has_prior() const { return ffi::graph_has_prior(h_); }
    Prior make_prior() { return Prior(ffi::graph_make_prior(h_)); }
    void clear_prior() { ffi::graph_clear_prior(h_); }
    option<Prior> prior() {
        ffi::Prior* p = ffi::graph_prior(h_);
        return p ? option<Prior>(Prior(p)) : option<Prior>();
    }

    /// Ok(LmResult) for every healthy termination, Err(SolveError) for
    /// a solve failure (-1) or a caught panic (-2) -- the same split
    /// Rust's SolveResult makes.
    SolveResult solve_dense(const LmConfig& cfg = LmConfig{}) {
        LmResult r;
        int32_t code = ffi::graph_solve_dense(h_, &cfg, &r);
        if (code >= 0) return SolveResult::ok(r);
        return SolveResult::err({static_cast<LmStatus>(code), last_error()});
    }
    SolveResult solve_sparse(const LmConfig& cfg = LmConfig{}) {
        LmResult r;
        int32_t code = ffi::graph_solve_sparse(h_, &cfg, &r);
        if (code >= 0) return SolveResult::ok(r);
        return SolveResult::err({static_cast<LmStatus>(code), last_error()});
    }
    /// Band Cholesky solve for banded Hessians; kd is the half-bandwidth
    /// in scalar parameters.
    SolveResult solve_band(uint32_t kd, const LmConfig& cfg = LmConfig{}) {
        LmResult r;
        int32_t code = ffi::graph_solve_band(h_, kd, &cfg, &r);
        if (code >= 0) return SolveResult::ok(r);
        return SolveResult::err({static_cast<LmStatus>(code), last_error()});
    }
    /// Total cost at the current parameter values (f64 evaluation).
    double cost() { return ffi::graph_cost(h_); }
    /// Prepare the covariance at the current (solved) parameters; query
    /// per-entity marginals on the returned view.
    result<Covariance, CovError> assemble_covariance(CovMode mode = CovMode::AllMarginals) {
        if (ffi::graph_assemble_covariance(h_, uint32_t(mode)) != 0)
            return result<Covariance, CovError>::err({last_error()});
        return result<Covariance, CovError>::ok(Covariance(h_));
    }
    /// Empty string when the model is clean, the Diagnostic text
    /// otherwise. The returned pointer is valid until the next call on
    /// this model.
    const char* validate() { return ffi::graph_validate(h_); }
    const char* last_error() const { return ffi::graph_last_error(h_); }
    /// Text report of the last completed solve (status, cost,
    /// iterations, timing and the backend's plan when gathered); ""
    /// before the first solve. Valid until the next report call.
    const char* last_report() { return ffi::graph_last_report(h_, false); }
    /// last_report() with colour and box-drawing glyphs.
    const char* last_pretty_report() { return ffi::graph_last_report(h_, true); }

private:
    ffi::Graph* h_;
};

} // namespace m3500_demo
